### ISSUE TITLE
[Flowbroker] Publishing on device using device out node causes persister failure

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1095]
Publishing on device using device out node causes persister failure.

```
persister_1                   | Exception in thread Persister:
persister_1                   | Traceback (most recent call last):
persister_1                   |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
persister_1                   |     self.run()
persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a4-py3.6.egg/dojot/module/kafka/consumer.py", line 123, in run
persister_1                   |     self.callback(msg.topic, msg.value)
persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a4-py3.6.egg/dojot/module/messenger.py", line 327, in __process_kafka_messages
persister_1                   |     self.emit(self.topics[topic]['subject'], self.topics[topic]['tenant'], "message", messages)
persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a4-py3.6.egg/dojot/module/messenger.py", line 194, in emit
persister_1                   |     callback(tenant, data)
persister_1                   |   File "history/subscriber/persister.py", line 136, in handle_event_data
persister_1                   |     del metadata['timestamp']
persister_1                   | KeyError: 'timestamp'
```

**Affected Version**: 61.1-20190423

**Comment by betefaber** [comment]
Test OK.

```
persister_1                   | [31/05/19 - 15:04:47] |messenger| INFO: Emitting new event message for subject device-data@admin
persister_1                   | [31/05/19 - 15:04:47] |persister| INFO: Received data: {'metadata': {'deviceid': '12321e', 'tenant': 'admin', 'timestamp': 1559315086010}, 'attrs': {'velocidade': 70}}
persister_1                   | [31/05/19 - 15:04:47] |persister| DEBUG: got data event b'{"metadata":{"deviceid":"12321e","tenant":"admin","timestamp":1559315086010},"attrs":{"velocidade":70}}'
persister_1                   | [31/05/19 - 15:04:48] |messenger| INFO: Emitting new event message for subject device-data@admin
persister_1                   | [31/05/19 - 15:04:48] |persister| INFO: Received data: {'metadata': {'deviceid': 'a03cf0', 'tenant': 'admin', 'timestamp': 1559315087049}, 'attrs': {'mensagem': 'vento muito forte'}}
persister_1                   | [31/05/19 - 15:04:48] |persister| DEBUG: got data event b'{"metadata":{"deviceid":"a03cf0","tenant":"admin","timestamp":1559315087049},"attrs":{"mensagem":"vento muito forte"}}'
```

```
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: Got a message in topic 6c6086fb-f1a8-4934-8063-f37ffe264ebc.
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: There are 1 callbacks registered.
flowbroker_1                  | <15:04:47 31/05/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 31 32 33 32 31 65 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
flowbroker_1                  |   size: 103,
flowbroker_1                  |   key: null,
flowbroker_1                  |   topic: '6c6086fb-f1a8-4934-8063-f37ffe264ebc',
flowbroker_1                  |   offset: 4,
flowbroker_1                  |   partition: 0,
flowbroker_1                  |   timestamp: 1559315086010 }
flowbroker_1                  | <15:04:47 31/05/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"deviceid\":\"12321e\",\"tenant\":\"admin\",\"timestamp\":1559315086010},\"attrs\":{\"velocidade\":70}}"}
flowbroker_1                  | retriving data related to admin:12321e from cache
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [ingestor] got new device event: { metadata: { tenant: 'admin', timestamp: 1559315086010 },
flowbroker_1                  |   event: 'publish',
flowbroker_1                  |   data: { attrs: { velocidade: 70 }, id: '12321e' } }
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [executor] will handle node switch
flowbroker_1                  | debug: Executing switch node...
flowbroker_1                  | debug: ... switch node was successfully executed.
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [executor] hop (switch) result: [{"payload":{"velocidade":70}}]
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [executor] will handle node change
flowbroker_1                  | debug: Executing change node...
flowbroker_1                  | debug: ... change node was successfully executed.
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [executor] hop (change) result: [{"payload":{"velocidade":70},"saida":{"mensagem":"vento muito forte"}}]
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [executor] will handle node device out
flowbroker_1                  | debug: Executing device-out node...
flowbroker_1                  | debug: Updating device...
flowbroker_1                  | debug: Message is: { metadata: { deviceid: 'a03cf0', tenant: 'admin', timestamp: 1559315087049 },
flowbroker_1                  |   attrs: { mensagem: 'vento muito forte' } }
flowbroker_1                  | object
flowbroker_1                  | will produce { metadata: { deviceid: 'a03cf0', tenant: 'admin', timestamp: 1559315087049 },
flowbroker_1                  |   attrs: { mensagem: 'vento muito forte' } } to device-data:admin
flowbroker_1                  | <15:04:47 31/05/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device':
flowbroker_1                  |    { admin: 'a4ea2578-aab1-498a-a50a-ae3467370712',
flowbroker_1                  |      teste: 'e58a4b18-89d6-4cb5-9861-13adde6cb436' },
flowbroker_1                  |   'device-data':
flowbroker_1                  |    { admin: '6c6086fb-f1a8-4934-8063-f37ffe264ebc',
flowbroker_1                  |      teste: 'ddd09edf-31cc-482b-9426-b2ee22046a6b' },
flowbroker_1                  |   'dojot.notifications':
flowbroker_1                  |    { admin: '554a3868-3c15-4284-9265-0ba8bf028845',
flowbroker_1                  |      teste: '30c926b3-75a0-445f-8c9d-0621fdb275c4' } }
flowbroker_1                  | debug: ... device was updated.
flowbroker_1                  | debug: ... device-out node was successfully executed.
flowbroker_1                  | <15:04:47 31/05/2019> -- DEBUG: [executor] hop (device out) result: undefined
flowbroker_1                  | <15:04:48 31/05/2019> -- DEBUG: Got a message in topic 6c6086fb-f1a8-4934-8063-f37ffe264ebc.
flowbroker_1                  | <15:04:48 31/05/2019> -- DEBUG: There are 1 callbacks registered.
flowbroker_1                  | <15:04:48 31/05/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 61 30 33 63 66 30 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
flowbroker_1                  |   size: 118,
flowbroker_1                  |   key: null,
flowbroker_1                  |   topic: '6c6086fb-f1a8-4934-8063-f37ffe264ebc',
flowbroker_1                  |   offset: 5,
flowbroker_1                  |   partition: 0,
flowbroker_1                  |   timestamp: 1559315087050 }
flowbroker_1                  | <15:04:48 31/05/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
flowbroker_1                  | <15:04:48 31/05/2019> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <15:04:48 31/05/2019> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"deviceid\":\"a03cf0\",\"tenant\":\"admin\",\"timestamp\":1559315087049},\"attrs\":{\"mensagem\":\"vento muito forte\"}}"}
flowbroker_1                  | retriving data related to admin:a03cf0 from cache
flowbroker_1                  | <15:04:48 31/05/2019> -- DEBUG: [ingestor] got new device event: { metadata: { tenant: 'admin', timestamp: 1559315087049 },
flowbroker_1                  |   event: 'publish',
flowbroker_1                  |   data: { attrs: { mensagem: 'vento muito forte' }, id: 'a03cf0' } }
```

Tested on Version: **62.2-20190524**
