### ISSUE TITLE
Problem recreating a user

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1221]
When the user is recreated, their data is recovered. However, nodes do not appear when creating a new flow and their device data is not published.

**Steps to reproduce the problem:**

- The mg_data and pg_data volumes were created. The data was persisted. 

- Registered Tenants

```
{
    "tenants": [
        "admin",
        "xxx"
    ]
}
```

- Delete the last user of tenant "xxx"

```
auth_1                        | [07/08/19 - 15:04:48] |PDPController| INFO: checking for group permissions
auth_1                        | [07/08/19 - 15:04:48] |PDPController| INFO: user 1 permit to DELETE on /auth/user/67/ registered on cache
auth_1                        | [07/08/19 - 15:04:48] |CRUDController| INFO: user eduardo deleted by admin
auth_1                        | [07/08/19 - 15:04:48] |CRUDController| INFO: {'id': '67', 'name': 'Eduardo', 'username': 'eduardo', 'service': 'xxx', 'email': 'edu@noemail.com', 'profile': 'admin', 'created_date': '2019-08-07 14:50:43.637142', 'created_by': '1'}
auth_1                        | [07/08/19 - 15:04:48] |CRUDController| INFO: will emit tenant lifecycle event xxx - DELETE
auth_1                        | [07/08/19 - 15:04:48] |PDPController| INFO: user 1 permit to GET on /auth/user/ from cache
```
 - Registered Tenants

```
{
    "tenants": [
        "admin"
    ]
}
```

- Restart dojot

```
docker-compose -p dojot down
docker rm -f $(docker ps -aq)  ---> to remove remote nodes
docker-compose -p dojot up -d
wait for ejbca to rise
```

- **Recreate the deleted user (user + tenant) via API**

```
auth_1                        | Exception in thread Thread-2:
auth_1                        | Traceback (most recent call last):
auth_1                        |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
auth_1                        |     self.run()
auth_1                        |   File "/usr/src/app/auth/controller/KafkaPublisher.py", line 56, in run
auth_1                        |     self.init()
auth_1                        |   File "/usr/src/app/auth/controller/KafkaPublisher.py", line 43, in init
auth_1                        |     cls.messenger = Messenger("dojot.auth", config)
auth_1                        |   File "/usr/src/venv/lib/python3.6/site-packages/dojot/module/messenger.py", line 79, in __init__
auth_1                        |     self.producer.init()
auth_1                        |   File "/usr/src/venv/lib/python3.6/site-packages/dojot/module/kafka/producer.py", line 33, in init
auth_1                        |     bootstrap_servers=self.broker)
auth_1                        |   File "/usr/src/venv/lib/python3.6/site-packages/kafka/producer/kafka.py", line 362, in __init__
auth_1                        |     **self.config)
auth_1                        |   File "/usr/src/venv/lib/python3.6/site-packages/kafka/client_async.py", line 219, in __init__
auth_1                        |     self.config['api_version'] = self.check_version(timeout=check_timeout)
auth_1                        |   File "/usr/src/venv/lib/python3.6/site-packages/kafka/client_async.py", line 819, in check_version
auth_1                        |     raise Errors.NoBrokersAvailable()
auth_1                        | kafka.errors.NoBrokersAvailable: NoBrokersAvailable
auth_1                        | 
auth_1                        | [07/08/19 - 15:20:41] |PDPController| INFO: checking for group permissions
auth_1                        | [07/08/19 - 15:20:41] |PDPController| INFO: user 1 permit to POST on /auth/user/ registered on cache
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: Creating new user...
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: Reading request...
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: ... request is:
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: {'username': 'eduardo', 'service': 'xxx', 'email': 'edu@noemail.com', 'name': 'Eduardo', 'profile': 'admin'}
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: Inserting user into database...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Checking user data...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... user data is OK.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Checking whether user already exist...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... user doesn't exist.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Checking whether user e-mail is already being used...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... user e-mail is not being used.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Creating user instance...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... user instance was created.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: User data is: eduardo created by admin
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Configuring Kong...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... Kong was successfully configured.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Adding new user to database session...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... new user was added to database session.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Committing database changes...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... database changes were committed.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Configuring user profile...
auth_1                        | [07/08/19 - 15:20:41] |RelationshipController| INFO: user eduardo added to group admin by admin
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... user profile was configured.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Configuring user password...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... user password was configured.
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: Sending tenant creation message to other components...
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| INFO: Will emit tenant lifecycle event xxx - CREATE
auth_1                        | [07/08/19 - 15:20:41] |CRUDController| DEBUG: ... tenant creation message was sent.
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: ... user data was inserted into the database.
auth_1                        | [07/08/19 - 15:20:41] |webRoutes| DEBUG: ... new user was created.
```

- Login with this user

- Nodes do not appear (#608)

![Screenshot at 2019-08-07 12-22-18](https://user-images.githubusercontent.com/37310063/62645749-396dc580-b923-11e9-856b-ae4525ed9ac3.png)

`flowbroker_1                  | <15:22:12 07/08/2019> -- |auth -- DEBUG: will ignore /red/keymap.json
`
- Data is not published. (#799)

mosquitto_pub -t /xxx/3aac40/attrs -m '{"int":40}'

```
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Authenticating MQTT client
iotagent-mqtt_1               | {"pid":7,"hostname":"c46ef73e7c1e","name":"MoscaServer","level":30,"time":1565191586288,"msg":"client connected","client":"mosqpub|2717-efaber-Opt","v":1}
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- INFO: client up
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Authorizing MQTT client mosqpub|2717-efaber-Opt to publish to /xxx/3aac40/attrs
iotagent-mqtt_1               | {"pid":7,"hostname":"c46ef73e7c1e","name":"MoscaServer","level":30,"time":1565191586290,"msg":"closed","client":"mosqpub|2717-efaber-Opt","v":1}
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- INFO: client down
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- |iotagent -- INFO: Getting device from http://device-manager:5000/device/3aac40
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- INFO: Parameters are: url: http://device-manager:5000/device/3aac40, headers: { authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoieHh4IiwidXNlcm5hbWUiOiJpb3RhZ2VudC1tcXR0In0=.ZHVtbXkgc2lnbmF0dXJl' }, method: get, TAG
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Got device {"attrs":{"1":[{"created":"2019-08-07T15:23:46.361306+00:00","id":1,"is_static_overridden":false,"label":"int","static_value":"","template_id":"1","type":"dynamic","value_type":"integer"}]},"created":"2019-08-07T15:23:57.725445+00:00","id":"3aac40","label":"d","templates":[1]}
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Expected topic is /xxx/3aac40/attrs
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Device published on topic /xxx/3aac40/attrs
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Authorized client mosqpub|2717-efaber-Opt to publish to topic /xxx/3aac40/attrs
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- DEBUG: Published data: {"int":40}, client: mosqpub|2717-efaber-Opt, topic: /xxx/3aac40/attrs
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data': { admin: 'b31c0a2b-aaba-43dd-809b-ff80d315c7ac' } }
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- |messenger -- WARN: No producer was created for subject device-data@xxx. Maybe this tenant doesn't exist?
iotagent-mqtt_1               | <15:26:26 07/08/2019> -- |messenger -- WARN: Message {"metadata":{"deviceid":"3aac40","tenant":"xxx","timestamp":1565191586336},"attrs":{"int":40}} is being discarded!
```
Affected version: **63.1-20190705**

**Comment by betefaber** [comment]
The problem only occurs if the user and tenant have already been created.

If one of them is new (user or tenant), the problem does not happen.

**Comment by bizetti** [comment]
Ticket analyis (Dec, 27th): Important in one next version.

**Comment by bizetti** [comment]
Won't be fixed. It's rare.
