### ISSUE TITLE
[History] [Persister] Configure log level using an endpoint or environment variable

### ISSUE THREAD

**Issue by juliamourac** [dojot/dojot#1241]

**Comment by betefaber** [comment]
**history:** log level setting

by environment variable:

- LOG_LEVEL = INFO
```
~$ kubectl -n dojot logs -f --tail 1000 history-5b779b987d-894ql
[2020-06-24 18:59:52 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 18:59:52 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 18:59:52 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 18:59:52 +0000] [8] [INFO] Booting worker with pid: 8


```
```
$ kubectl -n dojot exec -it history-5b779b987d-894ql -- sh
/usr/src/app # echo $LOG_LEVEL
INFO

```

- LOG_LEVEL = info
```
$ kubectl -n dojot logs -f --tail 1000 history-55cbb64cfd-8n9sj
[2020-06-24 19:01:42 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:01:42 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:01:42 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:01:42 +0000] [8] [INFO] Booting worker with pid: 8
[2020-06-24 19:01:45 +0000] [6] [INFO] Shutting down: Master
[2020-06-24 19:01:45 +0000] [6] [INFO] Reason: Worker failed to boot.

```
![history_info](https://user-images.githubusercontent.com/37310063/85620514-46c69800-b63a-11ea-8585-fc7f72b7a800.png)


- LOG_LEVEL = DEBUG
```
$ kubectl -n dojot logs -f --tail 1000 history-799ff9b555-s5w28
[2020-06-24 19:04:14 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:04:14 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:04:14 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:04:14 +0000] [8] [INFO] Booting worker with pid: 8

```
```
$ kubectl -n dojot exec -it history-799ff9b555-s5w28 -- sh
/usr/src/app # echo $LOG_LEVEL
DEBUG

```

- LOG_LEVEL = debug
```
$ kubectl -n dojot logs -f --tail 1000 history-9c8d78475-hpdlp
[2020-06-24 19:06:22 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:06:22 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:06:22 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:06:22 +0000] [8] [INFO] Booting worker with pid: 8
[2020-06-24 19:06:26 +0000] [6] [INFO] Shutting down: Master
[2020-06-24 19:06:26 +0000] [6] [INFO] Reason: Worker failed to boot.

````
![history_debug](https://user-images.githubusercontent.com/37310063/85620565-5940d180-b63a-11ea-8d84-dd30812f1762.png)



- LOG_LEVEL = WARNING
```
$ kubectl -n dojot logs -f --tail 1000 history-8484cb5b84-5grtq
[2020-06-24 19:08:39 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:08:39 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:08:39 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:08:39 +0000] [8] [INFO] Booting worker with pid: 8

```
```
$ kubectl -n dojot exec -it history-8484cb5b84-5grtq -- sh
/usr/src/app # echo $LOG_LEVEL
WARNING

```
- LOG_LEVEL = warning
```
$ kubectl -n dojot logs -f --tail 1000 history-5c87d9db8-89rl9
[2020-06-24 19:11:41 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:11:41 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
[2020-06-24 19:11:41 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 19:11:41 +0000] [9] [INFO] Booting worker with pid: 9
[2020-06-24 19:11:43 +0000] [7] [INFO] Shutting down: Master
[2020-06-24 19:11:43 +0000] [7] [INFO] Reason: Worker failed to boot.

```
![history_warning](https://user-images.githubusercontent.com/37310063/85620649-7675a000-b63a-11ea-8d5f-cc63c3a253e6.png)

- LOG_LEVEL = ERROR
```
$ kubectl -n dojot logs -f --tail 1000 history-7df859c7d-jdlnx
[2020-06-24 19:13:40 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:13:40 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:13:40 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:13:40 +0000] [8] [INFO] Booting worker with pid: 8

```
```
$ kubectl -n dojot exec -it history-7df859c7d-jdlnx -- sh
/usr/src/app # echo $LOG_LEVEL
ERROR

```
- LOG_LEVEL = error
```
~$ kubectl -n dojot logs -f --tail 1000 history-dbd6d4b46-gst2x
[2020-06-24 19:15:38 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:15:38 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:15:38 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:15:38 +0000] [8] [INFO] Booting worker with pid: 8
[2020-06-24 19:15:41 +0000] [6] [INFO] Shutting down: Master
[2020-06-24 19:15:41 +0000] [6] [INFO] Reason: Worker failed to boot.

```
![history_error](https://user-images.githubusercontent.com/37310063/85620664-7c6b8100-b63a-11ea-8f8f-56fd6a23a586.png)

- LOG_LEVEL = CRITICAL
```
$ kubectl -n dojot logs -f --tail 1000 history-7db888d6cf-x6lvq
[2020-06-24 19:17:16 +0000] [12] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:17:16 +0000] [12] [INFO] Listening at: http://0.0.0.0:8000 (12)
[2020-06-24 19:17:16 +0000] [12] [INFO] Using worker: gevent
[2020-06-24 19:17:16 +0000] [14] [INFO] Booting worker with pid: 14

```
```
$ kubectl -n dojot exec -it history-7db888d6cf-x6lvq -- sh
/usr/src/app # echo $LOG_LEVEL
CRITICAL
```

- LOG_LEVEL = critical
```
~$ kubectl -n dojot logs -f --tail 1000 history-77c4b684dc-6nxbd
[2020-06-24 19:19:03 +0000] [6] [INFO] Starting gunicorn 19.6.0
[2020-06-24 19:19:03 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
[2020-06-24 19:19:03 +0000] [6] [INFO] Using worker: gevent
[2020-06-24 19:19:03 +0000] [8] [INFO] Booting worker with pid: 8
[2020-06-24 19:19:05 +0000] [6] [INFO] Shutting down: Master
[2020-06-24 19:19:05 +0000] [6] [INFO] Reason: Worker failed to boot.

```
![history_critical](https://user-images.githubusercontent.com/37310063/85620688-83928f00-b63a-11ea-8990-1fdd26bceb30.png)

----
by endpoint:

```
curl -X PUT 10.50.11.97:30001/history/log?level=debug -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{"new_log_level": "DEBUG"}

curl -X GET 10.50.11.97:30001/history/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json" 2>/dev/null
{"log_level": "DEBUG"}

curl -X PUT 10.50.11.97:30001/history/log?level=info -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{"new_log_level": "INFO"}

curl -X GET 10.50.11.97:30001/history/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json" 2>/dev/null
{"log_level": "INFO"}

curl -X PUT 10.50.11.97:30001/history/log?level=warning -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{"new_log_level": "WARNING"}

curl -X GET 10.50.11.97:30001/history/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json" 2>/dev/null
{"log_level": "WARNING"}

curl -X PUT 10.50.11.97:30001/history/log?level=error -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{"new_log_level": "ERROR"}

curl -X GET 10.50.11.97:30001/history/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json" 2>/dev/null
{"log_level": "ERROR"}

curl -X PUT 10.50.11.97:30001/history/log?level=critical -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{"new_log_level": "CRITICAL"}

curl -X GET 10.50.11.97:30001/history/log -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json" 2>/dev/null
{"log_level": "CRITICAL"}

curl -X PUT 10.50.11.97:30001/history/log?level=warn -H "Authorization: Bearer ${JWT}" -H "Content-Type:application/json"
{
    "title": "Invalid parameter",
    "description": "The \"level\" parameter is invalid. Logging level must be DEBUG, INFO, WARNING, ERROR or CRITICAL!"
}
```

**Comment by betefaber** [comment]
**persister**: log level setting

by environment variable:

- LOG_LEVEL = DEBUG
```
[24/06/20 - 20:41:47] |persister| INFO: Received data: {'metadata': {'deviceid': 'a3b7f8', 'tenant': 'admin', 'timestamp': 1593031306}, 'attrs': {'chuva': 4}}
[24/06/20 - 20:41:47] |persister| DEBUG: got data event b'{"metadata":{"deviceid":"a3b7f8","tenant":"admin","timestamp":1593031306},"attrs":{"chuva":4}}'
[24/06/20 - 20:41:48] |persister| INFO: Received data: {'attrs': {'medida': '41'}, 'metadata': {'timestamp': 1593031308605, 'tenant': 'admin', 'deviceid': '46f2ac'}}
[24/06/20 - 20:41:48] |persister| DEBUG: got data event b'{"attrs":{"medida":"41"},"metadata":{"timestamp":1593031308605,"tenant":"admin","deviceid":"46f2ac"}}'
[24/06/20 - 20:41:48] |persister| INFO: Received data: {'attrs': {'data': {'attrs': {'chuva': 4, 'chuva60min': 41}}}, 'metadata': {'timestamp': 1593031308767, 'tenant': 'admin', 'deviceid': '2ffc04'}}
[24/06/20 - 20:41:48] |persister| DEBUG: got data event b'{"attrs":{"data":{"attrs":{"chuva":4,"chuva60min":41}}},"metadata":{"timestamp":1593031308767,"tenant":"admin","deviceid":"2ffc04"}}'
[24/06/20 - 20:41:49] |persister| DEBUG: Received a notification: {'msgID': 'dc1598a8-2c56-4438-95cd-fac2f4303bd6', 'timestamp': 1593031309233, 'message': 'teste', 'metaAttrsFilter': {'statusCode': 200, 'headers': {'access-control-allow-origin': '*', 'content-type': 'text/html; charset=utf-8', 'x-cloud-trace-context': '6298d445612a749b55c245ed738b6571', 'date': 'Wed, 24 Jun 2020 20:41:49 GMT', 'server': 'Google Frontend', 'content-length': '54', 'connection': 'close'}, 'responseUrl': 'http://ptsv2.com/t/3fbhu-1543424220/post', 'payload': 'Thank you for this dump. I hope you have a lovely day!', 'shouldPersist': True}, 'subject': 'user_notification'}. Will check if it will be persisted.
[24/06/20 - 20:41:49] |persister| DEBUG: Notification should be persisted.
```
```
~$ kubectl -n dojot exec -it persister-67d8888566-267qd -- sh
/usr/src/app # echo $LOG_LEVEL
DEBUG
```

- LOG_LEVEL = debug
```
$ kubectl -n dojot logs -f --tail 1000 persister-5f78c7b566-r8r4t
[2020-06-24 20:44:44 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 20:44:44 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 20:44:44 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 20:44:44 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'debug'
```


- LOG_LEVEL = INFO
```
[24/06/20 - 20:47:06] |persister| INFO: Received data: {'metadata': {'deviceid': 'a3b7f8', 'tenant': 'admin', 'timestamp': 1593031625}, 'attrs': {'chuva': 4}}
[24/06/20 - 20:47:06] |persister| INFO: Received data: {'attrs': {'medida': '45'}, 'metadata': {'timestamp': 1593031626718, 'tenant': 'admin', 'deviceid': '46f2ac'}}
[24/06/20 - 20:47:06] |persister| INFO: Received data: {'attrs': {'data': {'attrs': {'chuva': 4, 'chuva60min': 45}}}, 'metadata': {'timestamp': 1593031626867, 'tenant': 'admin', 'deviceid': '2ffc04'}}
```
```
$ kubectl -n dojot exec -it persister-68b6c6c5d9-vhvxm -- sh
/usr/src/app # echo $LOG_LEVEL
INFO
```

- LOG_LEVEL = info
```
$ kubectl -n dojot logs -f --tail 1000 persister-797988d8b9-rrtpl
[2020-06-24 20:48:45 +0000] [8] [INFO] Starting gunicorn 19.6.0
[2020-06-24 20:48:45 +0000] [8] [INFO] Listening at: http://0.0.0.0:8057 (8)
[2020-06-24 20:48:45 +0000] [8] [INFO] Using worker: gevent
[2020-06-24 20:48:45 +0000] [14] [INFO] Booting worker with pid: 14
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'info'
````

- LOG_LEVEL = WARNING

No warning messages

```
$ kubectl -n dojot logs -f --tail 1000 persister-b4784b96f-tlzpc
[2020-06-24 20:59:33 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 20:59:33 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 20:59:33 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 20:59:33 +0000] [13] [INFO] Booting worker with pid: 13
```
```
$ kubectl -n dojot exec -it persister-b4784b96f-tlzpc -- sh
/usr/src/app # echo $LOG_LEVEL
WARNING
```
- LOG_LEVEL = warning
```
$ kubectl -n dojot logs -f --tail 1000 persister-7bfddf565-chhkp
[2020-06-24 21:02:01 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 21:02:01 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 21:02:01 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 21:02:01 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'warning'
```

- LOG_LEVEL = ERROR

No error messages

```
$ kubectl -n dojot logs -f --tail 1000 persister-79d59c7579-pxtff
[2020-06-24 21:02:59 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 21:02:59 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 21:02:59 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 21:02:59 +0000] [13] [INFO] Booting worker with pid: 13
```
```
$ kubectl -n dojot exec -it persister-79d59c7579-pxtff -- sh
/usr/src/app # echo $LOG_LEVEL
ERROR
```
- LOG_LEVEL = error
```
~$ kubectl -n dojot logs -f --tail 1000 persister-567dd46795-wf4p2
[2020-06-24 21:07:17 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 21:07:17 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 21:07:17 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 21:07:17 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'error'
```

- LOG_LEVEL = CRITICAL

No critical messages

```
$ kubectl -n dojot logs -f --tail 1000 persister-7877f8cf48-lfl28
[2020-06-24 21:08:12 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 21:08:12 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 21:08:12 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 21:08:12 +0000] [13] [INFO] Booting worker with pid: 13
```
```
~$ kubectl -n dojot exec -it persister-7877f8cf48-lfl28 -- sh
/usr/src/app # echo $LOG_LEVEL
CRITICAL
```

- LOG_LEVEL = critical
```
$ kubectl -n dojot logs -f --tail 1000 persister-7b7cbcd588-x8ln8
[2020-06-24 21:10:37 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-24 21:10:37 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-24 21:10:37 +0000] [7] [INFO] Using worker: gevent
[2020-06-24 21:10:37 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'critical'
```

**Comment by betefaber** [comment]
The problems found were reported in the tickets:

#1513 , #1515 , #1516 , #1504
