### ISSUE TITLE
[kubernetes] Kafka is not consuming tenancy information

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1262]
If the kafka address is incorrectly configured in auth, the thread dies but the container is still running.
```
[17/10/19 - 13:15:02] |webRoutes| DEBUG: ... publisher initialization thread started.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/src/app/auth/controller/KafkaPublisher.py", line 56, in run
    self.init()
  File "/usr/src/app/auth/controller/KafkaPublisher.py", line 43, in init
    cls.messenger = Messenger("dojot.auth", config)
  File "/usr/src/venv/lib/python3.6/site-packages/dojot/module/messenger.py", line 79, in __init__
    self.producer.init()
  File "/usr/src/venv/lib/python3.6/site-packages/dojot/module/kafka/producer.py", line 33, in init
    bootstrap_servers=self.broker)
  File "/usr/src/venv/lib/python3.6/site-packages/kafka/producer/kafka.py", line 362, in __init__
    **self.config)
  File "/usr/src/venv/lib/python3.6/site-packages/kafka/client_async.py", line 219, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/src/venv/lib/python3.6/site-packages/kafka/client_async.py", line 819, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

[17/10/19 - 13:15:47] |PDPController| INFO: checking for group permissions
[17/10/19 - 13:15:47] |PDPController| INFO: user 4 permit to GET on /auth/user/ registered on cache
```
**Note**: the correct name of the environment variable is KAFKA_HOSTS

Affected version: **v0.4.0**

**Comment by betefaber** [comment]
Issue resolved with KAFKA_HOSTS environment variable correction (related with #1273).

**Comment by betefaber** [comment]
The environment variable has been corrected:
```
        - name: KAFKA_HOSTS
          value: kafka-server:9092
```
