### ISSUE TITLE
[Flow broker] 'Request body' should not be mandatory - http node

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#1298]
Applied to version 0.4.0.
the field 'Request body' should not be mandatory in http node. 
For example,  we can send a Get request without body

**Comment by bizetti** [comment]
Ticket analysis meeting (April, 3rd): Severity: High, but Priority: Low. Fix for 0.5.

**Comment by betefaber** [comment]
Flow execution error when sending a GET request without a body.

```
<20:09:21 24/06/2020> -- |http -- DEBUG: Executing http node...
<20:09:21 24/06/2020> -- |http -- DEBUG: ... http node was not successfully executed.
<20:09:21 24/06/2020> -- |http -- ERROR: Error while retrieving http payload: TypeError: Cannot read property 'shift' of null
<20:09:21 24/06/2020> -- WARN: [executor] Node (Af7654b68b05558:http) execution failed. Error: httpin.errors.no-body. Aborting flow 4b1cdde4-ad87-49d3-b578-de59f4f73070 branch execution.
```

**Comment by betefaber** [comment]
Fixed in v0.4.3-rc.1.

Although in the node configuration there is an indication of the mandatory field, the flow is saved without the need to fill in the 'Request body' field. (body: '')


![image](https://user-images.githubusercontent.com/37310063/90145709-99792200-dd56-11ea-8047-5f6cd99c4279.png)


```
flowbroker_1                  | <14:13:57 13/08/2020> -- |flowMngr -- DEBUG: Parsing new flow...
flowbroker_1                  | <14:13:57 13/08/2020> -- |flowMngr -- DEBUG: New flow: ParsedFlow {
flowbroker_1                  |   heads: [],
flowbroker_1                  |   devices: [],
flowbroker_1                  |   templates: [],
flowbroker_1                  |   nodes: {},
flowbroker_1                  |   red:
flowbroker_1                  |    [ { id: 'f66d93e3.8f42e', type: 'tab', label: 'Flow 1' },
flowbroker_1                  |      { id: '853a54b9.f53208',
flowbroker_1                  |        type: 'device template in',
flowbroker_1                  |        z: 'f66d93e3.8f42e',
flowbroker_1                  |        name: 'ônibus',
flowbroker_1                  |        device_template: { id: 6 },
flowbroker_1                  |        status: 'false',
flowbroker_1                  |        device_template_id: 6,
flowbroker_1                  |        x: 136.5,
flowbroker_1                  |        y: 144,
flowbroker_1                  |        wires: [ [ 'ce40a438.e567c8' ] ] },
flowbroker_1                  |      { id: '784cd62a.09b088',
flowbroker_1                  |        type: 'http',
flowbroker_1                  |        z: 'f66d93e3.8f42e',
flowbroker_1                  |        name: '',
flowbroker_1                  |        method: 'GET',
flowbroker_1                  |        ret: 'txt',
flowbroker_1                  |        body: '',
flowbroker_1                  |        response: 'responseGet',
flowbroker_1                  |        url: 'http://ptsv2.com/t/3fbhu-1543424220/post',
flowbroker_1                  |        x: 918.5,
flowbroker_1                  |        y: 408,
flowbroker_1                  |        wires: [ [] ] },
flowbroker_1                  |      { id: 'ce40a438.e567c8',
flowbroker_1                  |        type: 'switch',
flowbroker_1                  |        z: 'f66d93e3.8f42e',
flowbroker_1                  |        name: 'velocidade >= 50',
flowbroker_1                  |        property: 'payload.velocidade',
flowbroker_1                  |        propertyType: 'msg',
flowbroker_1                  |        rules: [ { t: 'gte', v: '50', vt: 'num' } ],
flowbroker_1                  |        checkall: 'true',
flowbroker_1                  |        outputs: '1',
flowbroker_1                  |        x: 409.5,
flowbroker_1                  |        y: 210,
flowbroker_1                  |        wires: [ [ '5d51ecfa.baa4e4' ] ] },
flowbroker_1                  |      { id: '5d51ecfa.baa4e4',
flowbroker_1                  |        type: 'template',
flowbroker_1                  |        z: 'f66d93e3.8f42e',
flowbroker_1                  |        name: '',
flowbroker_1                  |        field: 'reqBody',
flowbroker_1                  |        fieldType: 'msg',
flowbroker_1                  |        syntax: 'handlebars',
flowbroker_1                  |        template: '{"payload": "velocidade muito alta: {{payload.velocidade}} km/h!"}',
flowbroker_1                  |        output: 'str',
flowbroker_1                  |        x: 651.5,
flowbroker_1                  |        y: 318,
flowbroker_1                  |        wires: [ [ '784cd62a.09b088' ] ] } ] }
flowbroker_1                  | <14:13:57 13/08/2020> -- |flowMngr -- DEBUG: Ignoring 'tab' node.
flowbroker_1                  | <14:13:57 13/08/2020> -- |flowMngr -- DEBUG: ... flow was successfully parsed.
```

**Comment by betefaber** [comment]
HTTP node execution failed (#1650)

**Comment by ctossato** [comment]
Tested on v0.5.0-alpha4. Http node was not successfully executed. I got the following log:
```
<19:25:52 25/09/2020> -- |http -- DEBUG: Executing http node...
<19:25:52 25/09/2020> -- |http -- DEBUG: ... http node was not successfully executed.
<19:25:52 25/09/2020> -- |http -- ERROR: An exception was thrown: TypeError: Cannot read property 'headers' of undefined
<19:25:52 25/09/2020> -- WARN: [executor] Node (A6705178ca00ef:http) execution failed. Error: TypeError: Cannot read property 'headers' of undefined
    at DataHandler.handleMessageRequest (/opt/flowbroker/orchestrator/src/nodes/http/index.js:155:25)
    at DataHandler.handleMessage (/opt/flowbroker/orchestrator/src/nodes/http/index.js:123:42)
    at Executor.hop (/opt/flowbroker/orchestrator/src/executor.js:57:48)
    at channel.consume (/opt/flowbroker/orchestrator/src/amqp.js:80:18)
    at Channel.BaseChannel.dispatchMessage (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:478:12)
    at Channel.BaseChannel.handleDelivery (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:487:15)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:273:10
    at Channel.content (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:326:9)
    at Channel.C.acceptMessageFrame (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:241:31)
    at Channel.C.accept (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:394:17)
    at Connection.mainAccept [as accept] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:478:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7). Aborting flow ebdad936-0e33-4a9b-9521-93fdc049bead branch execution.
```

**Comment by betefaber** [comment]
Tested in **v0.7.0-rc.1**

![image](https://user-images.githubusercontent.com/37310063/122826935-20bded00-d2ba-11eb-956a-462c2b8c8583.png)


![image](https://user-images.githubusercontent.com/37310063/122826777-ece2c780-d2b9-11eb-93c5-63afaa971d67.png)

```
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: Got a message in topic admin.device-data.
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: There are 1 callbacks registered.
flowbroker_1                  | <20:50:29 21/06/2021> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 66 61 34 63 62 39 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
flowbroker_1                  |   size: 100,
flowbroker_1                  |   key: <Buffer 61 64 6d 69 6e 3a 66 61 34 63 62 39>,
flowbroker_1                  |   topic: 'admin.device-data',
flowbroker_1                  |   offset: 57,
flowbroker_1                  |   partition: 0,
flowbroker_1                  |   timestamp: 1624308629662 } 
flowbroker_1                  | <20:50:29 21/06/2021> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: { 'a0ae3abe-3ecf-4814-ba52-50767862b8d8': [Function] }
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: Mapping device fa4cb9 ===into===> event_queue1
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"deviceid\":\"fa4cb9\",\"tenant\":\"admin\",\"timestamp\":1624308629662},\"attrs\":{\"medida\":1.5}}"}
flowbroker_1                  | <20:50:29 21/06/2021> -- |dev cache -- DEBUG: retriving data related to admin:fa4cb9 from cache
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: [ingestor] got new device event: { metadata: { tenant: 'admin', timestamp: 1624308629662 },
flowbroker_1                  |   event: 'publish',
flowbroker_1                  |   data: { attrs: { medida: 1.5 }, id: 'fa4cb9' } }
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: [executor] will handle node Ae593bc2cb200a:http
flowbroker_1                  | <20:50:29 21/06/2021> -- |http -- DEBUG: Executing http node...
flowbroker_1                  | <20:50:29 21/06/2021> -- |http -- DEBUG: HTTP request about to be sent: Url {
flowbroker_1                  |   protocol: 'http:',
flowbroker_1                  |   slashes: true,
flowbroker_1                  |   auth: null,
flowbroker_1                  |   host: 'ptsv2.com',
flowbroker_1                  |   port: null,
flowbroker_1                  |   hostname: 'ptsv2.com',
flowbroker_1                  |   hash: null,
flowbroker_1                  |   search: null,
flowbroker_1                  |   query: null,
flowbroker_1                  |   pathname: '/t/r4bml-1575294028/post',
flowbroker_1                  |   path: '/t/r4bml-1575294028/post',
flowbroker_1                  |   href: 'http://ptsv2.com/t/r4bml-1575294028/post',
flowbroker_1                  |   method: 'GET',
flowbroker_1                  |   headers: {} }
flowbroker_1                  | <20:50:29 21/06/2021> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <20:50:30 21/06/2021> -- |http -- DEBUG: ... http node was successfully executed.
flowbroker_1                  | <20:50:30 21/06/2021> -- DEBUG: [executor] hop (http) result: [{"payload":{"metadata":{"tenant":"admin","timestamp":1624308629662},"event":"publish","data":{"attrs":{"medida":1.5},"id":"fa4cb9"}},"responseGET":{"statusCode":200,"headers":{"content-type":"text/plain; charset=utf-8","vary":"Accept-Encoding","access-control-allow-origin":"*","x-cloud-trace-context":"21b9525f4a91f84505e058337d8e320d","date":"Mon, 21 Jun 2021 20:50:30 GMT","server":"Google Frontend","content-length":"54","connection":"close"},"responseUrl":"http://ptsv2.com/t/r4bml-1575294028/post","payload":"Thank you for this dump. I hope you have a lovely day!"}}]
flowbroker_1                  | <20:50:30 21/06/2021> -- DEBUG: [executor] will handle node A1b4ddf2b1bdf91:notification
flowbroker_1                  | <20:50:30 21/06/2021> -- |notification -- DEBUG: output is: { msgID: '4ae79b6c-f132-49e5-b34b-ef9685d623cd',
flowbroker_1                  |   timestamp: 1624308630257,
flowbroker_1                  |   message: 'http GET',
flowbroker_1                  |   metaAttrsFilter: 
flowbroker_1                  |    { statusCode: 200,
flowbroker_1                  |      headers: 
flowbroker_1                  |       { 'content-type': 'text/plain; charset=utf-8',
flowbroker_1                  |         vary: 'Accept-Encoding',
flowbroker_1                  |         'access-control-allow-origin': '*',
flowbroker_1                  |         'x-cloud-trace-context': '21b9525f4a91f84505e058337d8e320d',
flowbroker_1                  |         date: 'Mon, 21 Jun 2021 20:50:30 GMT',
flowbroker_1                  |         server: 'Google Frontend',
flowbroker_1                  |         'content-length': '54',
flowbroker_1                  |         connection: 'close' },
flowbroker_1                  |      responseUrl: 'http://ptsv2.com/t/r4bml-1575294028/post',
flowbroker_1                  |      payload: 'Thank you for this dump. I hope you have a lovely day!',
flowbroker_1                  |      shouldPersist: true },
flowbroker_1                  |   subject: 'user_notification' }
flowbroker_1                  | <20:50:30 21/06/2021> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device': 
flowbroker_1                  |    { admin: 'admin.dojot.device-manager.device',
flowbroker_1                  |      teste: 'teste.dojot.device-manager.device',
flowbroker_1                  |      test: 'test.dojot.device-manager.device' },
flowbroker_1                  |   'device-data': 
flowbroker_1                  |    { admin: 'admin.device-data',
flowbroker_1                  |      teste: 'teste.device-data',
flowbroker_1                  |      test: 'test.device-data' },
flowbroker_1                  |   'dojot.notifications': 
flowbroker_1                  |    { admin: 'admin.dojot.notifications',
flowbroker_1                  |      teste: 'teste.dojot.notifications',
flowbroker_1                  |      test: 'test.dojot.notifications' },
flowbroker_1                  |   'dojot.ftp': 
flowbroker_1                  |    { admin: 'admin.dojot.ftp',
flowbroker_1                  |      teste: 'teste.dojot.ftp',
flowbroker_1                  |      test: 'test.dojot.ftp' } }
flowbroker_1                  | <20:50:30 21/06/2021> -- |notification -- DEBUG: ...notification node was successfully executed.
flowbroker_1                  | <20:50:30 21/06/2021> -- DEBUG: [executor] hop (notification) result: []
flowbroker_1                  | <20:50:30 21/06/2021> -- DEBUG: Got a message in topic admin.dojot.notifications.
flowbroker_1                  | <20:50:30 21/06/2021> -- DEBUG: There are 1 callbacks registered.
flowbroker_1                  | <20:50:30 21/06/2021> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 73 67 49 44 22 3a 22 34 61 65 37 39 62 36 63 2d 66 31 33 32 2d 34 39 65 35 2d 62 33 34 62 2d 65 66 39 36 38 35 64 36 32 33 63 64 22 2c 22 74 ... >,
flowbroker_1                  |   size: 589,
flowbroker_1                  |   key: null,
flowbroker_1                  |   topic: 'admin.dojot.notifications',
flowbroker_1                  |   offset: 12,
flowbroker_1                  |   partition: 0,
flowbroker_1                  |   timestamp: 1624308630258 } 
flowbroker_1                  | <20:50:30 21/06/2021> -- |messenger -- DEBUG: Emitting new event message for subject dojot.notifications@admin
flowbroker_1                  | <20:50:30 21/06/2021> -- |messenger -- DEBUG: No one is listening to subject dojot.notifications events.
flowbroker_1                  | <20:50:30 21/06/2021> -- |messenger -- DEBUG: Message produced successfully
```
