### ISSUE TITLE
Call failed when accessing the endpoint /image

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1385]
Call failed when accessing the endpoint /fw-image/image, details of template or the list of devices.

- image-manager log

```
10.244.1.216 - - [03/Mar/2020:13:55:53 +0000] "GET /image?label=8 HTTP/1.1" 500 25 "http://10.50.11.237:30001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36"
[2020-03-03 13:55:53,261] ERROR in app: Exception on /image [GET]
Traceback (most recent call last):
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/src/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/ImageManager/ImageManager.py", line 37, in get_all
    return make_response(jsonify(json_images), 200)
  File "/usr/src/venv/lib/python3.6/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/usr/src/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
10.244.1.216 - - [03/Mar/2020:13:55:53 +0000] "GET /image?label=8 HTTP/1.1" 500 25 "http://10.50.11.237:30001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36"
```
- manage firmware of template

![detalhesTemplate](https://user-images.githubusercontent.com/37310063/75786196-ae7f6d00-5d43-11ea-82eb-27206711c429.png)

- device list after viewing device details

![detailsDevice](https://user-images.githubusercontent.com/37310063/75800073-c4972880-5d57-11ea-84ae-bd95a19a4e7d.png)

**Note**: In the previous version (v0.4.2_rc1) the problem does not happen
```
10.244.1.15 - - [03/Mar/2020:14:17:56 +0000] "GET /image?label=8 HTTP/1.1" 200 3 "http://10.50.11.237:30001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36"
10.244.1.15 - - [03/Mar/2020:14:17:56 +0000] "GET /image?label=8 HTTP/1.1" 200 3 "http://10.50.11.237:30001/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36"
```
![detalhesTemplate_rc1](https://user-images.githubusercontent.com/37310063/75786214-b5a67b00-5d43-11ea-96b6-fb41406b584c.png)

![listadevices_rc1](https://user-images.githubusercontent.com/37310063/75786229-bc34f280-5d43-11ea-9421-ab45f425412b.png)

**Affected version**: v0.4.2

**Environments**: docker and kubernetes

**Comment by betefaber** [comment]
Test OK. Tested in version **v0.4.2**

- list firmware version
```
GET {{HOST}}:{{PORT}}/fw-image/image?label=4
[
  {
    "confirmed": true,
    "created": "2020-03-09T14:03:14.266806+00:00",
    "fw_version": "FW 1.0",
    "id": "406f48e2-2a4e-46a7-871c-8c01945cc247",
    "label": "4",
    "updated": "2020-03-09T14:03:14.396521+00:00"
  }
]
```
- list image
```
GET {{HOST}}:{{PORT}}/fw-image/image/0a27651a-a727-4eef-9aea-9bb517fb7f91
{
  "confirmed": true,
  "created": "2020-03-09T14:03:14.266806+00:00",
  "fw_version": "FW 1.0",
  "id": "406f48e2-2a4e-46a7-871c-8c01945cc247",
  "label": "4",
  "updated": "2020-03-09T14:03:14.396521+00:00"
}
```
- list binary
```
GET {{HOST}}:{{PORT}}/fw-image/image/406f48e2-2a4e-46a7-871c-8c01945cc247/binary
46 65 61 74 75 72 65 3a 20 41 64 69 63 69 6f 6e 61 72 20 54 65 6d 70 6c 61 74 65 20 63 6f 6d 20 61 74 72 69 62 75 74 6f 20 73 69 6d 70 6c 65 73 20 47 69 76 65 6e 20 71 75 65 20 6f 20 75 73 75 c3 a1 72 69 6f 20 71 75 65 72 20 61 64 69 63 69 6f 6e 61 72 20 75 6d 20 74 65 6d 70 6c 61 74 65 20 63 6f 6d 20 75 6d 20 61 74 72 69 62 75 74 6f 20 73 69 6d 70 6c 65 73 20 57 68 65 6e 20 6f 20 75 73 75 c3 a1 72 69 6f 20 61 64 69 63 69 6f 6e 61 20 75 6d 20 74 65 6d 70 6c 61 74 65 20 63 6f 6d 20 75 6d 20 61 74 72 69 62 75 74 6f 20 73 69 6d 70 6c 65 73 20 54 68 65 6e 20 6f 20 74 65 6d 70 6c 61 74 65 20 c3 a9 20 63 72 69 61 64 6f 20 63 6f 6d 20 73 75 63 65 73 73 6f 
```
- delete image
```
 DELETE {{HOST}}:{{PORT}}/fw-image/image/406f48e2-2a4e-46a7-871c-8c01945cc247
{
  "removed_image": {
    "confirmed": true,
    "created": "2020-03-09T14:03:14.266806+00:00",
    "fw_version": "FW 1.0",
    "id": "406f48e2-2a4e-46a7-871c-8c01945cc247",
    "label": "4",
    "updated": "2020-03-09T14:03:14.396521+00:00"
  },
  "result": "ok"
}
```
- create firmware version
```
POST {{HOST}}:{{PORT}}/fw-image/image/
{"label": "4", "fw_version": "fw 4.0"}
{
  "id": "1010bf8b-26ed-4f72-b4c9-3cde5717e862",
  "label": "4",
  "published_at": "Mon, 09 Mar 2020 14:22:29 GMT",
  "url": "/image/1010bf8b-26ed-4f72-b4c9-3cde5717e862"
}
```
 - create image
```
POST {{HOST}}:{{PORT}}/fw-image/image/1010bf8b-26ed-4f72-b4c9-3cde5717e862/binary
{
  "image": "1010bf8b-26ed-4f72-b4c9-3cde5717e862",
  "message": "image uploaded"
}
```
