### ISSUE TITLE
Persister crashes if log level setting is incorrect

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1504]
Persister crashes if log level setting is incorrect.
WARN and ERROR log levels are not considered.

- LOG_LEVEL = DEBUG:
```
$ kubectl -n dojot logs -f --tail 1000 persister-67d8888566-lwr68
[2020-06-22 17:39:34 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 17:39:34 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 17:39:34 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 17:39:34 +0000] [13] [INFO] Booting worker with pid: 13
[22/06/20 - 17:39:35] |persister| DEBUG: Initializing persister...
[22/06/20 - 17:39:35] |persister| INFO: db initialized
[22/06/20 - 17:39:35] |persister| DEBUG: Creating indexes for tenants: ['admin', 'teste']
[22/06/20 - 17:39:35] |persister| DEBUG: ... persister was successfully initialized.
[22/06/20 - 17:39:35] |persister| DEBUG: Initializing dojot messenger...
[22/06/20 - 17:39:36] |persister| DEBUG: ... dojot messenger was successfully initialized.
```

- LOG_LEVEL = debug

```
~$ kubectl -n dojot logs -f --tail 1000 persister-5f78c7b566-r86pr
[2020-06-22 17:42:31 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 17:42:31 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 17:42:31 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 17:42:31 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'debug'
```

![image](https://user-images.githubusercontent.com/37310063/85320653-c5d09a80-b499-11ea-8503-928c1322ec74.png)

----

- LOG_LEVEL = INFO
```
$ kubectl -n dojot logs -f --tail 1000 persister-68b6c6c5d9-qxn22
[2020-06-22 18:09:08 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 18:09:08 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 18:09:08 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 18:09:09 +0000] [13] [INFO] Booting worker with pid: 13
[22/06/20 - 18:09:09] |persister| INFO: db initialized

```
- LOG_LEVEL = info
```
$ kubectl -n dojot logs -f --tail 1000 persister-797988d8b9-bz9nz
[2020-06-22 18:11:20 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 18:11:20 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 18:11:20 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 18:11:20 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'info'

```
![image](https://user-images.githubusercontent.com/37310063/85321279-d0d7fa80-b49a-11ea-99a8-17bf3798ee30.png)

----

- LOG_LEVEL = WARN (this level is ignored)
```
$ kubectl -n dojot logs -f --tail 1000 persister-558dbdbddf-pkt8n
[2020-06-22 18:13:15 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 18:13:15 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 18:13:15 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 18:13:15 +0000] [13] [INFO] Booting worker with pid: 13

```
- LOG_LEVEL = warn
```
$ kubectl -n dojot logs -f --tail 1000 persister-6d7db66ddf-lkhq7
[2020-06-22 18:15:38 +0000] [8] [INFO] Starting gunicorn 19.6.0
[2020-06-22 18:15:38 +0000] [8] [INFO] Listening at: http://0.0.0.0:8057 (8)
[2020-06-22 18:15:38 +0000] [8] [INFO] Using worker: gevent
[2020-06-22 18:15:38 +0000] [14] [INFO] Booting worker with pid: 14
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'warn'

```
![image](https://user-images.githubusercontent.com/37310063/85321650-65425d00-b49b-11ea-98c7-e09041eff506.png)

----

- LOG_LEVEL = ERROR (this level is ignored)
```
$ kubectl -n dojot logs -f --tail 1000 persister-79d59c7579-jt9rp
[2020-06-22 18:17:56 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 18:17:56 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 18:17:56 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 18:17:56 +0000] [13] [INFO] Booting worker with pid: 13

```
- LOG_LEVEL= error
```
~$ kubectl -n dojot logs -f --tail 1000 persister-567dd46795-qcqcg
[2020-06-22 18:21:46 +0000] [7] [INFO] Starting gunicorn 19.6.0
[2020-06-22 18:21:46 +0000] [7] [INFO] Listening at: http://0.0.0.0:8057 (7)
[2020-06-22 18:21:46 +0000] [7] [INFO] Using worker: gevent
[2020-06-22 18:21:46 +0000] [13] [INFO] Booting worker with pid: 13
Traceback (most recent call last):
  File "history/subscriber/persister.py", line 11, in <module>
    LOGGER = Logger.Log(conf.log_level).color_log()
  File "/usr/src/app/history/Logger.py", line 24, in __init__
    self.log.setLevel(log_level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1284, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'error'

```
![image](https://user-images.githubusercontent.com/37310063/85322207-527c5800-b49c-11ea-95ef-b9fa53cd73b6.png)

Affected version: v0.5.0-alpha.1

**Comment by thiagodpf** [comment]
PRs with corrections:
https://github.com/dojot/history/pull/86
https://github.com/dojot/history/pull/87
