### ISSUE TITLE
[ejbca] Authentication failed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1776]
- ejbca initialization failure.

```
ejbca_1                       | 21:33:14,402 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018559: Deployed "ejbca.ear"
ejbca_1                       | 21:33:37,092 INFO  [org.ejbca.core.ejb.authentication.web.WebAuthenticationProviderSessionBean] (http--0.0.0.0-8443-1) The certificate is revoked or cannot be located in the database. SubjectDN 'CN=SuperAdmin'.
ejbca_1                       | 21:33:37,094 INFO  [org.cesecore.audit.impl.log4j.Log4jDevice] (http--0.0.0.0-8443-1) 2020-10-16 21:33:37+00:00;AUTHENTICATION;FAILURE;ADMINWEB;EJBCA;none;;;;msg=The certificate is revoked or cannot be located in the database. SubjectDN 'CN=SuperAdmin'.
ejbca_1                       | 21:33:37,119 ERROR [org.jboss.as.webservices.invocation.InvocationHandlerEJB3] (http--0.0.0.0-8443-1) Method invocation failed with exception: Authentication failed. Further information: No admin authenticated for certificate with serialNumber 4450252206896951397 and issuerDN 'CN=IOTmidCA,O=EJBCA IOT,C=SE'.: org.cesecore.authorization.AuthorizationDeniedException: Authentication failed. Further information: No admin authenticated for certificate with serialNumber 4450252206896951397 and issuerDN 'CN=IOTmidCA,O=EJBCA IOT,C=SE'.
ejbca_1                       |         at org.ejbca.core.protocol.ws.EjbcaWSHelper.getAdmin(EjbcaWSHelper.java:194) [ejbca-ws-ejb.jar:]
ejbca_1                       |         at org.ejbca.core.protocol.ws.EjbcaWSHelper.getAdmin(EjbcaWSHelper.java:158) [ejbca-ws-ejb.jar:]
ejbca_1                       |         at org.ejbca.core.protocol.ws.EjbcaWS.getLastCAChain(EjbcaWS.java:2798) [ejbca-ws-ejb.jar:]
ejbca_1                       |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_91]
ejbca_1                       |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_91]
ejbca_1                       |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_91]
ejbca_1                       |         at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_91]
ejbca_1                       |         at org.jboss.as.ee.component.ManagedReferenceMethodInterceptorFactory$ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptorFactory.java:72) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:228) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:304) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:190) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:32) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:165) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.as.webservices.invocation.AbstractInvocationHandlerEJB.invoke(AbstractInvocationHandlerEJB.java:112)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.JBossWSInvoker._invokeInternal(JBossWSInvoker.java:181)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.JBossWSInvoker.invoke(JBossWSInvoker.java:127)
ejbca_1                       |         at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
ejbca_1                       |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_91]
ejbca_1                       |         at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_91]
ejbca_1                       |         at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
ejbca_1                       |         at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:106)
ejbca_1                       |         at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:263)
ejbca_1                       |         at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
ejbca_1                       |         at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:207)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.RequestHandlerImpl.handleHttpRequest(RequestHandlerImpl.java:91)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.transport.ServletHelper.callRequestHandler(ServletHelper.java:169)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.CXFServletExt.invoke(CXFServletExt.java:87)
ejbca_1                       |         at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:185)
ejbca_1                       |         at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:108)
ejbca_1                       |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
ejbca_1                       |         at org.jboss.wsf.stack.cxf.CXFServletExt.service(CXFServletExt.java:135)
ejbca_1                       |         at org.jboss.wsf.spi.deployment.WSFServlet.service(WSFServlet.java:140) [jbossws-spi-2.0.3.GA.jar:2.0.3.GA]
ejbca_1                       |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
ejbca_1                       |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
ejbca_1                       |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
ejbca_1                       |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
ejbca_1                       |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
ejbca_1                       |         at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
ejbca_1                       |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
ejbca_1                       |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
ejbca_1                       |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
ejbca_1                       |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
ejbca_1                       |         at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
ejbca_1                       |         at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
ejbca_1                       |         at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930)
ejbca_1                       |         at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_91]
ejbca_1                       |
ejbca_1                       | 21:33:37,155 WARNING [org.apache.cxf.phase.PhaseInterceptorChain] (http--0.0.0.0-8443-1) Application {http://ws.protocol.core.ejbca.org/}EjbcaWSService#{http://ws.protocol.core.ejbca.org/}getLastCAChain has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: Authentication failed. Further information: No admin authenticated for certificate with serialNumber 4450252206896951397 and issuerDN 'CN=IOTmidCA,O=EJBCA IOT,C=SE'.
ejbca_1                       |         at org.jboss.wsf.stack.cxf.JBossWSInvoker.createFault(JBossWSInvoker.java:246)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.JBossWSInvoker._invokeInternal(JBossWSInvoker.java:207)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.JBossWSInvoker.invoke(JBossWSInvoker.java:127)
ejbca_1                       |         at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
ejbca_1                       |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_91]
ejbca_1                       |         at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_91]
ejbca_1                       |         at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
ejbca_1                       |         at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:106)
ejbca_1                       |         at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:263)
ejbca_1                       |         at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
ejbca_1                       |         at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:207)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.RequestHandlerImpl.handleHttpRequest(RequestHandlerImpl.java:91)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.transport.ServletHelper.callRequestHandler(ServletHelper.java:169)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.CXFServletExt.invoke(CXFServletExt.java:87)
ejbca_1                       |         at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:185)
ejbca_1                       |         at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:108)
ejbca_1                       |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
ejbca_1                       |         at org.jboss.wsf.stack.cxf.CXFServletExt.service(CXFServletExt.java:135)
ejbca_1                       |         at org.jboss.wsf.spi.deployment.WSFServlet.service(WSFServlet.java:140) [jbossws-spi-2.0.3.GA.jar:2.0.3.GA]
ejbca_1                       |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
ejbca_1                       |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
ejbca_1                       |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
ejbca_1                       |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
ejbca_1                       |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
ejbca_1                       |         at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
ejbca_1                       |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
ejbca_1                       |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
ejbca_1                       |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
ejbca_1                       |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
ejbca_1                       |         at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
ejbca_1                       |         at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
ejbca_1                       |         at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930)
ejbca_1                       |         at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_91]
ejbca_1                       | Caused by: org.cesecore.authorization.AuthorizationDeniedException: Authentication failed. Further information: No admin authenticated for certificate with serialNumber 4450252206896951397 and issuerDN 'CN=IOTmidCA,O=EJBCA IOT,C=SE'.
ejbca_1                       |         at org.ejbca.core.protocol.ws.EjbcaWSHelper.getAdmin(EjbcaWSHelper.java:194) [ejbca-ws-ejb.jar:]
ejbca_1                       |         at org.ejbca.core.protocol.ws.EjbcaWSHelper.getAdmin(EjbcaWSHelper.java:158) [ejbca-ws-ejb.jar:]
ejbca_1                       |         at org.ejbca.core.protocol.ws.EjbcaWS.getLastCAChain(EjbcaWS.java:2798) [ejbca-ws-ejb.jar:]
ejbca_1                       |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_91]
ejbca_1                       |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_91]
ejbca_1                       |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_91]
ejbca_1                       |         at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_91]
ejbca_1                       |         at org.jboss.as.ee.component.ManagedReferenceMethodInterceptorFactory$ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptorFactory.java:72) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:228) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:304) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:190) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:32) [jboss-as-ejb3-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.1.Final.jar:1.1.1.Final]
ejbca_1                       |         at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:165) [jboss-as-ee-7.1.1.Final.jar:7.1.1.Final]
ejbca_1                       |         at org.jboss.as.webservices.invocation.AbstractInvocationHandlerEJB.invoke(AbstractInvocationHandlerEJB.java:112)
ejbca_1                       |         at org.jboss.wsf.stack.cxf.JBossWSInvoker._invokeInternal(JBossWSInvoker.java:181)
ejbca_1                       |         ... 31 more
ejbca_1                       |
ejbca_1                       | /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
ejbca_1                       |   InsecureRequestWarning)
ejbca_1                       | /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
ejbca_1                       |   InsecureRequestWarning)
ejbca_1                       | Cant connect to EJBCA server for initial configuration
ejbca_1                       | Chances are the server is not ready yet.
ejbca_1                       | Will retry in 30sec
ejbca_1                       | Error occurred while loading CA cert chain. soap message: Authentication failed. Further information: No admin authenticated for certificate with serialNumber 4450252206896951397 and issuerDN 'CN=IOTmidCA,O=EJBCA IOT,C=SE'.

```
- warning when creating the container:

![ejbca-up](https://user-images.githubusercontent.com/37310063/96311438-d45e3700-0fdf-11eb-9e66-c6a9f90a985d.png)

Affected baseline: **v0.4.4-rc.1**

**Comment by betefaber** [comment]
The test environment has not been correctly configured.
