### ISSUE TITLE
Kafka-ws does not connect with kafka after restarting the computer

### ISSUE THREAD

**Issue by thiagodpf** [dojot/dojot#1825]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

report a bug

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

With a dojot docker-compose stack upright, restart the computer and after the stack goes up again, try to consume something from kafka-ws.

Apparently the kafka-ws service is unable to connect to kafka and does not listen to kafka events.

When restarting the kafka-ws service, without dropping the docker-compose stack, data consumption via kafka-ws returns to normal.

* **What is the expected behavior?**

the reconnection between kafka-ws and kafka is expected to be performed automatically.

* **What is the motivation / use case for changing the behavior?**

The kafka-ws service has problems when the computer is restarted and the docker-compose automatically climbs the dojot stack after the system boots.

* **Please tell us about your environment:**
  
  - Version: 0.5.0-rc1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This is the kafka-ws log after restarting the computer, before the restart the service worked normally:
```
2020-11-03T11:01:40.744Z -- kafka-ws:redis-manager -- info: Creating the RedisManager singleton...
2020-11-03T11:01:40.752Z -- kafka-ws:redis-manager -- info: RedisManager singleton creation complete!
2020-11-03T11:01:41.795Z -- kafka-ws:websocket-tarball -- info: Creating the Websocket Tarball singleton...
2020-11-03T11:01:41.797Z -- microservice-sdk:consumer -- info: Consumer configuration {"kafka":{"group.id":"kafka-ws","metadata.broker.list":"kafka:9092","auto.offset.reset":"largest","enable.auto.commit":false},"in.processing.max.messages":1,"queued.max.messages.bytes":10485760,"subscription.backoff.min.ms":1000,"subscription.backoff.max.ms":60000,"subscription.backoff.delta.ms":1000,"commit.interval.ms":5000}
2020-11-03T11:01:41.797Z -- microservice-sdk:consumer -- info: Kafka features: gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer
2020-11-03T11:01:41.799Z -- kafka-ws:websocket-tarball -- info: Websocket Tarball singleton creation complete!
2020-11-03T11:01:41.852Z -- kafka-ws -- info: Initializing the HTTP server...
2020-11-03T11:01:41.853Z -- kafka-ws:app -- info: Configuring the Express Application...
2020-11-03T11:01:41.859Z -- kafka-ws:app -- info: Express Application successfully configured!
2020-11-03T11:01:41.916Z -- kafka-ws -- info: HTTP server is ready to accept connections!
2020-11-03T11:01:41.916Z -- kafka-ws -- info: { address: '0.0.0.0', family: 'IPv4', port: 8080 }
2020-11-03T11:01:41.919Z -- kafka-ws:websocket-tarball -- info: Initializing the Kafka and Redis Components of the Websocket Tarball...
2020-11-03T11:01:41.919Z -- kafka-ws:kafka-consumer -- info: init: Kafka starting...
2020-11-03T11:02:11.988Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: broker transport failure
2020-11-03T11:02:11.989Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: all broker connections are down
2020-11-03T11:02:11.991Z -- microservice-sdk:consumer -- error: Error on connect: Error: broker transport failure
2020-11-03T11:02:11.992Z -- kafka-ws:kafka-consumer -- error: init: Error starting kafka Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-03T11:02:11.992Z -- kafka-ws:kafka-topics-consumer-callbacks-mgmt -- error: init: Error starting KafkaTopicsCallbacksMgmt Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-03T11:02:11.992Z -- kafka-ws:websocket-tarball -- error: Websocket Tarball init: Caught Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-03T11:02:11.993Z -- kafka-ws -- error: Unhandled Rejection at: Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28.
```

After manually restarting the kafka-ws service via docker, this is the log shown. In this case, the service will function correctly again:
```
2020-11-03T16:47:38.932Z -- kafka-ws:redis-manager -- info: Creating the RedisManager singleton...
2020-11-03T16:47:38.937Z -- kafka-ws:redis-manager -- info: RedisManager singleton creation complete!
2020-11-03T16:47:38.965Z -- kafka-ws:websocket-tarball -- info: Creating the Websocket Tarball singleton...
2020-11-03T16:47:38.967Z -- microservice-sdk:consumer -- info: Consumer configuration {"kafka":{"group.id":"kafka-ws","metadata.broker.list":"kafka:9092","auto.offset.reset":"largest","enable.auto.commit":false},"in.processing.max.messages":1,"queued.max.messages.bytes":10485760,"subscription.backoff.min.ms":1000,"subscription.backoff.max.ms":60000,"subscription.backoff.delta.ms":1000,"commit.interval.ms":5000}
2020-11-03T16:47:38.967Z -- microservice-sdk:consumer -- info: Kafka features: gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer
2020-11-03T16:47:38.967Z -- kafka-ws:websocket-tarball -- info: Websocket Tarball singleton creation complete!
2020-11-03T16:47:38.970Z -- kafka-ws -- info: Initializing the HTTP server...
2020-11-03T16:47:38.971Z -- kafka-ws:app -- info: Configuring the Express Application...
2020-11-03T16:47:38.974Z -- kafka-ws:app -- info: Express Application successfully configured!
2020-11-03T16:47:38.981Z -- kafka-ws -- info: HTTP server is ready to accept connections!
2020-11-03T16:47:38.982Z -- kafka-ws -- info: { address: '0.0.0.0', family: 'IPv4', port: 8080 }
2020-11-03T16:47:38.983Z -- kafka-ws:websocket-tarball -- info: Initializing the Kafka and Redis Components of the Websocket Tarball...
2020-11-03T16:47:38.983Z -- kafka-ws:kafka-consumer -- info: init: Kafka starting...
2020-11-03T16:47:38.988Z -- microservice-sdk:consumer -- info: Consumer is ready
2020-11-03T16:47:38.989Z -- kafka-ws:kafka-consumer -- info: init: ...Kafka started 
2020-11-03T16:47:38.993Z -- kafka-ws:redis-expire-mgmt -- info: Subscribed to __keyevent@1__:expired event channel
2020-11-03T16:47:38.993Z -- kafka-ws:websocket-tarball -- info: Successfully initialized Websocket Tarball Kafka and Redis Components!
```

**Comment by thiagodpf** [comment]
The problem reoccurred the next day, even waiting for about 1 hour after starting the computer, kafka-ws is unable to consume the data that is published in the kafka topics.

Log of the kafka-ws service the next day after starting the computer:
```
2020-11-04T11:23:59.761Z -- kafka-ws:redis-manager -- info: Creating the RedisManager singleton...
2020-11-04T11:23:59.767Z -- kafka-ws:redis-manager -- info: RedisManager singleton creation complete!
2020-11-04T11:24:00.974Z -- kafka-ws:websocket-tarball -- info: Creating the Websocket Tarball singleton...
2020-11-04T11:24:00.976Z -- microservice-sdk:consumer -- info: Consumer configuration {"kafka":{"group.id":"kafka-ws","metadata.broker.list":"kafka:9092","auto.offset.reset":"largest","enable.auto.commit":false},"in.processing.max.messages":1,"queued.max.messages.bytes":10485760,"subscription.backoff.min.ms":1000,"subscription.backoff.max.ms":60000,"subscription.backoff.delta.ms":1000,"commit.interval.ms":5000}
2020-11-04T11:24:00.976Z -- microservice-sdk:consumer -- info: Kafka features: gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer
2020-11-04T11:24:00.976Z -- kafka-ws:websocket-tarball -- info: Websocket Tarball singleton creation complete!
2020-11-04T11:24:01.000Z -- kafka-ws -- info: Initializing the HTTP server...
2020-11-04T11:24:01.001Z -- kafka-ws:app -- info: Configuring the Express Application...
2020-11-04T11:24:01.004Z -- kafka-ws:app -- info: Express Application successfully configured!
2020-11-04T11:24:01.012Z -- kafka-ws -- info: HTTP server is ready to accept connections!
2020-11-04T11:24:01.012Z -- kafka-ws -- info: { address: '0.0.0.0', family: 'IPv4', port: 8080 }
2020-11-04T11:24:01.014Z -- kafka-ws:websocket-tarball -- info: Initializing the Kafka and Redis Components of the Websocket Tarball...
2020-11-04T11:24:01.014Z -- kafka-ws:kafka-consumer -- info: init: Kafka starting...
2020-11-04T11:24:31.159Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: broker transport failure
2020-11-04T11:24:31.160Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: all broker connections are down
2020-11-04T11:24:31.160Z -- microservice-sdk:consumer -- error: Error on connect: Error: broker transport failure
2020-11-04T11:24:31.161Z -- kafka-ws:kafka-consumer -- error: init: Error starting kafka Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-04T11:24:31.161Z -- kafka-ws:kafka-topics-consumer-callbacks-mgmt -- error: init: Error starting KafkaTopicsCallbacksMgmt Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-04T11:24:31.166Z -- kafka-ws:websocket-tarball -- error: Websocket Tarball init: Caught Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-04T11:24:31.167Z -- kafka-ws -- error: Unhandled Rejection at: Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28.
```

**Comment by thiagodpf** [comment]
After removing the handlers of rejected promises, Node.js does not yet defeat the process, so the kafka-ws service stands as a zombie, unable to consume kafka data.

Here is the log without the rejected promise handlers:
```
2020-11-05T13:28:22.730Z -- kafka-ws:redis-manager -- info: Creating the RedisManager singleton...
2020-11-05T13:28:22.739Z -- kafka-ws:redis-manager -- info: RedisManager singleton creation complete!
2020-11-05T13:28:22.813Z -- kafka-ws:websocket-tarball -- info: Creating the Websocket Tarball singleton...
2020-11-05T13:28:22.826Z -- microservice-sdk:consumer -- info: Consumer configuration {"kafka":{"group.id":"kafka-ws","metadata.broker.list":"kafka:9092","auto.offset.reset":"largest","enable.auto.commit":false},"in.processing.max.messages":1,"queued.max.messages.bytes":10485760,"subscription.backoff.min.ms":1000,"subscription.backoff.max.ms":60000,"subscription.backoff.delta.ms":1000,"commit.interval.ms":5000}
2020-11-05T13:28:22.826Z -- microservice-sdk:consumer -- info: Kafka features: gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer
2020-11-05T13:28:22.827Z -- kafka-ws:websocket-tarball -- info: Websocket Tarball singleton creation complete!
2020-11-05T13:28:22.832Z -- kafka-ws -- info: Initializing the HTTP server...
2020-11-05T13:28:22.836Z -- kafka-ws:app -- info: Configuring the Express Application...
2020-11-05T13:28:22.843Z -- kafka-ws:app -- info: Express Application successfully configured!
2020-11-05T13:28:22.862Z -- kafka-ws -- info: HTTP server is ready to accept connections!
2020-11-05T13:28:22.862Z -- kafka-ws -- info: { address: '0.0.0.0', family: 'IPv4', port: 8080 }
2020-11-05T13:28:22.868Z -- kafka-ws:websocket-tarball -- info: Initializing the Kafka and Redis Components of the Websocket Tarball...
2020-11-05T13:28:22.868Z -- kafka-ws:kafka-consumer -- info: init: Kafka starting...
2020-11-05T13:28:52.873Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: broker transport failure
2020-11-05T13:28:52.874Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: all broker connections are down
2020-11-05T13:28:52.875Z -- microservice-sdk:consumer -- error: Error on connect: Error: broker transport failure
2020-11-05T13:28:52.875Z -- kafka-ws:kafka-consumer -- error: init: Error starting kafka Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-05T13:28:52.875Z -- kafka-ws:kafka-topics-consumer-callbacks-mgmt -- error: init: Error starting KafkaTopicsCallbacksMgmt Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
2020-11-05T13:28:52.877Z -- kafka-ws:websocket-tarball -- error: Websocket Tarball init: Caught Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
(node:17) UnhandledPromiseRejectionWarning: Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/kafka-ws/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:340:28
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by thiagodpf** [comment]
PR with the workaround for this problem:
https://github.com/dojot/dojot/pull/1836

**Comment by ctossato** [comment]
tested on version 0.5.0-rc.2. It seems to be OK.
