### ISSUE TITLE
[flowbroker][API] pods created for non-existent remote nodes are not removed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1845]
- adding non-existent remote node:
```
curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image":"dojot/teste","id":"teste"}' 2>/dev/null | jq
parse error: Invalid numeric literal at line 1, column 4
```
```
<12:59:26 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Using kubernetes driver.
<12:59:26 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Selected engine: kubernetes
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Using kubernetes API servera @ https://10.96.0.1:443
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Testing access...
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Retrieving current deployment...
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Sending request to server...
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... request was sent to the server.
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Retrieving current deployment...
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Sending request to server...
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... request was sent to the server.
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... server access is OK.
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Creating service for this deployment...
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Service to be created: { apiVersion: 'v1',
  kind: 'Service',
  metadata:
   { name: 'flownode-adminteste',
     labels: { app: 'flowbroker', name: '' } },
  spec:
   { selector: { name: 'flownode-adminteste' },
     ports: [ { protocol: 'TCP', port: 5555, targetPort: 5555 } ] } }
<12:59:27 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... service for deployment created:  { statusCode: 201,
  body:
   { kind: 'Service',
     apiVersion: 'v1',
     metadata:
      { name: 'flownode-adminteste',
        namespace: 'dojot',
        selfLink: '/api/v1/namespaces/dojot/services/flownode-adminteste',
        uid: 'beea4b26-ae6f-46ae-9076-84465b94393d',
        resourceVersion: '22972211',
        creationTimestamp: '2020-11-16T12:59:27Z',
        labels: { app: 'flowbroker', name: '' } },
     spec:
      { ports: [ { protocol: 'TCP', port: 5555, targetPort: 5555 } ],
        selector: { name: 'flownode-adminteste' },
        clusterIP: '10.96.114.222',
        type: 'ClusterIP',
        sessionAffinity: 'None' },
     status: { loadBalancer: {} } } }
<12:59:27 16/11/2020> -- |dispatcher -- INFO: Dispatcher connected to flownode-adminteste on port 5555
```

`flownode-adminteste-86d67fb95d-hfmzl    0/1     ImagePullBackOff`

----
- adding remote node with empty id:
```
curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image":"dojot/arithmetic-mean-example:3.0.0-alpha2","id":""}' 2>/dev/null | jq
{
  "message": "Failed to add node: The remote node id () differs from its name (arithmetic-mean)."
}
```
```
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Using kubernetes driver.
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Selected engine: kubernetes
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Using kubernetes API servera @ https://10.96.0.1:443
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Testing access...
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Retrieving current deployment...
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Sending request to server...
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... request was sent to the server.
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Retrieving current deployment...
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Sending request to server...
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... request was sent to the server.
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... server access is OK.
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Creating service for this deployment...
<13:11:18 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Service to be created: { apiVersion: 'v1',
  kind: 'Service',
  metadata:
   { name: 'flownode-admin',
     labels: { app: 'flowbroker', name: '' } },
  spec:
   { selector: { name: 'flownode-admin' },
     ports: [ { protocol: 'TCP', port: 5555, targetPort: 5555 } ] } }
<13:11:19 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... service for deployment created:  { statusCode: 201,
  body:
   { kind: 'Service',
     apiVersion: 'v1',
     metadata:
      { name: 'flownode-admin',
        namespace: 'dojot',
        selfLink: '/api/v1/namespaces/dojot/services/flownode-admin',
        uid: '24962fa4-169e-494a-8707-7eea3e368611',
        resourceVersion: '22973930',
        creationTimestamp: '2020-11-16T13:11:18Z',
        labels: { app: 'flowbroker', name: '' } },
     spec:
      { ports: [ { protocol: 'TCP', port: 5555, targetPort: 5555 } ],
        selector: { name: 'flownode-admin' },
        clusterIP: '10.96.250.3',
        type: 'ClusterIP',
        sessionAffinity: 'None' },
     status: { loadBalancer: {} } } }
<13:11:19 16/11/2020> -- |dispatcher -- INFO: Dispatcher connected to flownode-admin on port 5555
<13:11:28 16/11/2020> -- |dispatcher -- DEBUG: Received reply: {"payload":{"payload":{"id":"sample/arithmetic-mean","name":"arithmetic-mean","module":"arithmetic-mean","version":"0.0.0"}},"requestId":"19d232ce-4ee1-49a2-8091-0b91bbae3be4"}
<13:11:28 16/11/2020> -- |dispatcher -- DEBUG: Received reply: {"payload":{"payload":"<script type=\"text/x-red\" data-template-name=\"arithmetic-mean\">\n    <div class=\"form-row\">\n        <label for=\"node-input-name\"><i class=\"fa fa-tag\"></i> Name</label>\n        <input type=\"text\" id=\"node-input-name\">\n    </div>\n    <div class=\"form-row\">\n        <label for=\"node-input-in\"><i class=\"fa fa-edit\"></i> <span>input from</span></label>\n        <input type=\"text\" id=\"node-input-in\" placeholder=\"payload\" style=\"width:250px;\">\n        <input type=\"hidden\" id=\"node-input-inFieldType\">\n    </div>\n    <div class=\"form-row\">\n        <label for=\"node-input-out\"><i class=\"fa fa-edit\"></i> <span>output to</span></label>\n        <input type=\"text\" id=\"node-input-out\" placeholder=\"payload\" style=\"width:250px;\">\n        <input type=\"hidden\" id=\"node-input-outFieldType\">\n    </div>\n</script>\n\n<script type=\"text/x-red\" data-help-name=\"arithmetic-mean\">\n</script>\n\n<script type=\"text/javascript\">\n    RED.nodes.registerType('arithmetic-mean', {\n        category: 'converters',\n        color: \"rgb(231, 231, 174)\",\n        defaults: {\n            name: { value: \"\", required: false },\n            out:  { value: \"payload\", validate: RED.validators.typedInput(\"outFieldType\") },\n            outFieldType: { value: \"msg\" },\n            in: { value: \"payload\", validate: RED.validators.typedInput(\"inFieldType\") },\n            inFieldType: { value: \"msg\" },\n        },\n        inputs: 1,\n        outputs: 1,\n        icon: \"cog.png\",\n        label: function () {\n            return this.name || \"arithmetic mean\";\n        },\n        labelStyle: function () {\n            return this.name ? \"node_label_italic\" : \"\";\n        },\n        oneditprepare: function () {\n            if (!this.outFieldType) {\n                this.outFieldType = 'msg';\n            }\n\n            $(\"#node-input-out\").typedInput({\n                default: 'msg',\n                types: ['msg'],\n                typeField: $(\"#node-input-outFieldType\")\n            });\n\n            if (!this.inFieldType) {\n                this.inFieldType = 'msg';\n            }\n\n            $(\"#node-input-in\").typedInput({\n                default: 'msg',\n                types: ['msg'],\n                typeField: $(\"#node-input-inFieldType\")\n            });\n        },\n        oneditsave: function () { }\n    });\n</script>"},"requestId":"96242d00-6767-44bd-873b-e5e5b9c34eb8"}
<13:11:28 16/11/2020> -- |nodeMngr -- ERROR: Failed to remove remote node
                admin/ (Error: Not found remote node with id .). keep going ..
```
`flownode-admin-6787c55974-kdfqj         1/1     Running`

----
- adding remote node unavailable:
```
curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image":"raulnegreiros/mysql-insert","id":"mysql-insert"}' 2>/dev/null | jq
parse error: Invalid numeric literal at line 1, column 4
```
```
<13:18:42 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Using kubernetes driver.
<13:18:42 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Selected engine: kubernetes
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Using kubernetes API servera @ https://10.96.0.1:443
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Testing access...
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Retrieving current deployment...
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Sending request to server...
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... request was sent to the server.
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Retrieving current deployment...
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Sending request to server...
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... request was sent to the server.
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... server access is OK.
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Creating service for this deployment...
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: Service to be created: { apiVersion: 'v1',
  kind: 'Service',
  metadata:
   { name: 'flownode-adminmysql-insert',
     labels: { app: 'flowbroker', name: '' } },
  spec:
   { selector: { name: 'flownode-adminmysql-insert' },
     ports: [ { protocol: 'TCP', port: 5555, targetPort: 5555 } ] } }
<13:18:43 16/11/2020> -- |kb8sRemoveNode -- DEBUG: ... service for deployment created:  { statusCode: 201,
  body:
   { kind: 'Service',
     apiVersion: 'v1',
     metadata:
      { name: 'flownode-adminmysql-insert',
        namespace: 'dojot',
        selfLink: '/api/v1/namespaces/dojot/services/flownode-adminmysql-insert',
        uid: '08d16a0c-bc9e-456b-8a7d-c8f13574a38e',
        resourceVersion: '22974973',
        creationTimestamp: '2020-11-16T13:18:43Z',
        labels: { app: 'flowbroker', name: '' } },
     spec:
      { ports: [ { protocol: 'TCP', port: 5555, targetPort: 5555 } ],
        selector: { name: 'flownode-adminmysql-insert' },
        clusterIP: '10.96.3.94',
        type: 'ClusterIP',
        sessionAffinity: 'None' },
     status: { loadBalancer: {} } } }
<13:18:43 16/11/2020> -- |dispatcher -- INFO: Dispatcher connected to flownode-adminmysql-insert on port 5555
```
`flownode-adminmysql-insert-57cc4785b5-wsfph   1/1     Running`

![Screenshot_21](https://user-images.githubusercontent.com/37310063/99259987-92e8c380-27f9-11eb-8f07-f11dbd2cc05f.png)

- removing remote node "teste"
```
 curl -X DELETE ${DOJOT_HOST}/flows/v1/node/teste -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" 2>/dev/null | jq
{
  "message": "Failed to remove node.",
  "error": "Not found remote node with id teste."
}
```
```
<13:25:54 16/11/2020> -- |api -- ERROR: Error: Not found remote node with id teste.
    at Promise (/opt/flowbroker/orchestrator/src/nodeManager.js:353:25)
    at new Promise (<anonymous>)
    at NodeManager.delRemoteNode (/opt/flowbroker/orchestrator/src/nodeManager.js:322:12)
    at app.delete (/opt/flowbroker/orchestrator/src/api.js:78:15)
    at Layer.handle [as handle_request] (/opt/flowbroker/orchestrator/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/flowbroker/orchestrator/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/flowbroker/orchestrator/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/flowbroker/orchestrator/node_modules/express/lib/router/layer.js:95:5)
    at /opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:281:22
    at param (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/opt/flowbroker/orchestrator/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/opt/flowbroker/orchestrator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:317:13)
```

-removing remote node "mysql-insert"
```
 curl -X DELETE ${DOJOT_HOST}/flows/v1/node/mysql-insert -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" 2>/dev/null | jq
{
  "message": "Failed to remove node.",
  "error": "Not found remote node with id mysql-insert."
}
```
```
<13:28:15 16/11/2020> -- |api -- ERROR: Error: Not found remote node with id mysql-insert.
    at Promise (/opt/flowbroker/orchestrator/src/nodeManager.js:353:25)
    at new Promise (<anonymous>)
    at NodeManager.delRemoteNode (/opt/flowbroker/orchestrator/src/nodeManager.js:322:12)
    at app.delete (/opt/flowbroker/orchestrator/src/api.js:78:15)
    at Layer.handle [as handle_request] (/opt/flowbroker/orchestrator/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/flowbroker/orchestrator/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/flowbroker/orchestrator/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/flowbroker/orchestrator/node_modules/express/lib/router/layer.js:95:5)
    at /opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:281:22
    at param (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/opt/flowbroker/orchestrator/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/opt/flowbroker/orchestrator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/flowbroker/orchestrator/node_modules/express/lib/router/index.js:317:13)
```
- removing all remote nodes
```
 curl -X DELETE ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" 2>/dev/null | jq
{
  "message": "ok"
}
```
Despite the success message, pods are not removed

![Screenshot_22](https://user-images.githubusercontent.com/37310063/99260007-9da35880-27f9-11eb-90ac-721f57a530dd.png)

**Comment by betefaber** [comment]
Test performed in the **docker environment**:

- adding non-existent remote node
```
curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image":"dojot/teste","id":"teste"}' 2>/dev/null | jq
{
  "message": "Failed to add node: Failed to create docker container."
}
```
```
flowbroker_1                  | <18:31:25 17/11/2020> -- |nodeMngr -- ERROR: Failed to create docker container for
flowbroker_1                  |           remote node admin/teste ({"error":null,"response":{"statusCode":404,"body":{"message":"pull access denied for dojot/teste, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"},"headers":{"api-version":"1.40","content-type":"application/json","docker-experimental":"false","ostype":"linux","server":"Docker/19.03.5 (linux)","date":"Tue, 17 Nov 2020 18:31:25 GMT","content-length":"158","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"/var/run/docker.sock","port":null,"hostname":"/var/run/docker.sock","hash":null,"search":"?fromImage=dojot%2Fteste","query":"fromImage=dojot%2Fteste","pathname":"/v1.32/images/create?fromImage=dojot%2Fteste","path":"/v1.32/images/create?fromImage=dojot%2Fteste","href":"http://unix/var/run/docker.sock:/v1.32/images/create?fromImage=dojot%2Fteste","isUnix":true},"method":"POST","headers":{"X-Registry-Auth":"{}","host":"http","accept":"application/json","content-length":0}}},"body":{"message":"pull access denied for dojot/teste, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}}).
```
----
- adding remote node with empty id:
```
curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image":"dojot/arithmetic-mean-example:3.0.0-alpha2","id":""}' 2>/dev/null | jq
{
  "message": "Failed to add node: The remote node id () differs from its name (arithmetic-mean)."
}
```
```
flowbroker_1                  | [harbor-master][modem] error parsing body as json
flowbroker_1                  | <18:43:42 17/11/2020> -- |dockerRemoteNode -- DEBUG: [nodes] image dojot/arithmetic-mean-example:3.0.0-alpha2 created
flowbroker_1                  | <18:43:43 17/11/2020> -- |dockerRemoteNode -- DEBUG: [nodes] container flowbroker.admin.04d647c was created
flowbroker_1                  | <18:43:44 17/11/2020> -- |dockerRemoteNode -- DEBUG: Target: 3e572899470f
flowbroker_1                  | <18:43:46 17/11/2020> -- |dockerRemoteNode -- DEBUG: [nodes] container up: flowbroker.admin.04d647c:3e572899470ffc75b983aa424ac4f2b6bed2666179c0aa574ff041f64537e469
flowbroker_1                  | <18:43:46 17/11/2020> -- |dispatcher -- INFO: Dispatcher connected to 3e572899470f on port 5555
flowbroker_1                  | <18:43:50 17/11/2020> -- |dispatcher -- DEBUG: Received reply: {"payload":{"payload":{"id":"sample/arithmetic-mean","name":"arithmetic-mean","module":"arithmetic-mean","version":"0.0.0"}},"requestId":"df16d44e-4698-4ae9-beb7-5e56e672f8fb"}
flowbroker_1                  | <18:43:50 17/11/2020> -- |dispatcher -- DEBUG: Received reply: {"payload":{"payload":"<script type=\"text/x-red\" data-template-name=\"arithmetic-mean\">\n    <div class=\"form-row\">\n        <label for=\"node-input-name\"><i class=\"fa fa-tag\"></i> Name</label>\n        <input type=\"text\" id=\"node-input-name\">\n    </div>\n    <div class=\"form-row\">\n        <label for=\"node-input-in\"><i class=\"fa fa-edit\"></i> <span>input from</span></label>\n        <input type=\"text\" id=\"node-input-in\" placeholder=\"payload\" style=\"width:250px;\">\n        <input type=\"hidden\" id=\"node-input-inFieldType\">\n    </div>\n    <div class=\"form-row\">\n        <label for=\"node-input-out\"><i class=\"fa fa-edit\"></i> <span>output to</span></label>\n        <input type=\"text\" id=\"node-input-out\" placeholder=\"payload\" style=\"width:250px;\">\n        <input type=\"hidden\" id=\"node-input-outFieldType\">\n    </div>\n</script>\n\n<script type=\"text/x-red\" data-help-name=\"arithmetic-mean\">\n</script>\n\n<script type=\"text/javascript\">\n    RED.nodes.registerType('arithmetic-mean', {\n        category: 'converters',\n        color: \"rgb(231, 231, 174)\",\n        defaults: {\n            name: { value: \"\", required: false },\n            out:  { value: \"payload\", validate: RED.validators.typedInput(\"outFieldType\") },\n            outFieldType: { value: \"msg\" },\n            in: { value: \"payload\", validate: RED.validators.typedInput(\"inFieldType\") },\n            inFieldType: { value: \"msg\" },\n        },\n        inputs: 1,\n        outputs: 1,\n        icon: \"cog.png\",\n        label: function () {\n            return this.name || \"arithmetic mean\";\n        },\n        labelStyle: function () {\n            return this.name ? \"node_label_italic\" : \"\";\n        },\n        oneditprepare: function () {\n            if (!this.outFieldType) {\n                this.outFieldType = 'msg';\n            }\n\n            $(\"#node-input-out\").typedInput({\n                default: 'msg',\n                types: ['msg'],\n                typeField: $(\"#node-input-outFieldType\")\n            });\n\n            if (!this.inFieldType) {\n                this.inFieldType = 'msg';\n            }\n\n            $(\"#node-input-in\").typedInput({\n                default: 'msg',\n                types: ['msg'],\n                typeField: $(\"#node-input-inFieldType\")\n            });\n        },\n        oneditsave: function () { }\n    });\n</script>"},"requestId":"2dfc331c-a09f-4691-a652-1a7d0579ff5b"}
flowbroker_1                  | <18:43:50 17/11/2020> -- |nodeMngr -- ERROR: Failed to remove remote node
flowbroker_1                  |                 admin/ (Error: Not found remote node with id .). keep going ..
```
**The pod with the empty id is created:**

`3e572899470f        dojot/arithmetic-mean-example:3.0.0-alpha2     "node src/index.js"      3 minutes ago       Up 3 minutes        flowbroker.admin.04d647c`

----
- adding remote node unavailable:
```
 curl -X POST ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" -d '{"image":"raulnegreiros/mysql-insert","id":"mysql-insert"}' 2>/dev/null | jq
{
  "message": "Failed to add node: Failed to create docker container."
}
```
```
flowbroker_1                  | <18:50:22 17/11/2020> -- |nodeMngr -- ERROR: Failed to create docker container for
flowbroker_1                  |           remote node admin/mysql-insert ({"error":null,"response":{"statusCode":500,"body":{"message":"Get https://registry-1.docker.io/v2/raulnegreiros/mysql-insert/tags/list: Get https://auth.docker.io/token?scope=repository%3Araulnegreiros%2Fmysql-insert%3Apull&service=registry.docker.io: net/http: TLS handshake timeout"},"headers":{"api-version":"1.40","content-type":"application/json","docker-experimental":"false","ostype":"linux","server":"Docker/19.03.5 (linux)","date":"Tue, 17 Nov 2020 18:50:22 GMT","content-length":"236","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"/var/run/docker.sock","port":null,"hostname":"/var/run/docker.sock","hash":null,"search":"?fromImage=raulnegreiros%2Fmysql-insert","query":"fromImage=raulnegreiros%2Fmysql-insert","pathname":"/v1.32/images/create?fromImage=raulnegreiros%2Fmysql-insert","path":"/v1.32/images/create?fromImage=raulnegreiros%2Fmysql-insert","href":"http://unix/var/run/docker.sock:/v1.32/images/create?fromImage=raulnegreiros%2Fmysql-insert","isUnix":true},"method":"POST","headers":{"X-Registry-Auth":"{}","host":"http","accept":"application/json","content-length":0}}},"body":{"message":"Get https://registry-1.docker.io/v2/raulnegreiros/mysql-insert/tags/list: Get https://auth.docker.io/token?scope=repository%3Araulnegreiros%2Fmysql-insert%3Apull&service=registry.docker.io: net/http: TLS handshake timeout"}}).
```
----
- removing all remote nodes
```
curl -X DELETE ${DOJOT_HOST}/flows/v1/node -H "Authorization: Bearer ${JWT}" -H "content-type: application/json" 2>/dev/null | jq
{
  "message": "ok"
}
```
```
flowbroker_1                  | <18:59:50 17/11/2020> -- |nodeMngr -- DEBUG: Trying to remove docker container undefined
flowbroker_1                  | <18:59:53 17/11/2020> -- |nodeMngr -- DEBUG: Succeeded to remove container.
flowbroker_1                  | <18:59:53 17/11/2020> -- |nodeMngr -- DEBUG: Succeeded to delete remote node with id kelvin for tenant admin.
```

**The pod with the empty id is not removed:**

`3e572899470f        dojot/arithmetic-mean-example:3.0.0-alpha2     "node src/index.js"      17 minutes ago      Up 16 minutes                    flowbroker.admin.04d647c`

**Comment by bizetti** [comment]
Patch after 0.5.0 released.

**Comment by betefaber** [comment]
**Consequence of creating a non-existent image deployment**:

- GUI access failure

![image](https://user-images.githubusercontent.com/37310063/99807124-c8edb680-2b1d-11eb-8756-d3b3b1d42f48.png)

```
curl -X GET ${DOJOT_HOST}/template -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'
{"msg":"Internal Error"}
```
```
curl -X GET ${DOJOT_HOST}/device -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json'
{"msg":"Internal Error"}
```

- device-manager log:

```
[18/11/20 - 12:45:36] |TemplateHandler| INFO:  Getting template with id 19
[18/11/20 - 12:45:36] |TemplateHandler| INFO:  Getting template with id 20
[18/11/20 - 12:45:37] |BackendHandler| INFO:  Publishing create event to Kafka
[18/11/20 - 12:45:37] |DeviceHandler| INFO:  Creating a new device with id e999e.
[18/11/20 - 12:45:37] |BackendHandler| INFO:  Publishing create event to Kafka
[18/11/20 - 12:45:37] |DeviceHandler| INFO:  Creating a new device with id 57dbd6.
[18/11/20 - 12:45:37] |BackendHandler| INFO:  Publishing create event to Kafka
[18/11/20 - 12:45:37] |DeviceHandler| INFO:  Creating a new device with id 20ee73.
[18/11/20 - 12:45:37] |BackendHandler| INFO:  Publishing create event to Kafka
[18/11/20 - 12:45:37] |DeviceHandler| INFO:  Creating a new device with id 207e5f.
[2020-11-19 19:52:08,534] ERROR in app: Exception on /template [GET]
Traceback (most recent call last):
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/src/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/DeviceManager/TemplateHandler.py", line 429, in flask_get_templates
    result = TemplateHandler.get_templates(params, token)
  File "/usr/src/app/DeviceManager/TemplateHandler.py", line 95, in get_templates
    init_tenant_context(token, db)
  File "/usr/src/app/DeviceManager/TenancyManager.py", line 112, in init_tenant_context
    init_tenant(tenant, db)
  File "/usr/src/app/DeviceManager/TenancyManager.py", line 80, in init_tenant
    tenant_exists = db.session.query(query).scalar()
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2866, in scalar
    ret = self.one()
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2837, in one
    ret = self.one_or_none()
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2807, in one_or_none
    ret = list(self)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
 [SQL: "SELECT EXISTS (SELECT schema_name \nFROM information_schema.schemata \nWHERE schema_name = 'admin') AS anon_1"] (Background on this error at: http://sqlalche.me/e/e3q8)
[2020-11-19 19:52:08,687] ERROR in app: Exception on /device [GET]
Traceback (most recent call last):
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/src/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "devices" does not exist
LINE 3: FROM devices ORDER BY devices.label
             ^

```

![image](https://user-images.githubusercontent.com/37310063/99807785-bf188300-2b1e-11eb-8fd2-67f70cbd2d2a.png)


- after removing this deployment and restarting the device-manager, you can access the GUI
