### ISSUE TITLE
[k2v - health check] Service remains unhealthy

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2027]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

After restarting kafka and iotagent-mqtt, the service is unhealthy.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**_Steps_**:

1. Stop kafka & iotagent-mqtt

```
k2v-bridge_1                  | 2021-03-11T18:45:01.264Z -- microservice-sdk:consumer -- debug: Disconnecting from kafka...
k2v-bridge_1                  | 2021-03-11T18:45:01.264Z -- microservice-sdk:consumer -- debug: Unsubscribing from all topics and disconnecting ...
k2v-bridge_1                  | 2021-03-11T18:45:01.264Z -- microservice-sdk:commit-mngr -- debug: CommitManager finished successfully.. committing processed offsets
k2v-bridge_1                  | 2021-03-11T18:45:01.264Z -- microservice-sdk:commit-mngr -- debug: Submitting a commit to Kafka: [{"partition":0,"offset":3895,"topic":"admin.dojot.device-manager.device"}]
k2v-bridge_1                  | 2021-03-11T18:45:01.264Z -- microservice-sdk:consumer -- debug: Committed processed offsets!
k2v-bridge_1                  | 2021-03-11T18:45:01.264Z -- microservice-sdk:consumer -- debug: Calling resume consumer; isPaused? false...
k2v-bridge_1                  | 2021-03-11T18:45:01.271Z -- microservice-sdk:consumer -- info: Consumer disconnected. { connectionOpened: 1615488194636 }
k2v-bridge_1                  | 2021-03-11T18:45:01.271Z -- microservice-sdk:consumer -- debug: Successfully disconnected producer from Kafka.
k2v-bridge_1                  | 2021-03-11T18:45:01.271Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:45:02.264Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T18:45:07.269Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:45:07.270Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:45:08.270Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T18:45:13.279Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:45:13.279Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:45:14.278Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T18:45:19.284Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:45:19.284Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:45:20.285Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T18:45:25.293Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:45:25.294Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:45:26.294Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T18:45:31.300Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:45:31.301Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:45:32.301Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T18:45:34.811Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:45:34.812Z -- k2v:mqtt-client -- warn: MQTT connection closed
```
2. Start iotagent-mqtt
```
k2v-bridge_1                  | 2021-03-11T18:45:42.960Z -- k2v:agent-messenger -- info: Initializing Kafka Consumer...
k2v-bridge_1                  | 2021-03-11T18:45:42.960Z -- microservice-sdk:consumer -- info: Consumer configuration {"in.processing.max.messages":1,"queued.max.messages.bytes":10485760,"subscription.backoff.min.ms":1000,"subscription.backoff.max.ms":60000,"subscription.backoff.delta.ms":1000,"commit.interval.ms":5000,"kafka.consumer":{"client.id":"k2v-bridge","group.id":"k2v-bridge-group-id","max.in.flight.requests.per.connection":1000000,"metadata.broker.list":"kafka:9092","socket.keepalive.enable":false,"enable.auto.commit":false},"kafka.topic":{"acks":-1,"auto.offset.reset":"beginning"},"disconnect.interval.ms":3000}
k2v-bridge_1                  | 2021-03-11T18:45:42.960Z -- microservice-sdk:consumer -- info: Kafka features: gzip,snappy,sasl,regex,lz4,sasl_gssapi,sasl_plain,plugins
k2v-bridge_1                  | 2021-03-11T18:46:12.964Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: host resolution failure
k2v-bridge_1                  | 2021-03-11T18:46:12.964Z -- microservice-sdk:consumer -- warn: Kafka event.error: Error: all broker connections are down
k2v-bridge_1                  | 2021-03-11T18:46:15.967Z -- microservice-sdk:consumer -- error: Error on connect: Error: broker transport failure
k2v-bridge_1                  | 2021-03-11T18:46:15.967Z -- k2v:agent-messenger -- error: Error while initializing the Kafka Consumer
k2v-bridge_1                  | 2021-03-11T18:46:15.967Z -- k2v:agent-messenger -- error: Error: Local: Broker transport failure
k2v-bridge_1                  |     at Function.createLibrdkafkaError [as create] (/opt/k2v_bridge/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/error.js:411:10)
k2v-bridge_1                  |     at /opt/k2v_bridge/node_modules/@dojot/microservice-sdk/node_modules/node-rdkafka/lib/client.js:350:28
k2v-bridge_1                  | 2021-03-11T18:46:15.968Z -- k2v:agent-messenger -- error: Bailing out!
k2v-bridge_1                  | 2021-03-11T18:46:15.968Z -- k2v:mqtt-client -- info: MQTT connection established
k2v-bridge_1                  | 2021-03-11T18:46:20.973Z -- microservice-sdk:service-state-manager -- warn: Removing 2 services...
k2v-bridge_1                  | 2021-03-11T18:46:20.974Z -- microservice-sdk:service-state-manager -- warn: Removed service "kafka"
k2v-bridge_1                  | 2021-03-11T18:46:20.974Z -- microservice-sdk:service-state-manager -- warn: Removed service "mqtt"
k2v-bridge_1                  | 2021-03-11T18:46:20.975Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
k2v-bridge_1                  | 2021-03-11T18:46:20.975Z -- k2v:agent-messenger -- warn: Shutting down Kafka connection...
k2v-bridge_1                  | 2021-03-11T18:46:20.976Z -- microservice-sdk:consumer -- debug: Disconnecting from kafka...
k2v-bridge_1                  | 2021-03-11T18:46:20.976Z -- microservice-sdk:consumer -- debug: ... not initialized. Aborting operation.
k2v-bridge_1                  | 2021-03-11T18:46:20.977Z -- k2v:mqtt-client -- warn: Closing MQTT connection...
k2v-bridge_1                  | 2021-03-11T18:46:20.980Z -- microservice-sdk:service-state-manager -- debug: Service "kafka" is not registered, will not signalize anything
k2v-bridge_1                  | 2021-03-11T18:46:20.982Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T18:46:20.984Z -- k2v:mqtt-client -- warn: MQTT connection was closed!
k2v-bridge_1                  | 2021-03-11T18:46:20.985Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T18:46:20.988Z -- microservice-sdk:service-state-manager -- debug: Service "kafka" is not registered, will not signalize anything
k2v-bridge_1                  | 2021-03-11T18:46:20.988Z -- microservice-sdk:service-state-manager -- debug: Service "mqtt" is not registered, will not signalize anything
k2v-bridge_1                  | 1 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
k2v-bridge_1                  | 1 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
k2v-bridge_1                  | 1 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
k2v-bridge_1                  | 1 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
```
![Captura de tela de 2021-03-11 18-41-16](https://user-images.githubusercontent.com/37310063/110861677-3ffdb500-829d-11eb-930d-d5b04cf9a22e.png)

3. Start kafka

```
k2v-bridge_1                  | 2 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | 3 - Trying to connect with *kafka* on port *9092*
k2v-bridge_1                  | No Kafka brokers available, exiting ...
dojot_k2v-bridge_1 exited with code 1
k2v-bridge_1                  | "ok"
k2v-bridge_1                  | dojot EJBCA broker at host 'x509-identity-mgmt:3000' fully started.
k2v-bridge_1                  | Generating KeyPar in /opt/k2v_bridge/app/cert/k2v-bridge.key
k2v-bridge_1                  | Generating RSA private key, 2048 bit long modulus (2 primes)
k2v-bridge_1                  | ............+++++
k2v-bridge_1                  | ...........+++++
k2v-bridge_1                  | e is 65537 (0x010001)
k2v-bridge_1                  | Create CSR for k2v-bridge
k2v-bridge_1                  | 
k2v-bridge_1                  | Signing cert : http://x509-identity-mgmt:3000/internal/api/v1/throw-away 
k2v-bridge_1                  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
k2v-bridge_1                  |                                  Dload  Upload   Total   Spent    Left  Speed
100  3005  100  2088  100   917  15938   7000 --:--:-- --:--:-- --:--:-- 22938
k2v-bridge_1                  | Saving CRT /opt/k2v_bridge/app/cert/k2v-bridge.crt
k2v-bridge_1                  | 
k2v-bridge_1                  | Retrieve certificate of trusted CA : http://x509-identity-mgmt:3000/internal/api/v1/throw-away/ca 
k2v-bridge_1                  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
k2v-bridge_1                  |                                  Dload  Upload   Total   Spent    Left  Speed
100  2277  100  2277    0     0  29960      0 --:--:-- --:--:-- --:--:-- 29960
k2v-bridge_1                  | Saving CRT /opt/k2v_bridge/app/cert/ca.crt
k2v-bridge_1                  | 
k2v-bridge_1                  | Retrieve CRL of trusted CA : http://x509-identity-mgmt:3000/internal/api/v1/throw-away/ca/crl 
k2v-bridge_1                  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
k2v-bridge_1                  |                                  Dload  Upload   Total   Spent    Left  Speed
100  1106  100  1106    0     0  14179      0 --:--:-- --:--:-- --:--:-- 14179
k2v-bridge_1                  | /opt/k2v_bridge/app/cert/k2v-bridge.crt: OK
k2v-bridge_1                  | Certificate Chain - Verification OK
k2v-bridge_1                  | Authenticated!
k2v-bridge_1                  | 
k2v-bridge_1                  | > k2v-bridge@1.1.0 app /opt/k2v_bridge
k2v-bridge_1                  | > node index.js
k2v-bridge_1                  | 
k2v-bridge_1                  | 2021-03-11T21:45:48.667Z -- k2v:index -- info: Configuration:
k2v-bridge_1                  | {
k2v-bridge_1                  |   healthcheck: { 'kafka.interval.ms': 30000 },
k2v-bridge_1                  |   log: {
k2v-bridge_1                  |     'console.level': 'debug',
k2v-bridge_1                  |     'file.enable': false,
k2v-bridge_1                  |     'file.filename': 'k2v-%DATE%.log',
k2v-bridge_1                  |     'file.level': 'info',
k2v-bridge_1                  |     verbose: false
k2v-bridge_1                  |   },
k2v-bridge_1                  |   messenger: { 'consumer.topic.suffix': 'dojot.device-manager.device' },
k2v-bridge_1                  |   mqtt: {
k2v-bridge_1                  |     clean: false,
k2v-bridge_1                  |     'client.id': 'k2v-bridge',
k2v-bridge_1                  |     host: 'iotagent-mqtt',
k2v-bridge_1                  |     'keep.alive': 60,
k2v-bridge_1                  |     port: 8883,
k2v-bridge_1                  |     protocol: 'mqtts',
k2v-bridge_1                  |     'reject.unauthorized': true,
k2v-bridge_1                  |     username: 'k2v-bridge',
k2v-bridge_1                  |     ca: '/opt/k2v_bridge/app/cert/ca.crt',
k2v-bridge_1                  |     cert: '/opt/k2v_bridge/app/cert/k2v-bridge.crt',
k2v-bridge_1                  |     key: '/opt/k2v_bridge/app/cert/k2v-bridge.key'
k2v-bridge_1                  |   },
k2v-bridge_1                  |   publish: { qos: 1, 'topic.suffix': '/config' },
k2v-bridge_1                  |   sdk: {
k2v-bridge_1                  |     'in.processing.max.messages': 1,
k2v-bridge_1                  |     'queued.max.messages.bytes': 10485760,
k2v-bridge_1                  |     'subscription.backoff.min.ms': 1000,
k2v-bridge_1                  |     'subscription.backoff.max.ms': 60000,
k2v-bridge_1                  |     'subscription.backoff.delta.ms': 1000,
k2v-bridge_1                  |     'commit.interval.ms': 5000
k2v-bridge_1                  |   },
k2v-bridge_1                  |   consumer: {
k2v-bridge_1                  |     'client.id': 'k2v-bridge',
k2v-bridge_1                  |     'group.id': 'k2v-bridge-group-id',
k2v-bridge_1                  |     'max.in.flight.requests.per.connection': 1000000,
k2v-bridge_1                  |     'metadata.broker.list': 'kafka:9092',
k2v-bridge_1                  |     'socket.keepalive.enable': false
k2v-bridge_1                  |   },
k2v-bridge_1                  |   topic: { acks: -1, 'auto.offset.reset': 'beginning' },
k2v-bridge_1                  |   app: {
k2v-bridge_1                  |     'ejbca.address': 'x509-identity-mgmt:3000',
k2v-bridge_1                  |     hostname: 'k2v-bridge',
k2v-bridge_1                  |     'connection.retry.count': '3',
k2v-bridge_1                  |     'user.config.file': 'docker.conf',
k2v-bridge_1                  |     'connection.retry.timeout': '3',
k2v-bridge_1                  |     basedir: '/opt/k2v_bridge'
k2v-bridge_1                  |   }
k2v-bridge_1                  | }
k2v-bridge_1                  | 2021-03-11T21:45:48.668Z -- microservice-sdk:service-state-manager -- info: Initializing the ServiceStateManager...
k2v-bridge_1                  | 2021-03-11T21:45:48.669Z -- microservice-sdk:service-state-manager -- info: ServiceStateManager configuration: {
k2v-bridge_1                  |   lightship: { detectKubernetes: false, terminate: [Function: terminate] }
k2v-bridge_1                  | }
k2v-bridge_1                  | 2021-03-11T21:45:48.673Z -- microservice-sdk:service-state-manager -- info: ... ServiceStateManager initialized.
k2v-bridge_1                  | 2021-03-11T21:45:48.674Z -- microservice-sdk:service-state-manager -- debug: Service kafka was registered
k2v-bridge_1                  | 2021-03-11T21:45:48.674Z -- microservice-sdk:service-state-manager -- debug: Service mqtt was registered
k2v-bridge_1                  | 2021-03-11T21:45:48.675Z -- microservice-sdk:service-state-manager -- debug: Health checker for service kafka was registered
k2v-bridge_1                  | 2021-03-11T21:45:48.675Z -- k2v:mqtt-client -- info: Connecting MQTT client...
k2v-bridge_1                  | 2021-03-11T21:45:48.705Z -- k2v:mqtt-client -- info: Binding event callbacks...
k2v-bridge_1                  | 2021-03-11T21:45:48.706Z -- k2v:mqtt-client -- info: ... bound event callbacks
k2v-bridge_1                  | 2021-03-11T21:45:48.723Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:48.723Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:49.724Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:49.733Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:49.733Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:50.735Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:50.778Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:50.778Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:51.779Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:51.819Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:51.819Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:52.821Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:52.861Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:52.862Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:53.863Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:53.905Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:53.905Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:54.905Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:54.916Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:54.916Z -- k2v:mqtt-client -- warn: MQTT connection closed
```
![Captura de tela de 2021-03-11 18-49-29](https://user-images.githubusercontent.com/37310063/110861714-4be97700-829d-11eb-9248-e0e00b2d996f.png)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
- when the service status is unhealthy

```
k2v-bridge_1                  | 2021-03-11T21:45:48.673Z -- microservice-sdk:service-state-manager -- info: ... ServiceStateManager initialized.
k2v-bridge_1                  | 2021-03-11T21:45:48.674Z -- microservice-sdk:service-state-manager -- debug: Service kafka was registered
k2v-bridge_1                  | 2021-03-11T21:45:48.674Z -- microservice-sdk:service-state-manager -- debug: Service mqtt was registered
k2v-bridge_1                  | 2021-03-11T21:45:48.675Z -- microservice-sdk:service-state-manager -- debug: Health checker for service kafka was registered
k2v-bridge_1                  | 2021-03-11T21:45:48.675Z -- k2v:mqtt-client -- info: Connecting MQTT client...
k2v-bridge_1                  | 2021-03-11T21:45:48.705Z -- k2v:mqtt-client -- info: Binding event callbacks...
k2v-bridge_1                  | 2021-03-11T21:45:48.706Z -- k2v:mqtt-client -- info: ... bound event callbacks
k2v-bridge_1                  | 2021-03-11T21:45:48.723Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:48.723Z -- k2v:mqtt-client -- warn: MQTT connection closed
k2v-bridge_1                  | 2021-03-11T21:45:49.724Z -- k2v:mqtt-client -- warn: Trying to reconnect to the broker...
k2v-bridge_1                  | 2021-03-11T21:45:49.733Z -- k2v:agent-messenger -- debug: Error while finishing Kafka connection, going on like nothing happened
k2v-bridge_1                  | 2021-03-11T21:45:49.733Z -- k2v:mqtt-client -- warn: MQTT connection closed
```

- when the service status is healthy
```
k2v-bridge_1                  | 2021-03-12T14:28:34.146Z -- microservice-sdk:service-state-manager -- info: ... ServiceStateManager initialized.
k2v-bridge_1                  | 2021-03-12T14:28:34.147Z -- microservice-sdk:service-state-manager -- debug: Service kafka was registered
k2v-bridge_1                  | 2021-03-12T14:28:34.147Z -- microservice-sdk:service-state-manager -- debug: Service mqtt was registered
k2v-bridge_1                  | 2021-03-12T14:28:34.148Z -- microservice-sdk:service-state-manager -- debug: Health checker for service kafka was registered
k2v-bridge_1                  | 2021-03-12T14:28:34.148Z -- k2v:mqtt-client -- info: Connecting MQTT client...
k2v-bridge_1                  | 2021-03-12T14:28:34.182Z -- k2v:mqtt-client -- info: Binding event callbacks...
k2v-bridge_1                  | 2021-03-12T14:28:34.182Z -- k2v:mqtt-client -- info: ... bound event callbacks
k2v-bridge_1                  | 2021-03-12T14:28:34.213Z -- k2v:agent-messenger -- info: Initializing Kafka Consumer...
k2v-bridge_1                  | 2021-03-12T14:28:34.214Z -- microservice-sdk:consumer -- info: Consumer configuration {"in.processing.max.messages":1,"queued.max.messages.bytes":10485760,"subscription.backoff.min.ms":1000,"subscription.backoff.max.ms":60000,"subscription.backoff.delta.ms":1000,"commit.interval.ms":5000,"kafka.consumer":{"client.id":"k2v-bridge","group.id":"k2v-bridge-group-id","max.in.flight.requests.per.connection":1000000,"metadata.broker.list":"kafka:9092","socket.keepalive.enable":false,"enable.auto.commit":false},"kafka.topic":{"acks":-1,"auto.offset.reset":"beginning"},"disconnect.interval.ms":3000}
k2v-bridge_1                  | 2021-03-12T14:28:34.214Z -- microservice-sdk:consumer -- info: Kafka features: gzip,snappy,sasl,regex,lz4,sasl_gssapi,sasl_plain,plugins
k2v-bridge_1                  | 2021-03-12T14:28:34.222Z -- microservice-sdk:consumer -- info: Consumer is ready
k2v-bridge_1                  | 2021-03-12T14:28:34.222Z -- microservice-sdk:commit-mngr -- debug: CommitManager initialized successfully..
k2v-bridge_1                  | 2021-03-12T14:28:34.222Z -- microservice-sdk:consumer -- debug: Refreshing subscriptions
k2v-bridge_1                  | 2021-03-12T14:28:34.223Z -- microservice-sdk:consumer -- debug: subscribing in the following topics (0): []
k2v-bridge_1                  | 2021-03-12T14:28:34.223Z -- microservice-sdk:consumer -- debug: subscribing on topic: /^.+dojot\.device-manager\.device/
k2v-bridge_1                  | 2021-03-12T14:28:34.224Z -- microservice-sdk:consumer -- debug: Refreshing subscriptions
k2v-bridge_1                  | 2021-03-12T14:28:34.224Z -- microservice-sdk:consumer -- debug: subscribing in the following topics (1): [{}]
k2v-bridge_1                  | % ^.+dojot\.device-manager\.device
k2v-bridge_1                  | 2021-03-12T14:28:34.225Z -- k2v:agent-messenger -- info: ... Kafka Consumer was initialized
k2v-bridge_1                  | 2021-03-12T14:28:34.225Z -- k2v:mqtt-client -- info: MQTT connection established
```

**Comment by betefaber** [comment]
The error was not reproduced in version **v0.6.0-rc.2**.
