### ISSUE TITLE
Error in running the tracking simulator

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2054]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

Tracking simulator does not run

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```
$ python3 -m trackingsim.main -H localhost -G localhost -c -n 5 -l bus -x -22.909657 -y -47.062364
2021-03-26 09:23:41,960 - trackingsim - Thread 139725816444736 - INFO - Options: {'host': 'localhost', 'port': 1883, 'gw': 'localhost', 'tenant': 'admin', 'user': 'admin', 'password': 'admin', 'secure': False, 'prefix': 'bus', 'clear': True, 'number_of_devices': 5, 'devices': [], 'latitude': '-22.909657', 'longitude': '-47.062364', 'movement': 'straight-line'}
2021-03-26 09:23:42,241 - trackingsim.devices - Thread 139725816444736 - INFO - Removed devices: ['1e5199', '7ae267', '9cb637', 'e4be11', 'e8522']
2021-03-26 09:23:42,313 - trackingsim.devices - Thread 139725816444736 - INFO - Removed templates: [8]
2021-03-26 09:23:42,820 - trackingsim.devices - Thread 139725816444736 - INFO - Created devices: ['5d6647', '2dbd26', '441f21', '154d28', '158532']
2021-03-26 09:23:42,820 - trackingsim - Thread 139725816444736 - INFO - Starting thread for device 5d6647
2021-03-26 09:23:42,821 - trackingsim - Thread 139725816444736 - INFO - Starting thread for device 2dbd26
2021-03-26 09:23:42,821 - trackingsim - Thread 139725816444736 - INFO - Starting thread for device 441f21
2021-03-26 09:23:42,821 - trackingsim - Thread 139725816444736 - INFO - Starting thread for device 154d28
2021-03-26 09:23:42,821 - trackingsim - Thread 139725816444736 - INFO - Starting thread for device 158532
2021-03-26 09:23:42,823 - trackingsim.sim - Thread 139725542291200 - INFO - Starting simulation for device 5d6647 with sleep time 8.669276117003726
Exception in thread Thread-1:
2021-03-26 09:23:42,823 - trackingsim.sim - Thread 139725584238336 - INFO - Starting simulation for device 2dbd26 with sleep time 6.6148481105792545
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-2:
2021-03-26 09:23:42,823 - trackingsim.sim - Thread 139725726848768 - INFO - Starting simulation for device 441f21 with sleep time 7.625655232229227
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-3:
2021-03-26 09:23:42,824 - trackingsim.sim - Thread 139725735241472 - INFO - Starting simulation for device 154d28 with sleep time 9.427309371394319
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/main.py", line 19, in worker
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    s.run()
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/main.py", line 19, in worker
2021-03-26 09:23:42,824 - trackingsim.sim - Thread 139725752084224 - INFO - Starting simulation for device 158532 with sleep time 6.81580969143669
Exception in thread Thread-4:
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 55, in run
    self.run()
Traceback (most recent call last):
    s.run()
    data['sinr'] = self.__get_next_sinr()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 55, in run
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 117, in __get_next_sinr
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
    displacement_from_origin = distance.vincenty(self.__origin, self.__current_position).kilometers
Exception in thread Thread-5:
    self._target(*self._args, **self._kwargs)
AttributeError: module 'geopy.distance' has no attribute 'vincenty'
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 870, in run
    data['sinr'] = self.__get_next_sinr()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/main.py", line 19, in worker
    self._target(*self._args, **self._kwargs)
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 117, in __get_next_sinr
    s.run()
    self.run()
    displacement_from_origin = distance.vincenty(self.__origin, self.__current_position).kilometers
AttributeError: module 'geopy.distance' has no attribute 'vincenty'
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/main.py", line 19, in worker
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 55, in run
    s.run()
    self._target(*self._args, **self._kwargs)
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 55, in run
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/main.py", line 19, in worker
    data['sinr'] = self.__get_next_sinr()
    s.run()
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 117, in __get_next_sinr
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 55, in run
    data['sinr'] = self.__get_next_sinr()
    displacement_from_origin = distance.vincenty(self.__origin, self.__current_position).kilometers
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 117, in __get_next_sinr
AttributeError: module 'geopy.distance' has no attribute 'vincenty'
    data['sinr'] = self.__get_next_sinr()
    displacement_from_origin = distance.vincenty(self.__origin, self.__current_position).kilometers
  File "/l/disk0/efaber/Releases-Dojot/teste/tracking-simulator/trackingsim/sim.py", line 117, in __get_next_sinr
AttributeError: module 'geopy.distance' has no attribute 'vincenty'
    displacement_from_origin = distance.vincenty(self.__origin, self.__current_position).kilometers
AttributeError: module 'geopy.distance' has no attribute 'vincenty'
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc.2
  - Environment: docker-compose
  - Operating system: Ubuntu 20.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Requirements need to be updated

**Comment by FrancielePessi** [comment]
test performed (docker-compose v0.6.0-rc2)

![Captura de tela de 2021-04-09 17-34-05.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/31c7f569-7687-4b75-9fa0-fca496a1bfe6)

![Captura de tela de 2021-04-09 17-33-53.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/abaef65c-cb29-4531-992b-83b0b98a1e32)
