### ISSUE TITLE
[Kafka-ws] Kafka-ws flaps between Ready and NotReady after redis connection be broken and reestablished

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2094]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

Kafka-ws flaps between Ready and NotReady after redis connection be broken and reestablished. Then, it remains not ready.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

  - 1-Interrupt connection between kafka-ws and kafka-ws-redis
  - 2-try to connect a WS client.
  - 3-wait until kafka-ws becomes not ready
  - 4-reestablish the connection between kafka-ws and kafka-ws-redis
  - 5-wait until kafka-ws becomes ready
  - 6-connect a WS client. (connection is established successfully)
  - 7-see that kafka-ws becomes not ready

Logs and captures: 
[rc3_redis_connection.zip](https://github.com/dojot/dojot/files/6384890/rc3_redis_connection.zip)

* **What is the expected behavior?**
after step 5, kafka-ws shall keep ready.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.6.0-rc3
  - Environment: kubernetes
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mprevide** [comment]
steps to reproduce the problem from @ctossato:


```
docker exec dojot_redis_1 ip link show

eth0@if371: ....

ip a | grep 371

sudo ip link set vethe4d074a down
```

**Comment by mprevide** [comment]
I added a heathchecker that ping/pong the redis, but I noticed that it didn't work properly using the steps above because the service never received any error as an answer, it was stopped.
The solution was to add a timeout in case it was not possible to obtain the pong.
I don't know if it's the best solution.

**Comment by betefaber** [comment]
1. stop kafka-ws-redis
```
kafka-ws_1                    | 2021-05-06T17:31:37.182Z -- kafka-ws:redis-expire-mgmt -- info: sub: onEnd
kafka-ws_1                    | 2021-05-06T17:31:37.182Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":1,"error":null,"total_retry_time":0,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:31:37.183Z -- kafka-ws:redis-expire-mgmt -- info: pub: onEnd
kafka-ws_1                    | 2021-05-06T17:31:37.183Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":1,"error":null,"total_retry_time":0,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:31:37.183Z -- kafka-ws:redis-manager -- info: end
kafka-ws_1                    | 2021-05-06T17:31:37.183Z -- kafka-ws:redis-manager -- debug: Retry strategy options { attempt: 1, error: null, total_retry_time: 0, times_connected: 2 }
kafka-ws_1                    | 2021-05-06T17:31:42.184Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:31:42.184Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:31:42.185Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:31:47.186Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":2,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":5000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:31:47.187Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":2,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":5000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:31:52.189Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:31:52.190Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:31:52.192Z -- kafka-ws:redis-manager -- debug: Retry strategy options {
kafka-ws_1                    |   attempt: 2,
kafka-ws_1                    |   error: Error: Redis connection to kafka-ws-redis:6379 failed - getaddrinfo EAI_AGAIN kafka-ws-redis
kafka-ws_1                    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
kafka-ws_1                    |     errno: 'EAI_AGAIN',
kafka-ws_1                    |     code: 'EAI_AGAIN',
kafka-ws_1                    |     syscall: 'getaddrinfo',
kafka-ws_1                    |     hostname: 'kafka-ws-redis'
kafka-ws_1                    |   },
kafka-ws_1                    |   total_retry_time: 5000,
kafka-ws_1                    |   times_connected: 2
kafka-ws_1                    | }
kafka-ws_1                    | 2021-05-06T17:31:55.473Z -- kafka-ws:redis-manager -- debug: Checking if redis is health...
kafka-ws_1                    | 2021-05-06T17:31:55.490Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-pub is health...
kafka-ws_1                    | 2021-05-06T17:31:55.492Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-sub is health...
kafka-ws_1                    | 2021-05-06T17:31:55.505Z -- kafka-ws:kafka-consumer -- debug: Kafka is health
kafka-ws_1                    | 2021-05-06T17:31:57.193Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:31:57.193Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":3,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":10000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:31:57.194Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":3,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":10000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:32:00.477Z -- kafka-ws:redis-manager -- warn: redis is not health because time exceeded to receive pong.
kafka-ws_1                    | 2021-05-06T17:32:00.478Z -- kafka-ws:redis-manager -- error: There was a problem trying to check if the redis is healthy. e=time exceeded to receive pong {"stack":"Error: time exceeded to receive pong\n    at Timeout._onTimeout (/opt/kafka-ws/app/Redis/Utils.js:25:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
kafka-ws_1                    | 2021-05-06T17:32:00.490Z -- kafka-ws:redis-expire-mgmt -- warn: redis-expire-pub is not health because time exceeded to receive pong.
kafka-ws_1                    | 2021-05-06T17:32:00.491Z -- kafka-ws:redis-expire-mgmt -- error: There was a problem trying to check if the redis-expire-pub is healthy. e=time exceeded to receive pong {"stack":"Error: time exceeded to receive pong\n    at Timeout._onTimeout (/opt/kafka-ws/app/Redis/Utils.js:25:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
kafka-ws_1                    | 2021-05-06T17:32:00.493Z -- kafka-ws:redis-expire-mgmt -- warn: redis-expire-sub is not health because time exceeded to receive pong.
kafka-ws_1                    | 2021-05-06T17:32:00.494Z -- kafka-ws:redis-expire-mgmt -- error: There was a problem trying to check if the redis-expire-sub is healthy. e=time exceeded to receive pong {"stack":"Error: time exceeded to receive pong\n    at Timeout._onTimeout (/opt/kafka-ws/app/Redis/Utils.js:25:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
kafka-ws_1                    | 2021-05-06T17:32:02.196Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:02.197Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:02.201Z -- kafka-ws:redis-manager -- debug: Retry strategy options {
kafka-ws_1                    |   attempt: 3,
kafka-ws_1                    |   error: Error: Redis connection to kafka-ws-redis:6379 failed - getaddrinfo EAI_AGAIN kafka-ws-redis
kafka-ws_1                    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
kafka-ws_1                    |     errno: 'EAI_AGAIN',
kafka-ws_1                    |     code: 'EAI_AGAIN',
kafka-ws_1                    |     syscall: 'getaddrinfo',
kafka-ws_1                    |     hostname: 'kafka-ws-redis'
kafka-ws_1                    |   },
kafka-ws_1                    |   total_retry_time: 10000,
kafka-ws_1                    |   times_connected: 2
kafka-ws_1                    | }
kafka-ws_1                    | 2021-05-06T17:32:07.202Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":4,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":15000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:32:07.202Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":4,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":15000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:32:07.203Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:12.204Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:12.205Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:12.210Z -- kafka-ws:redis-manager -- debug: Retry strategy options {
kafka-ws_1                    |   attempt: 4,
kafka-ws_1                    |   error: Error: Redis connection to kafka-ws-redis:6379 failed - getaddrinfo EAI_AGAIN kafka-ws-redis
kafka-ws_1                    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
kafka-ws_1                    |     errno: 'EAI_AGAIN',
kafka-ws_1                    |     code: 'EAI_AGAIN',
kafka-ws_1                    |     syscall: 'getaddrinfo',
kafka-ws_1                    |     hostname: 'kafka-ws-redis'
kafka-ws_1                    |   },
kafka-ws_1                    |   total_retry_time: 15000,
kafka-ws_1                    |   times_connected: 2
kafka-ws_1                    | }
kafka-ws_1                    | 2021-05-06T17:32:17.210Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":5,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":20000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:32:17.210Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:17.212Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":5,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":20000,"times_connected":2}
kafka-ws_1                    | 2021-05-06T17:32:22.211Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:22.213Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:32:22.218Z -- kafka-ws:redis-manager -- debug: Retry strategy options {
kafka-ws_1                    |   attempt: 5,
kafka-ws_1                    |   error: Error: Redis connection to kafka-ws-redis:6379 failed - getaddrinfo EAI_AGAIN kafka-ws-redis
kafka-ws_1                    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
kafka-ws_1                    |     errno: 'EAI_AGAIN',
kafka-ws_1                    |     code: 'EAI_AGAIN',
kafka-ws_1                    |     syscall: 'getaddrinfo',
kafka-ws_1                    |     hostname: 'kafka-ws-redis'
kafka-ws_1                    |   },
kafka-ws_1                    |   total_retry_time: 20000,
kafka-ws_1                    |   times_connected: 2
kafka-ws_1                    | }

```

2. connecting a WS client.

```
kafka-ws_1                    | 2021-05-06T17:37:37.782Z -- kafka-ws:redis-expire-mgmt -- info: pub: onEnd
kafka-ws_1                    | 2021-05-06T17:37:37.782Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":1,"error":null,"total_retry_time":0,"times_connected":3}
kafka-ws_1                    | 2021-05-06T17:37:37.783Z -- kafka-ws:redis-expire-mgmt -- info: sub: onEnd
kafka-ws_1                    | 2021-05-06T17:37:37.784Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":1,"error":null,"total_retry_time":0,"times_connected":3}
kafka-ws_1                    | 2021-05-06T17:37:37.784Z -- kafka-ws:redis-manager -- info: end
kafka-ws_1                    | 2021-05-06T17:37:37.785Z -- kafka-ws:redis-manager -- debug: Retry strategy options { attempt: 1, error: null, total_retry_time: 0, times_connected: 3 }
kafka-ws_1                    | 2021-05-06T17:37:42.785Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:37:42.786Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:37:42.788Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:37:45.604Z -- kafka-ws:app -- error: The application is not in a ready state, the request cannot be handled
kafka-ws_1                    | 2021-05-06T17:37:45.604Z -- kafka-ws:app -- debug: ServiceUnavailableError: Service Unavailable
kafka-ws_1                    |     at /opt/kafka-ws/app/App.js:40:14
kafka-ws_1                    |     at newFn (/opt/kafka-ws/node_modules/express-async-errors/index.js:16:20)
kafka-ws_1                    |     at Layer.handle [as handle_request] (/opt/kafka-ws/node_modules/express/lib/router/layer.js:95:5)
kafka-ws_1                    |     at trim_prefix (/opt/kafka-ws/node_modules/express/lib/router/index.js:317:13)
kafka-ws_1                    |     at /opt/kafka-ws/node_modules/express/lib/router/index.js:284:7
kafka-ws_1                    |     at Function.process_params (/opt/kafka-ws/node_modules/express/lib/router/index.js:335:12)
kafka-ws_1                    |     at next (/opt/kafka-ws/node_modules/express/lib/router/index.js:275:10)
kafka-ws_1                    |     at expressInit (/opt/kafka-ws/node_modules/express/lib/middleware/init.js:40:5)
kafka-ws_1                    |     at newFn (/opt/kafka-ws/node_modules/express-async-errors/index.js:16:20)
kafka-ws_1                    |     at Layer.handle [as handle_request] (/opt/kafka-ws/node_modules/express/lib/router/layer.js:95:5)
kafka-ws_1                    | 2021-05-06T17:37:47.789Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":2,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":5000,"times_connected":3}
kafka-ws_1                    | 2021-05-06T17:37:47.790Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":2,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":5000,"times_connected":3}


```
3. kafka-ws unhealthy

4.  start kafka-ws-redis
```
kafka-ws_1                    | 2021-05-06T17:38:30.505Z -- kafka-ws:redis-manager -- warn: redis is not health because time exceeded to receive pong.
kafka-ws_1                    | 2021-05-06T17:38:30.505Z -- kafka-ws:redis-manager -- error: There was a problem trying to check if the redis is healthy. e=time exceeded to receive pong {"stack":"Error: time exceeded to receive pong\n    at Timeout._onTimeout (/opt/kafka-ws/app/Redis/Utils.js:25:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
kafka-ws_1                    | 2021-05-06T17:38:30.505Z -- kafka-ws:redis-expire-mgmt -- warn: redis-expire-pub is not health because time exceeded to receive pong.
kafka-ws_1                    | 2021-05-06T17:38:30.506Z -- kafka-ws:redis-expire-mgmt -- error: There was a problem trying to check if the redis-expire-pub is healthy. e=time exceeded to receive pong {"stack":"Error: time exceeded to receive pong\n    at Timeout._onTimeout (/opt/kafka-ws/app/Redis/Utils.js:25:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}
kafka-ws_1                    | 2021-05-06T17:38:30.506Z -- kafka-ws:redis-expire-mgmt -- warn: redis-expire-sub is not health because time exceeded to receive pong.
kafka-ws_1                    | 2021-05-06T17:38:30.506Z -- kafka-ws:redis-expire-mgmt -- error: There was a problem trying to check if the redis-expire-sub is healthy. e=time exceeded to receive pong {"stack":"Error: time exceeded to receive pong\n    at Timeout._onTimeout (/opt/kafka-ws/app/Redis/Utils.js:25:25)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)"}

kafka-ws_1                    | 2021-05-06T17:38:32.816Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:38:32.817Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:38:32.819Z -- kafka-ws:redis-manager -- debug: Retry strategy options {
kafka-ws_1                    |   attempt: 6,
kafka-ws_1                    |   error: Error: Redis connection to kafka-ws-redis:6379 failed - getaddrinfo EAI_AGAIN kafka-ws-redis
kafka-ws_1                    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
kafka-ws_1                    |     errno: 'EAI_AGAIN',
kafka-ws_1                    |     code: 'EAI_AGAIN',
kafka-ws_1                    |     syscall: 'getaddrinfo',
kafka-ws_1                    |     hostname: 'kafka-ws-redis'
kafka-ws_1                    |   },
kafka-ws_1                    |   total_retry_time: 25000,
kafka-ws_1                    |   times_connected: 3
kafka-ws_1                    | }

```
5. kafka-ws healthy

```
kafka-ws_1                    | 2021-05-06T17:40:47.904Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":20,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":95000,"times_connected":3}
kafka-ws_1                    | 2021-05-06T17:40:47.904Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:40:47.905Z -- kafka-ws:redis-expire-mgmt -- debug: Retry strategy options {"attempt":20,"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"kafka-ws-redis"},"total_retry_time":95000,"times_connected":3}
kafka-ws_1                    | 2021-05-06T17:40:52.906Z -- kafka-ws:redis-expire-mgmt -- warn: pub: reconnecting
kafka-ws_1                    | 2021-05-06T17:40:52.907Z -- kafka-ws:redis-expire-mgmt -- warn: sub: reconnecting
kafka-ws_1                    | 2021-05-06T17:40:52.909Z -- kafka-ws:redis-manager -- debug: Retry strategy options {
kafka-ws_1                    |   attempt: 20,
kafka-ws_1                    |   error: Error: Redis connection to kafka-ws-redis:6379 failed - getaddrinfo EAI_AGAIN kafka-ws-redis
kafka-ws_1                    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
kafka-ws_1                    |     errno: 'EAI_AGAIN',
kafka-ws_1                    |     code: 'EAI_AGAIN',
kafka-ws_1                    |     syscall: 'getaddrinfo',
kafka-ws_1                    |     hostname: 'kafka-ws-redis'
kafka-ws_1                    |   },
kafka-ws_1                    |   total_retry_time: 95000,
kafka-ws_1                    |   times_connected: 3
kafka-ws_1                    | }
kafka-ws_1                    | 2021-05-06T17:40:53.926Z -- kafka-ws:redis-expire-mgmt -- info: pub: Connect
kafka-ws_1                    | 2021-05-06T17:40:53.927Z -- kafka-ws:redis-expire-mgmt -- debug: sub: ready.
kafka-ws_1                    | 2021-05-06T17:40:53.927Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.927Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.928Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.928Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.928Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.928Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.928Z -- kafka-ws:redis-expire-mgmt -- info: Subscribed to __keyevent@1__:expired event channel
kafka-ws_1                    | 2021-05-06T17:40:53.928Z -- kafka-ws:redis-expire-mgmt -- info: sub: Connect
kafka-ws_1                    | 2021-05-06T17:40:53.929Z -- kafka-ws:redis-expire-mgmt -- debug: pub: ready.
kafka-ws_1                    | 2021-05-06T17:40:53.929Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.930Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.930Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.930Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.930Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:53.930Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:55.511Z -- kafka-ws:redis-manager -- debug: Checking if redis is health...
kafka-ws_1                    | 2021-05-06T17:40:55.512Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-pub is health...
kafka-ws_1                    | 2021-05-06T17:40:55.513Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-sub is health...
kafka-ws_1                    | 2021-05-06T17:40:55.514Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:40:55.515Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:40:55.516Z -- kafka-ws:kafka-consumer -- debug: Kafka is health
kafka-ws_1                    | 2021-05-06T17:40:57.912Z -- kafka-ws:redis-manager -- warn: reconnecting
kafka-ws_1                    | 2021-05-06T17:40:57.913Z -- kafka-ws:redis-manager -- info: connect
kafka-ws_1                    | 2021-05-06T17:40:57.913Z -- kafka-ws:redis-manager -- debug: ready.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:40:57.914Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:41:25.513Z -- kafka-ws:redis-manager -- debug: Checking if redis is health...
kafka-ws_1                    | 2021-05-06T17:41:25.515Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-pub is health...
kafka-ws_1                    | 2021-05-06T17:41:25.516Z -- kafka-ws:redis-expire-mgmt -- debug: Checking if redis-expire-sub is health...
kafka-ws_1                    | 2021-05-06T17:41:25.517Z -- kafka-ws:redis-manager -- debug: redis is health.
kafka-ws_1                    | 2021-05-06T17:41:25.518Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-pub is health.
kafka-ws_1                    | 2021-05-06T17:41:25.518Z -- kafka-ws:redis-expire-mgmt -- debug: redis-expire-sub is health.
kafka-ws_1                    | 2021-05-06T17:41:25.520Z -- kafka-ws:kafka-consumer -- debug: Kafka is health

```
6. connecting a WS client.

```
kafka-ws_1                    | 2021-05-06T17:44:27.192Z -- kafka-ws:app -- info: 172.18.0.29 - - a7baa377-ec61-42b5-840a-f0d6005dfdde 'GET /kafka-ws/v1/ticket HTTP/1.1' 200 77 - python-requests/2.25.1
kafka-ws_1                    | 
kafka-ws_1                    | 2021-05-06T17:44:27.198Z -- kafka-ws:websocket-tarball -- debug: Received connection from 172.18.0.29:51776
kafka-ws_1                    | 2021-05-06T17:44:27.198Z -- kafka-ws:websocket-tarball -- debug: Setting expiration connection to 1620330267 sec
kafka-ws_1                    | 2021-05-06T17:44:27.198Z -- kafka-ws:redis-expire-mgmt -- debug: addConnection: 6323994a-61d7-4304-b1d4-9e96e95b0356  1620330267
kafka-ws_1                    | 2021-05-06T17:44:27.199Z -- kafka-ws:kafka-topics-consumer-callbacks-mgmt -- debug: addCallbackToTopic: Topic=admin.device-data idCallback=6323994a-61d7-4304-b1d4-9e96e95b0356
kafka-ws_1                    | 2021-05-06T17:44:27.199Z -- kafka-ws:kafka-consumer -- debug: registerCallback: Register Callback for topic admin.device-data
kafka-ws_1                    | 2021-05-06T17:44:27.199Z -- microservice-sdk:consumer -- debug: subscribing on topic: admin.device-data
kafka-ws_1                    | 2021-05-06T17:44:27.199Z -- microservice-sdk:consumer -- debug: Refreshing subscriptions
kafka-ws_1                    | 2021-05-06T17:44:27.199Z -- microservice-sdk:consumer -- debug: subscribing in the following topics (1): ["admin.device-data"]
kafka-ws_1                    | 2021-05-06T17:44:27.200Z -- kafka-ws:kafka-consumer -- debug: registerCallback: All Registered Callbacks admin.device-data,2a218a7b-eaa7-41e0-b93c-b5b5e45ba965
kafka-ws_1                    | 2021-05-06T17:44:27.203Z -- microservice-sdk:consumer -- debug: Current queue utilization:
kafka-ws_1                    |     (97 + 0)/10485760 bytes
kafka-ws_1                    | 2021-05-06T17:44:27.204Z -- microservice-sdk:consumer -- debug: Message on topic: admin.device-data. Calling callback: 2a218a7b-eaa7-41e0-b93c-b5b5e45ba965. Attempt: 1/0
kafka-ws_1                    | 2021-05-06T17:44:27.204Z -- kafka-ws:kafka-topics-consumer-callbacks-mgmt -- debug: createCallbackKafka: Topic=admin.device-data Payload={
kafka-ws_1                    |   metadata: { deviceid: '5fe63f', tenant: 'admin', timestamp: 1620322136400 },
kafka-ws_1                    |   attrs: { int: 883 }
kafka-ws_1                    | }
kafka-ws_1                    | 2021-05-06T17:44:27.206Z -- kafka-ws:websocket-tarball -- debug: Sending {"attrs":{"int":692}}
kafka-ws_1                    | 2021-05-06T17:44:27.206Z -- microservice-sdk:consumer -- debug: Calling resume consumer; isPaused? false...
kafka-ws_1                    | 2021-05-06T17:44:27.206Z -- microservice-sdk:consumer -- debug: Current queue utilization:
kafka-ws_1                    |     (97 + 0)/10485760 bytes
kafka-ws_1                    | 2021-05-06T17:44:27.228Z -- microservice-sdk:consumer -- debug: Message on topic: admin.device-data. Calling callback: 2a218a7b-eaa7-41e0-b93c-b5b5e45ba965. Attempt: 1/0
kafka-ws_1                    | 2021-05-06T17:44:27.229Z -- kafka-ws:kafka-topics-consumer-callbacks-mgmt -- debug: createCallbackKafka: Topic=admin.device-data Payload={
kafka-ws_1                    |   metadata: { deviceid: '5fe63f', tenant: 'admin', timestamp: 1620322156458 },
kafka-ws_1                    |   attrs: { int: 828 }
kafka-ws_1                    | }

```
