### ISSUE TITLE
[flowbroker] Error running cron and cron-batch nodes 

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2294]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Error running cron (event request and http request) and cron-batch nodes 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Steps to reproduce the problem:
1. Create flows with cron and cron-batch nodes
2. Execute the flows 

```
flowbroker_1                  | <16:48:41 14/10/2021> -- |template -- DEBUG: ... template node was successfully executed.
flowbroker_1                  | <16:48:41 14/10/2021> -- DEBUG: [executor] hop (template) result: [{"payload":{"metadata":{"tenant":"admin","timestamp":1634230121119},"event":"publish","data":{"attrs":{"bool":true,"protocol":"mqtt","serial":"indefinido"},"id":"dae72b"}},"reqJOB":[{"time":"*/2 * * * *","timezone":"America/Sao_Paulo","name":"Keep alive","description":"This job sends a keep alive notification to a device every 2 minutes","http":{"method":"PUT","headers":{"Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJlVTFyNjM2bVpNdDF4VFJzeDdNVDNHQld1MFVpRWRkayIsImlhdCI6MTYzNDIzMDA3MCwiZXhwIjoxNjM0MjMwNDkwLCJwcm9maWxlIjoiYWRtaW4iLCJncm91cHMiOlsxXSwidXNlcmlkIjoxLCJqdGkiOiIwOTAzNGQyYjcxMTFiYzRkY2E3NDU1ZWNhOGM2YzBkMSIsInNlcnZpY2UiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.vsTg-EgterCQ-U3NL5mTagmBDeCt7VcZJRnud4OPL3o","Content-Type":"application/json"},"url":"http://device-manager:5000/device/dae72b/actuate","body":{"attrs":{"mensagem":"tô vivo"}}}}]}]
flowbroker_1                  | <16:48:41 14/10/2021> -- DEBUG: [executor] will handle node Ae606f5d2fbbfd8:cron-batch
flowbroker_1                  | <16:48:41 14/10/2021> -- |cron-batch -- DEBUG: Executing cron-batch node...
flowbroker_1                  | <16:48:41 14/10/2021> -- ERROR: Unhandled Rejection at: TypeError: Converting circular structure to JSON
flowbroker_1                  |     at JSON.stringify (<anonymous>)
flowbroker_1                  |     at axios.then.catch.error (/opt/flowbroker/orchestrator/src/nodes/cron-batch/cron-batch.js:87:65)
flowbroker_1                  |     at <anonymous>
flowbroker_1                  |     at process._tickCallback (internal/process/next_tick.js:189:7). Bailing out!!

```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.7.1-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
Steps to reproduce the problem:

- import the database: 
[DojotData-2294.json.txt](https://github.com/dojot/dojot/files/7469937/DojotData-2294.json.txt)

- publish data: 
`mosquitto_pub -h localhost -p 1883 -t admin:e74d07/attrs -u admin:e74d07  -m '{"bool":true}'`

**Comment by betefaber** [comment]
The problem is probably with the _cron service_, because error 500 also happens when using a script to create a cron job 

```
./create-or-update-http-job.sh -d localhost:8000 -u admin -p admin
Getting jwt token ...
... Got jwt token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJFZXlwRnV0ZjVJd0Rsb1lvMWQ5dWZFcXd0ZmpONXNodSIsImlhdCI6MTYzNTk2OTE3MCwiZXhwIjoxNjM1OTY5NTkwLCJwcm9maWxlIjoiYWRtaW4iLCJncm91cHMiOlsxXSwidXNlcmlkIjoxLCJqdGkiOiJlZDdmNWVhOWM0NzViN2ZhNGJkNDM4MjM5MjdhMTk2MyIsInNlcnZpY2UiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.WC0wSWzf14ItAPlcRQ24ALlTpDpILhBGtjzVAd5pwXQ.
Creating template ...
... Created template 4.
Creating device ...
... Created device 451ab8.
Scheduling a cron job (keepalive) ...
... Failed to create cron job.
{"status":"error","errors":"Cannot read property 'collection' of undefined"}
```
```
cron_1                        | 2021-11-03T19:52:50.816Z -- server -- info: - "HTTP/1.1 POST /cron/v1/jobs" "500 76bytes 2ms" "::ffff:172.23.0.35 - curl/7.58.0"
```
----
```
./create-or-update-broker-job.sh -d localhost:8000 -u admin -p admin
Getting jwt token ...
... Got jwt token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJFZXlwRnV0ZjVJd0Rsb1lvMWQ5dWZFcXd0ZmpONXNodSIsImlhdCI6MTYzNTk2OTE4NiwiZXhwIjoxNjM1OTY5NjA2LCJwcm9maWxlIjoiYWRtaW4iLCJncm91cHMiOlsxXSwidXNlcmlkIjoxLCJqdGkiOiI3MjdlNDc1M2NlODNjYmEzYmEzNmU1ZmRiOGE1YjFiNiIsInNlcnZpY2UiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.Kq0v1l1DAnNLkWMEcI5yzQQVCOfOIPV-fOke5G26uSQ.
Creating template ...
... Created template 5.
Creating device ...
... Created device "42aad".
Scheduling a cron job (keepalive) ...
... Failed to create cron job.
{"status":"error","errors":"Cannot read property 'collection' of undefined"}
```
```
cron_1                        | 2021-11-03T19:53:06.120Z -- server -- info: - "HTTP/1.1 POST /cron/v1/jobs" "500 76bytes 3ms" "::ffff:172.23.0.35 - curl/7.58.0"
```

**Comment by betefaber** [comment]
**jobs creation**

- CRON-BATCH node: HTTP
```
flowbroker_1                  | <20:49:01 08/02/2022> -- |cron-batch -- DEBUG: Executing cron-batch node...
flowbroker_1                  | <20:49:01 08/02/2022> -- |cron-batch -- DEBUG: Succeeded to create cron job 24e6ef15-cf87-4084-b426-b8d763ba1fa3
```

- CRON node: HTTP REQUEST
```
flowbroker_1                  | <20:49:01 08/02/2022> -- |cron -- DEBUG: Executing cron node...
flowbroker_1                  | <20:49:01 08/02/2022> -- |cron -- DEBUG: Executing create operation ...
flowbroker_1                  | <20:49:01 08/02/2022> -- |cron -- DEBUG: Succeeded to create cron job 61a5ed1a-c084-4f40-a8a3-53b78e4fb72e
```

- CRON-BATCH node: BROKER
```
flowbroker_1                  | <20:49:07 08/02/2022> -- |cron-batch -- DEBUG: Executing cron-batch node...
flowbroker_1                  | <20:49:07 08/02/2022> -- |cron-batch -- DEBUG: Succeeded to create cron job 4c2025c4-3374-41b8-a4eb-02e8c98e264c
```

- CRON node: EVENT REQUEST:
```
flowbroker_1                  | <20:49:07 08/02/2022> -- |cron -- DEBUG: Executing cron node...
flowbroker_1                  | <20:49:07 08/02/2022> -- |cron -- DEBUG: Executing create operation ...
flowbroker_1                  | <20:49:07 08/02/2022> -- |cron -- DEBUG: Succeeded to create cron job 84acc7d2-c645-4ded-84e7-5319a2a25c26
```

```
curl -X GET localhost:8000/cron/v1/jobs -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq
[
  {
    "jobId": "24e6ef15-cf87-4084-b426-b8d763ba1fa3",
    "spec": {
      "time": "*/2 * * * *",
      "timezone": "America/Sao_Paulo",
      "name": "Keep alive",
      "description": "This job sends a keep alive notification to a device every 2 minutes",
      "http": {
        "method": "PUT",
        "headers": {
          "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciO...2qZq6iHg",
          "Content-Type": "application/json"
        },
        "url": "http://device-manager:5000/device/c1863a/actuate",
        "body": {
          "attrs": {
            "mensagem": "tô vivo"
          }
        }
      }
    }
  },
  {
    "jobId": "61a5ed1a-c084-4f40-a8a3-53b78e4fb72e",
    "spec": {
      "time": "*/3 * * * *",
      "timezone": "UTC",
      "name": "tô vivo 2",
      "description": "Esse job envia notificação de tô vivo 2 a cada 3 minutos",
      "http": {
        "method": "PUT",
        "headers": {
          "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciO...2qZq6iHg",
          "Content-Type": "application/json"
        },
        "url": "http://device-manager:5000/device/c1863a/actuate",
        "body": {
          "attrs": {
            "mensagem": "tô vivo 2"
          }
        }
      }
    }
  },
  {
    "jobId": "4c2025c4-3374-41b8-a4eb-02e8c98e264c",
    "spec": {
      "time": "*/3 * * * *",
      "timezone": "America/Sao_Paulo",
      "name": "Keep alive",
      "description": "This job sends a keep alive notification to a device every 3 minutes",
      "broker": {
        "subject": "dojot.device-manager.device",
        "message": {
          "event": "configure",
          "meta": {
            "service": "admin",
            "timestamp": 1644406920006
          },
          "data": {
            "attrs": {
              "mensagem": "keepalive"
            },
            "id": "75439a"
          }
        }
      }
    }
  },
  {
    "jobId": "84acc7d2-c645-4ded-84e7-5319a2a25c26",
    "spec": {
      "time": "*/2 * * * *",
      "timezone": "UTC",
      "name": "keepalive2",
      "description": "Esse job envia notificação de keepalive2 a cada 2 minutos",
      "broker": {
        "subject": "dojot.device-manager.device",
        "message": {
          "event": "configure",
          "meta": {
            "service": "admin",
            "timestamp": 1644406920001
          },
          "data": {
            "attrs": {
              "mensagem": "keepalive2"
            },
            "id": "75439a"
          }
        }
      }
    }
  }
]
```

**jobs removal**

```
flowbroker_1                  | <11:47:34 09/02/2022> -- |cron-batch -- DEBUG: Executing cron-batch node...
flowbroker_1                  | <11:47:34 09/02/2022> -- |cron-batch -- DEBUG: Succeeded to remove cron job 24e6ef15-cf87-4084-b426-b8d763ba1fa3
```

```
flowbroker_1                  | <11:47:34 09/02/2022> -- |cron -- DEBUG: Executing cron node...
flowbroker_1                  | <11:47:34 09/02/2022> -- |cron -- DEBUG: Executing remove operation ...
flowbroker_1                  | <11:47:34 09/02/2022> -- |cron -- DEBUG: Succeeded to remove cron job 61a5ed1a-c084-4f40-a8a3-53b78e4fb72e
```

```
flowbroker_1                  | <11:48:39 09/02/2022> -- |cron-batch -- DEBUG: Executing cron-batch node...
flowbroker_1                  | <11:48:39 09/02/2022> -- |cron-batch -- DEBUG: Succeeded to remove cron job 4c2025c4-3374-41b8-a4eb-02e8c98e264c
```

```
flowbroker_1                  | <11:48:39 09/02/2022> -- |cron -- DEBUG: Executing cron node...
flowbroker_1                  | <11:48:39 09/02/2022> -- |cron -- DEBUG: Executing remove operation ...
flowbroker_1                  | <11:48:39 09/02/2022> -- |cron -- DEBUG: Succeeded to remove cron job 84acc7d2-c645-4ded-84e7-5319a2a25c26
```
```
curl -X GET localhost:8000/cron/v1/jobs -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq
[]
```
