### ISSUE TITLE
[Iot agent http] Publishing with invalid timestamp

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2319]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
When a message is published using an invalid timestamp it was expected receive a 400 result code.  But it is returned 200 and the published data is marked with a weird timestamp. See the following log.

the invalid timestamp used was `"ts": -1`

```
http-agent_1                  | 2021-10-25T20:22:59.970Z -- http-agent:express -- debug: Incoming request: {"id":"c688538e-3449-49d3-8f7d-0df9ba34dfd3"}
http-agent_1                  | 2021-10-25T20:22:59.971Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-10-25T20:23:00.979Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-10-25T20:23:00.980Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"ce1f4f","tenant":"admin","timestamp":978307200000},"attrs":{"temperature":16,"humidity":60}} to admin/device-data
http-agent_1                  | 2021-10-25T20:23:00.982Z -- http-agent:express -- debug: request has been finished: {"id":"c688538e-3449-49d3-8f7d-0df9ba34dfd3"}
```

* **Please tell us about your environment:**
  
  - Version: 0.7.1-rc.1
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
- single request: **204** result code

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
"ts": -1,
"data": {                                                          
     "float": 30.1                                                 
    }
}'   --cacert ca.crt --cert admin_3dde27.crt --key admin_3dde27.key
```

```
http-agent_1                  | 2021-12-10T20:14:39.299Z -- http-agent:express -- debug: Incoming request: {"id":"0ff59642-85f5-4545-be01-9cfe55f09fd2"}
http-agent_1                  | 2021-12-10T20:14:39.302Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-10T20:14:40.325Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-10T20:14:40.326Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"3dde27","tenant":"admin","timestamp":-1},"attrs":{"float":30.1}} to admin/device-data
http-agent_1                  | 2021-12-10T20:14:40.329Z -- http-agent:express -- debug: request has been finished: {"id":"0ff59642-85f5-4545-be01-9cfe55f09fd2"}
http-agent_1                  | 2021-12-10T20:14:40.330Z -- http-agent:express -- info: 0ff59642-85f5-4545-be01-9cfe55f09fd2 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "204 -bytes 1029ms" "172.27.0.1 - curl/7.58.0"
```

----
- multiple requests: **204** result code
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{        
"ts": -1,
"data": {
     "float": 18.5,
     "int": 1
    }                                                              
},
{"ts": -1,
"data": {
     "float": 20.1,
     "int": 2
    }
},
{"ts": -1,
"data": {
     "float": 49,
     "int": 3
    }
}
]'   --cacert ca.crt --cert admin_3dde27.crt --key admin_3dde27.key
```

```
http-agent_1                  | 2021-12-10T20:32:42.243Z -- http-agent:express -- debug: Incoming request: {"id":"bd97febb-b0eb-4a13-b257-69409fb8776e"}
http-agent_1                  | 2021-12-10T20:32:42.246Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-10T20:32:42.246Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-10T20:32:42.247Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-10T20:32:42.248Z -- http-agent:express -- debug: request has been finished: {"id":"bd97febb-b0eb-4a13-b257-69409fb8776e"}
http-agent_1                  | 2021-12-10T20:32:42.248Z -- http-agent:express -- info: bd97febb-b0eb-4a13-b257-69409fb8776e "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "204 -bytes 4ms" "172.27.0.1 - curl/7.58.0"
http-agent_1                  | 2021-12-10T20:32:43.294Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-10T20:32:43.294Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"3dde27","tenant":"admin","timestamp":-1},"attrs":{"float":18.5,"int":1}} to admin/device-data
http-agent_1                  | 2021-12-10T20:32:43.295Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-10T20:32:43.295Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"3dde27","tenant":"admin","timestamp":-1},"attrs":{"float":20.1,"int":2}} to admin/device-data
http-agent_1                  | 2021-12-10T20:32:43.296Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-10T20:32:43.297Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"3dde27","tenant":"admin","timestamp":-1},"attrs":{"float":49,"int":3}} to admin/device-data
```

**Comment by betefaber** [comment]
**single request:**

- invalid timestamps (result code: **400**)

> - timestamp = "**hoje**"

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "ts": "hoje",                       
      "data": {
        "temperature": 20
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
{"message":"Invalid timestamp"}
```
```
http-agent_1                  | 2021-12-23T12:11:18.871Z -- http-agent:express -- debug: Incoming request: {"id":"c82ec3f2-a27f-411e-a153-21d97d16aa15"}
http-agent_1                  | 2021-12-23T12:11:18.872Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:Invalid timestamp {"stack":"BadRequestError: Invalid timestamp\n    at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/opt/http-agent/index.js:4:29)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)"}
http-agent_1                  | 2021-12-23T12:11:18.872Z -- http-agent:express -- debug: request has been finished: {"id":"c82ec3f2-a27f-411e-a153-21d97d16aa15"}
http-agent_1                  | 2021-12-23T12:11:18.873Z -- http-agent:express -- info: c82ec3f2-a27f-411e-a153-21d97d16aa15 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "400 31bytes 1ms" "192.168.112.1 - curl/7.58.0"
```
> - timestamp = "2021-11-**35**T09:30:01.683000Z"

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Tyrization: ${JWT}" -d '{H "Author
      "ts": "2021-11-35T09:30:01.683000Z",
      "data": {
        "temperature": 35
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
{"message":"Invalid timestamp"}
```
``` 
http-agent_1                  | 2021-12-23T12:12:23.181Z -- http-agent:express -- debug: Incoming request: {"id":"6dba1d73-6a18-435d-ace3-8a9d5c6ab851"}
http-agent_1                  | 2021-12-23T12:12:23.185Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:Invalid timestamp {"stack":"BadRequestError: Invalid timestamp\n    at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/opt/http-agent/index.js:4:29)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)"}
http-agent_1                  | 2021-12-23T12:12:23.188Z -- http-agent:express -- debug: request has been finished: {"id":"6dba1d73-6a18-435d-ace3-8a9d5c6ab851"}
http-agent_1                  | 2021-12-23T12:12:23.189Z -- http-agent:express -- info: 6dba1d73-6a18-435d-ace3-8a9d5c6ab851 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "400 31bytes 6ms" "192.168.112.1 - curl/7.58.0"
```

> - timestamp = "2021-**13**-15T09:30:01.683000Z"

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "ts": "2021-13-15T09:30:01.683000Z",
      "data": {
        "temperature": 13
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
{"message":"Invalid timestamp"}
```
```
http-agent_1                  | 2021-12-23T12:58:41.305Z -- http-agent:express -- debug: Incoming request: {"id":"e82d36a0-9067-48d9-995c-2adad1b218c2"}
http-agent_1                  | 2021-12-23T12:58:41.308Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:Invalid timestamp {"stack":"BadRequestError: Invalid timestamp\n    at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/opt/http-agent/index.js:4:29)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)"}
http-agent_1                  | 2021-12-23T12:58:41.310Z -- http-agent:express -- debug: request has been finished: {"id":"e82d36a0-9067-48d9-995c-2adad1b218c2"}
http-agent_1                  | 2021-12-23T12:58:41.311Z -- http-agent:express -- info: e82d36a0-9067-48d9-995c-2adad1b218c2 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "400 31bytes 5ms" "192.168.112.1 - curl/7.58.0"
```

----
- valid timestamps (result code: **204**)

> - timestamp = "**2021-12-20T09:30:01.683000Z**"
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "ts": "2021-12-20T09:30:01.683000Z",
      "data": {
        "temperature": 16
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
```
```
http-agent_1                  | 2021-12-23T12:10:16.493Z -- http-agent:express -- debug: Incoming request: {"id":"4079ed0c-7d3f-4d7f-acce-f82397b7d3e9"}
http-agent_1                  | 2021-12-23T12:10:16.496Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-23T12:10:17.567Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-23T12:10:17.567Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1639992601683},"attrs":{"temperature":16}} to admin/device-data
http-agent_1                  | 2021-12-23T12:10:17.568Z -- http-agent:express -- debug: request has been finished: {"id":"4079ed0c-7d3f-4d7f-acce-f82397b7d3e9"}
http-agent_1                  | 2021-12-23T12:10:17.568Z -- http-agent:express -- info: 4079ed0c-7d3f-4d7f-acce-f82397b7d3e9 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "204 -bytes 1074ms" "192.168.112.1 - curl/7.58.0"
```

```
persister_1                   | [23/12/21 - 12:10:17] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': 1639992601683}, 'attrs': {'temperature': 16}}
```

> - timestamp = **-1**

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "ts": -1,                       
      "data": {
        "temperature": 20
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
```
```
http-agent_1                  | 2021-12-23T12:10:49.443Z -- http-agent:express -- debug: Incoming request: {"id":"ddca7a54-b64b-40a6-afa4-e79d463003aa"}
http-agent_1                  | 2021-12-23T12:10:49.446Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-23T12:10:50.464Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-23T12:10:50.464Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":-1},"attrs":{"temperature":20}} to admin/device-data
http-agent_1                  | 2021-12-23T12:10:50.465Z -- http-agent:express -- debug: request has been finished: {"id":"ddca7a54-b64b-40a6-afa4-e79d463003aa"}
http-agent_1                  | 2021-12-23T12:10:50.465Z -- http-agent:express -- info: ddca7a54-b64b-40a6-afa4-e79d463003aa "HTTP/1.1 POST /http-agent/v1/incoming-messages" "204 -bytes 1021ms" "192.168.112.1 - curl/7.58.0"
```
```
persister_1                   | [23/12/21 - 12:10:50] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': -1}, 'attrs': {'temperature': 20}}
```

> - timestamp = "Thursday, December 23, 2021 9:15:17 AM": valid (status 204)

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "ts": "Thursday, December 23, 2021 9:15:17 AM",
      "data": {
        "temperature": 23
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
```
```
http-agent_1                  | 2021-12-23T13:03:27.803Z -- http-agent:express -- debug: Incoming request: {"id":"cc3792a8-21a6-4659-96ae-2237a6ccea46"}
http-agent_1                  | 2021-12-23T13:03:27.808Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-23T13:03:28.816Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-23T13:03:28.816Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1640250917000},"attrs":{"temperature":23}} to admin/device-data
http-agent_1                  | 2021-12-23T13:03:28.816Z -- http-agent:express -- debug: request has been finished: {"id":"cc3792a8-21a6-4659-96ae-2237a6ccea46"}
http-agent_1                  | 2021-12-23T13:03:28.817Z -- http-agent:express -- info: cc3792a8-21a6-4659-96ae-2237a6ccea46 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "204 -bytes 1011ms" "192.168.112.1 - curl/7.58.0"
```
```
persister_1                   | [23/12/21 - 13:03:28] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': 1640250917000}, 'attrs': {'temperature': 23}}
```

**Comment by betefaber** [comment]
**multiple requests:**

- invalid timestamps: **_http-agent service restarts_**

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{
  "ts": "hoje",                       
   "data": {
        "temperature": 18.5
      }
},
{
  "ts": "ontem",                       
   "data": {
        "temperature": 20.1
      }
},
{ "ts": "agora",
  "data": {
        "temperature": 39
      }
}
]'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key

```

```
http-agent_1                  | 2021-12-23T14:14:20.695Z -- http-agent:express -- debug: Incoming request: {"id":"76fc140e-c34f-4a6b-ae69-e9f0ea079578"}
http-agent_1                  | 2021-12-23T14:14:20.726Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:14:20.726Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:14:20.726Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:14:20.727Z -- http-agent:express -- debug: request has been finished: {"id":"76fc140e-c34f-4a6b-ae69-e9f0ea079578"}
http-agent_1                  | 2021-12-23T14:14:20.729Z -- http-agent:express -- info: 76fc140e-c34f-4a6b-ae69-e9f0ea079578 "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "204 -bytes 30ms" "192.168.112.1 - curl/7.58.0"
http-agent_1                  | 2021-12-23T14:14:25.731Z -- microservice-sdk:service-state-manager -- warn: Removing 3 services...
http-agent_1                  | 2021-12-23T14:14:25.732Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-server"
http-agent_1                  | 2021-12-23T14:14:25.733Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-producer"
http-agent_1                  | 2021-12-23T14:14:25.733Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-cache"
http-agent_1                  | 2021-12-23T14:14:25.734Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
http-agent_1                  | 2021-12-23T14:14:25.735Z -- http-agent:Producer -- warn: Shutting down Kafka connection...
http-agent_1                  | 2021-12-23T14:14:25.736Z -- microservice-sdk:producer -- debug: Disconnecting from Kafka...
http-agent_1                  | 2021-12-23T14:14:25.736Z -- microservice-sdk:producer -- debug: Requesting message flushing before disconnect...
http-agent_1                  | 2021-12-23T14:14:25.738Z -- microservice-sdk:producer -- debug: ... all messages were flushed.
http-agent_1                  | 2021-12-23T14:14:25.740Z -- microservice-sdk:producer -- debug: Successfully disconnected producer from Kafka.
http-agent_1                  | 2021-12-23T14:14:25.741Z -- http-agent:Cache -- warn: Clearing the time interval that is set in the check period option...
http-agent_1                  | 2021-12-23T14:14:25.742Z -- http-agent:Server -- debug: Stopping the server from accepting new connections...
http-agent_1                  | 2021-12-23T14:14:25.744Z -- http-agent:Server -- warn: The server no longer accepts connections!
http-agent_1                  | 2021-12-23T14:14:25.746Z -- microservice-sdk:service-state-manager -- debug: Service "http-server" is not registered, will not signalize anything
http-agent_1                  | 2021-12-23T14:14:26.747Z -- microservice-sdk:service-state-manager -- warn: process did not exit on its own; investigate what is keeping the event loop active
http-agent_1                  | npm ERR! code ELIFECYCLE
http-agent_1                  | npm ERR! errno 1
http-agent_1                  | npm ERR! http-agent@0.0.1 start: `node index.js`
http-agent_1                  | npm ERR! Exit status 1
http-agent_1                  | npm ERR! 
http-agent_1                  | npm ERR! Failed at the http-agent@0.0.1 start script.
http-agent_1                  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
http-agent_1                  | 
http-agent_1                  | npm ERR! A complete log of this run can be found in:
http-agent_1                  | npm ERR!     /root/.npm/_logs/2021-12-23T14_14_26_795Z-debug.log
```
![Captura de tela de 2021-12-23 11-22-57](https://user-images.githubusercontent.com/37310063/147256110-68caff7f-4167-4653-9e60-073911629901.png)


- incorrect dates 
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{
      "ts": "2021-12-35T09:30:01.683000Z",
      "data": {
        "temperature": 35
      }
},
{
      "ts": "2021-13-15T09:35:01.683000Z",
      "data": {
        "temperature": 13
      }
},
{
      "ts": "2021-12-19T09:40:01.683000Z",
      "data": {
        "temperature": 13
      }
}
]'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
```
```
http-agent_1                  | 2021-12-23T14:37:14.459Z -- http-agent:express -- debug: Incoming request: {"id":"823afd90-31f7-4d54-a6e9-f1ef6b4040dc"}
http-agent_1                  | 2021-12-23T14:37:14.479Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-23T14:37:14.481Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:37:14.482Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:37:14.484Z -- http-agent:express -- debug: request has been finished: {"id":"823afd90-31f7-4d54-a6e9-f1ef6b4040dc"}
http-agent_1                  | 2021-12-23T14:37:14.485Z -- http-agent:express -- info: 823afd90-31f7-4d54-a6e9-f1ef6b4040dc "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "204 -bytes 24ms" "192.168.112.1 - curl/7.58.0"
http-agent_1                  | 2021-12-23T14:37:15.514Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-23T14:37:15.515Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1639906801683},"attrs":{"temperature":13}} to admin/device-data
http-agent_1                  | 2021-12-23T14:37:19.488Z -- microservice-sdk:service-state-manager -- warn: Removing 3 services...
http-agent_1                  | 2021-12-23T14:37:19.489Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-server"
http-agent_1                  | 2021-12-23T14:37:19.489Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-producer"
http-agent_1                  | 2021-12-23T14:37:19.490Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-cache"
http-agent_1                  | 2021-12-23T14:37:19.491Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
http-agent_1                  | 2021-12-23T14:37:19.491Z -- http-agent:Producer -- warn: Shutting down Kafka connection...
http-agent_1                  | 2021-12-23T14:37:19.492Z -- microservice-sdk:producer -- debug: Disconnecting from Kafka...
http-agent_1                  | 2021-12-23T14:37:19.493Z -- microservice-sdk:producer -- debug: Requesting message flushing before disconnect...
http-agent_1                  | 2021-12-23T14:37:19.494Z -- microservice-sdk:producer -- debug: ... all messages were flushed.
http-agent_1                  | 2021-12-23T14:37:19.497Z -- microservice-sdk:producer -- debug: Successfully disconnected producer from Kafka.
http-agent_1                  | 2021-12-23T14:37:19.500Z -- http-agent:Cache -- warn: Clearing the time interval that is set in the check period option...
http-agent_1                  | 2021-12-23T14:37:19.501Z -- http-agent:Server -- debug: Stopping the server from accepting new connections...
http-agent_1                  | 2021-12-23T14:37:19.503Z -- http-agent:Server -- warn: The server no longer accepts connections!
http-agent_1                  | 2021-12-23T14:37:19.505Z -- microservice-sdk:service-state-manager -- debug: Service "http-server" is not registered, will not signalize anything
http-agent_1                  | 2021-12-23T14:37:20.507Z -- microservice-sdk:service-state-manager -- warn: process did not exit on its own; investigate what is keeping the event loop active
http-agent_1                  | npm ERR! code ELIFECYCLE
http-agent_1                  | npm ERR! errno 1
http-agent_1                  | npm ERR! http-agent@0.0.1 start: `node index.js`
http-agent_1                  | npm ERR! Exit status 1
http-agent_1                  | npm ERR! 
http-agent_1                  | npm ERR! Failed at the http-agent@0.0.1 start script.
http-agent_1                  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
http-agent_1                  | 
http-agent_1                  | npm ERR! A complete log of this run can be found in:
http-agent_1                  | npm ERR!     /root/.npm/_logs/2021-12-23T14_37_20_546Z-debug.log
```

the data with the correct date is persisted:

```
persister_1                   | [23/12/21 - 14:37:15] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': 1639906801683}, 'attrs': {'temperature': 13}}
```

**Comment by betefaber** [comment]
The problem with invalid timestamp in multiple requests will be opened in another ticket.
