### ISSUE TITLE
[http-agent] error message with a wrong parameter

### ISSUE THREAD

**Issue by ctossato** [dojot/dojot#2353]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

when data field is missing in the publication, the http agent returns an error message mentioning "attrs" instead of "data".

Received error message:
 {'0': '"attrs" is required', '1': '"attrs" is required', '2': '"attrs" is required'}

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.7.0-rc1
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 18.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
Test OK

- simple request

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
"ts": "2021-10-03T09:30:01.683000Z" 
}'   --cacert ca.crt --cert admin_3dde27.crt --key admin_3dde27.key
{"message":"\"data\" is required"}
```
log:
```
http-agent_1                  | 2021-12-10T18:46:27.327Z -- http-agent:express -- debug: Incoming request: {"id":"df8d2efc-c805-49ca-b194-329fe63c8340"}
http-agent_1                  | 2021-12-10T18:46:27.328Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:"data" is required {"stack":"Error: \"data\" is required\n    at handlers.middleware (/opt/http-agent/app/express/routes/v1/IncomingMessages.js:37:23)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:275:10)"}
http-agent_1                  | 2021-12-10T18:46:27.328Z -- http-agent:express -- debug: request has been finished: {"id":"df8d2efc-c805-49ca-b194-329fe63c8340"}
http-agent_1                  | 2021-12-10T18:46:27.329Z -- http-agent:express -- info: df8d2efc-c805-49ca-b194-329fe63c8340 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "400 34bytes 1ms" "172.27.0.1 - curl/7.58.0"
```
----
- multiple requests 
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{"ts": "2021-10-03T10:30:01.000000Z"},
{"ts": "2021-10-03T10:42:02.000000Z"},
{"ts": "2021-10-03T10:50:00.000000Z"}
]'   --cacert ca.crt --cert admin_3dde27.crt --key admin_3dde27.key
{"message":{"0":"\"data\" is required","1":"\"data\" is required","2":"\"data\" is required"}}
```

log:
```
http-agent_1                  | 2021-12-10T18:59:34.545Z -- http-agent:express -- debug: Incoming request: {"id":"192708a0-c82a-40bb-b7da-f0a08ab9c7bd"}
http-agent_1                  | 2021-12-10T18:59:34.546Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:{"0":"\"data\" is required","1":"\"data\" is required","2":"\"data\" is required"} {"stack":"Error: {\"0\":\"\\\"data\\\" is required\",\"1\":\"\\\"data\\\" is required\",\"2\":\"\\\"data\\\" is required\"}\n    at handlers.middleware (/opt/http-agent/app/express/routes/v1/IncomingMessages.js:91:23)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:275:10)"}
http-agent_1                  | 2021-12-10T18:59:34.546Z -- http-agent:express -- debug: request has been finished: {"id":"192708a0-c82a-40bb-b7da-f0a08ab9c7bd"}
http-agent_1                  | 2021-12-10T18:59:34.547Z -- http-agent:express -- info: 192708a0-c82a-40bb-b7da-f0a08ab9c7bd "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "400 94bytes 1ms" "172.27.0.1 - curl/7.58.0"
```
