### ISSUE TITLE
[HTTP Agent] The http-agent service is restarted when multiple requests are sent with invalid timestamps 

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2415]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The http-agent service is restarted when multiple requests are sent with invalid timestamps.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

> - invalid timestamps

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{
  "ts": "hoje",                       
   "data": {
        "temperature": 18.5
      }
},
{
  "ts": "ontem",                       
   "data": {
        "temperature": 20.1
      }
},
{ "ts": "agora",
  "data": {
        "temperature": 39
      }
}
]'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key

```

```
http-agent_1                  | 2021-12-23T14:14:20.695Z -- http-agent:express -- debug: Incoming request: {"id":"76fc140e-c34f-4a6b-ae69-e9f0ea079578"}
http-agent_1                  | 2021-12-23T14:14:20.726Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:14:20.726Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:14:20.726Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:14:20.727Z -- http-agent:express -- debug: request has been finished: {"id":"76fc140e-c34f-4a6b-ae69-e9f0ea079578"}
http-agent_1                  | 2021-12-23T14:14:20.729Z -- http-agent:express -- info: 76fc140e-c34f-4a6b-ae69-e9f0ea079578 "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "204 -bytes 30ms" "192.168.112.1 - curl/7.58.0"
http-agent_1                  | 2021-12-23T14:14:25.731Z -- microservice-sdk:service-state-manager -- warn: Removing 3 services...
http-agent_1                  | 2021-12-23T14:14:25.732Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-server"
http-agent_1                  | 2021-12-23T14:14:25.733Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-producer"
http-agent_1                  | 2021-12-23T14:14:25.733Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-cache"
http-agent_1                  | 2021-12-23T14:14:25.734Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
http-agent_1                  | 2021-12-23T14:14:25.735Z -- http-agent:Producer -- warn: Shutting down Kafka connection...
http-agent_1                  | 2021-12-23T14:14:25.736Z -- microservice-sdk:producer -- debug: Disconnecting from Kafka...
http-agent_1                  | 2021-12-23T14:14:25.736Z -- microservice-sdk:producer -- debug: Requesting message flushing before disconnect...
http-agent_1                  | 2021-12-23T14:14:25.738Z -- microservice-sdk:producer -- debug: ... all messages were flushed.
http-agent_1                  | 2021-12-23T14:14:25.740Z -- microservice-sdk:producer -- debug: Successfully disconnected producer from Kafka.
http-agent_1                  | 2021-12-23T14:14:25.741Z -- http-agent:Cache -- warn: Clearing the time interval that is set in the check period option...
http-agent_1                  | 2021-12-23T14:14:25.742Z -- http-agent:Server -- debug: Stopping the server from accepting new connections...
http-agent_1                  | 2021-12-23T14:14:25.744Z -- http-agent:Server -- warn: The server no longer accepts connections!
http-agent_1                  | 2021-12-23T14:14:25.746Z -- microservice-sdk:service-state-manager -- debug: Service "http-server" is not registered, will not signalize anything
http-agent_1                  | 2021-12-23T14:14:26.747Z -- microservice-sdk:service-state-manager -- warn: process did not exit on its own; investigate what is keeping the event loop active
http-agent_1                  | npm ERR! code ELIFECYCLE
http-agent_1                  | npm ERR! errno 1
http-agent_1                  | npm ERR! http-agent@0.0.1 start: `node index.js`
http-agent_1                  | npm ERR! Exit status 1
http-agent_1                  | npm ERR! 
http-agent_1                  | npm ERR! Failed at the http-agent@0.0.1 start script.
http-agent_1                  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
http-agent_1                  | 
http-agent_1                  | npm ERR! A complete log of this run can be found in:
http-agent_1                  | npm ERR!     /root/.npm/_logs/2021-12-23T14_14_26_795Z-debug.log
```

> - incorrect dates 

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{
      "ts": "2021-12-35T09:30:01.683000Z",
      "data": {
        "temperature": 35
      }
},
{
      "ts": "2021-13-15T09:35:01.683000Z",
      "data": {
        "temperature": 13
      }
},
{
      "ts": "2021-12-19T09:40:01.683000Z",
      "data": {
        "temperature": 13
      }
}
]'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
```
```
http-agent_1                  | 2021-12-23T14:37:14.459Z -- http-agent:express -- debug: Incoming request: {"id":"823afd90-31f7-4d54-a6e9-f1ef6b4040dc"}
http-agent_1                  | 2021-12-23T14:37:14.479Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2021-12-23T14:37:14.481Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:37:14.482Z -- http-agent:index -- error: Unhandled Rejection at: BadRequestError: Invalid timestamp
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
http-agent_1                  |     at Module.load (internal/modules/cjs/loader.js:863:32)
http-agent_1                  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
http-agent_1                  |     at Module.require (internal/modules/cjs/loader.js:887:19)
http-agent_1                  |     at require (internal/modules/cjs/helpers.js:74:18)
http-agent_1                  |     at Object.<anonymous> (/opt/http-agent/index.js:4:29)
http-agent_1                  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
http-agent_1                  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10).
http-agent_1                  | 2021-12-23T14:37:14.484Z -- http-agent:express -- debug: request has been finished: {"id":"823afd90-31f7-4d54-a6e9-f1ef6b4040dc"}
http-agent_1                  | 2021-12-23T14:37:14.485Z -- http-agent:express -- info: 823afd90-31f7-4d54-a6e9-f1ef6b4040dc "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "204 -bytes 24ms" "192.168.112.1 - curl/7.58.0"
http-agent_1                  | 2021-12-23T14:37:15.514Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2021-12-23T14:37:15.515Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1639906801683},"attrs":{"temperature":13}} to admin/device-data
http-agent_1                  | 2021-12-23T14:37:19.488Z -- microservice-sdk:service-state-manager -- warn: Removing 3 services...
http-agent_1                  | 2021-12-23T14:37:19.489Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-server"
http-agent_1                  | 2021-12-23T14:37:19.489Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-producer"
http-agent_1                  | 2021-12-23T14:37:19.490Z -- microservice-sdk:service-state-manager -- warn: Removed service "http-cache"
http-agent_1                  | 2021-12-23T14:37:19.491Z -- microservice-sdk:service-state-manager -- warn: ... successfully removed all services
http-agent_1                  | 2021-12-23T14:37:19.491Z -- http-agent:Producer -- warn: Shutting down Kafka connection...
http-agent_1                  | 2021-12-23T14:37:19.492Z -- microservice-sdk:producer -- debug: Disconnecting from Kafka...
http-agent_1                  | 2021-12-23T14:37:19.493Z -- microservice-sdk:producer -- debug: Requesting message flushing before disconnect...
http-agent_1                  | 2021-12-23T14:37:19.494Z -- microservice-sdk:producer -- debug: ... all messages were flushed.
http-agent_1                  | 2021-12-23T14:37:19.497Z -- microservice-sdk:producer -- debug: Successfully disconnected producer from Kafka.
http-agent_1                  | 2021-12-23T14:37:19.500Z -- http-agent:Cache -- warn: Clearing the time interval that is set in the check period option...
http-agent_1                  | 2021-12-23T14:37:19.501Z -- http-agent:Server -- debug: Stopping the server from accepting new connections...
http-agent_1                  | 2021-12-23T14:37:19.503Z -- http-agent:Server -- warn: The server no longer accepts connections!
http-agent_1                  | 2021-12-23T14:37:19.505Z -- microservice-sdk:service-state-manager -- debug: Service "http-server" is not registered, will not signalize anything
http-agent_1                  | 2021-12-23T14:37:20.507Z -- microservice-sdk:service-state-manager -- warn: process did not exit on its own; investigate what is keeping the event loop active
http-agent_1                  | npm ERR! code ELIFECYCLE
http-agent_1                  | npm ERR! errno 1
http-agent_1                  | npm ERR! http-agent@0.0.1 start: `node index.js`
http-agent_1                  | npm ERR! Exit status 1
http-agent_1                  | npm ERR! 
http-agent_1                  | npm ERR! Failed at the http-agent@0.0.1 start script.
http-agent_1                  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
http-agent_1                  | 
http-agent_1                  | npm ERR! A complete log of this run can be found in:
http-agent_1                  | npm ERR!     /root/.npm/_logs/2021-12-23T14_37_20_546Z-debug.log
```

**Note**: the data with the correct date is persisted:

```
persister_1                   | [23/12/21 - 14:37:15] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': 1639906801683}, 'attrs': {'temperature': 13}}
```

* **What is the expected behavior?**
Same behavior when sending simple requests.
For single requests the response message is `Invalid timestamp` and the result code is `400`.

> - timestamp = "hoje"

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '{
      "ts": "hoje",                       
      "data": {
        "temperature": 20
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
{"message":"Invalid timestamp"}
```
```
http-agent_1                  | 2021-12-23T12:11:18.871Z -- http-agent:express -- debug: Incoming request: {"id":"c82ec3f2-a27f-411e-a153-21d97d16aa15"}
http-agent_1                  | 2021-12-23T12:11:18.872Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:Invalid timestamp {"stack":"BadRequestError: Invalid timestamp\n    at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/opt/http-agent/index.js:4:29)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)"}
http-agent_1                  | 2021-12-23T12:11:18.872Z -- http-agent:express -- debug: request has been finished: {"id":"c82ec3f2-a27f-411e-a153-21d97d16aa15"}
http-agent_1                  | 2021-12-23T12:11:18.873Z -- http-agent:express -- info: c82ec3f2-a27f-411e-a153-21d97d16aa15 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "400 31bytes 1ms" "192.168.112.1 - curl/7.58.0"
```

> - timestamp = "2021-**13**-15T09:30:01.683000Z"

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '
{
      "ts": "2021-13-15T09:30:01.683000Z",
      "data": {
        "temperature": 13
      }
  }'   --cacert ca.crt --cert admin_2a1503.crt --key admin_2a1503.key
{"message":"Invalid timestamp"}
```
```
http-agent_1                  | 2021-12-23T12:58:41.305Z -- http-agent:express -- debug: Incoming request: {"id":"e82d36a0-9067-48d9-995c-2adad1b218c2"}
http-agent_1                  | 2021-12-23T12:58:41.308Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:Invalid timestamp {"stack":"BadRequestError: Invalid timestamp\n    at Object.<anonymous> (/opt/http-agent/app/Utils.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/opt/http-agent/index.js:4:29)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)"}
http-agent_1                  | 2021-12-23T12:58:41.310Z -- http-agent:express -- debug: request has been finished: {"id":"e82d36a0-9067-48d9-995c-2adad1b218c2"}
http-agent_1                  | 2021-12-23T12:58:41.311Z -- http-agent:express -- info: e82d36a0-9067-48d9-995c-2adad1b218c2 "HTTP/1.1 POST /http-agent/v1/incoming-messages" "400 31bytes 5ms" "192.168.112.1 - curl/7.58.0"
```

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.7.1-rc.2
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![Captura de tela de 2021-12-23 11-22-57](https://user-images.githubusercontent.com/37310063/147286069-3be9450c-6bda-4e20-9fe9-98a3bcb7421e.png)

**Comment by betefaber** [comment]
Test **OK**.

```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{
  "ts": "hoje",                       
   "data": {
        "temperature": 18.5
      }
},
{
  "ts": "ontem",                       
   "data": {
        "temperature": 20.1
      }
},
{ "ts": "agora",
  "data": {
        "temperature": 39
      }
}
]'   --cacert caDojot.crt --cert admin_2a1503.crt --key admin_2a1503.key 2>/dev/null | jq
{
  "error": {
    "0": "Invalid timestamp",
    "1": "Invalid timestamp",
    "2": "Invalid timestamp"
  }
}
```

```
http-agent_1                  | 2022-01-31T15:07:35.972Z -- http-agent:express -- debug: Incoming request: {"id":"11bdca58-1389-4640-9ca6-1427ff895bdf"}
http-agent_1                  | 2022-01-31T15:07:35.973Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:{"0":"Invalid timestamp","1":"Invalid timestamp","2":"Invalid timestamp"} {"stack":"Error: {\"0\":\"Invalid timestamp\",\"1\":\"Invalid timestamp\",\"2\":\"Invalid timestamp\"}\n    at handlers.middleware (/opt/http-agent/app/express/routes/v1/IncomingMessages.js:106:23)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:275:10)"}
http-agent_1                  | 2022-01-31T15:07:35.974Z -- http-agent:express -- debug: request has been finished: {"id":"11bdca58-1389-4640-9ca6-1427ff895bdf"}
http-agent_1                  | 2022-01-31T15:07:35.974Z -- http-agent:express -- info: 11bdca58-1389-4640-9ca6-1427ff895bdf "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "400 83bytes 2ms" "192.168.240.1 - curl/7.58.0"

```
```
curl -X POST https://localhost:8080/http-agent/v1/incoming-messages/create-many -H 'Content-Type: application/json' -H "Authorization: ${JWT}" -d '[
{
  "ts": 1643379000000,                       
   "data": {
        "temperature": 12.5
      }
},
{
  "ts": "ontem" ,                       
   "data": {
        "temperature": 16
      }
},
{ "ts": 1643638212000,
  "data": {
        "temperature": 24
      }
}
]'   --cacert caDojot.crt --cert admin_2a1503.crt --key admin_2a1503.key 2>/dev/null | jq
{
  "error": {
    "1": "Invalid timestamp"
  }
}
```

```
http-agent_1                  | 2022-01-31T15:16:14.442Z -- http-agent:express -- debug: Incoming request: {"id":"9c7d1522-7d43-49aa-82b6-752f426e57fa"}
http-agent_1                  | 2022-01-31T15:16:14.444Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2022-01-31T15:16:14.447Z -- http-agent:Producer -- debug: Trying to send message to kafka topic admin.device-data...
http-agent_1                  | 2022-01-31T15:16:14.447Z -- http-agent:express/routes/v1/Device -- error: incoming-messages.post:{"1":"Invalid timestamp"} {"stack":"Error: {\"1\":\"Invalid timestamp\"}\n    at handlers.middleware (/opt/http-agent/app/express/routes/v1/IncomingMessages.js:106:23)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:335:12)\n    at next (/opt/http-agent/node_modules/@dojot/microservice-sdk/node_modules/express/lib/router/index.js:275:10)"}
http-agent_1                  | 2022-01-31T15:16:14.448Z -- http-agent:express -- debug: request has been finished: {"id":"9c7d1522-7d43-49aa-82b6-752f426e57fa"}
http-agent_1                  | 2022-01-31T15:16:14.449Z -- http-agent:express -- info: 9c7d1522-7d43-49aa-82b6-752f426e57fa "HTTP/1.1 POST /http-agent/v1/incoming-messages/create-many" "400 35bytes 5ms" "192.168.240.1 - curl/7.58.0"
http-agent_1                  | 2022-01-31T15:16:15.533Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2022-01-31T15:16:15.533Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1643379000000},"attrs":{"temperature":12.5}} to admin/device-data
http-agent_1                  | 2022-01-31T15:16:15.534Z -- http-agent:Producer -- debug: Successfully sent message to Kafka in admin.device-data
http-agent_1                  | 2022-01-31T15:16:15.534Z -- http-agent:Producer -- debug: Published message {"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1643638212000},"attrs":{"temperature":24}} to admin/device-data
```

```
persister_1                   | [31/01/22 - 15:16:15] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': 1643379000000}, 'attrs': {'temperature': 12.5}}
persister_1                   | [31/01/22 - 15:16:15] |persister| DEBUG: got data event b'{"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1643379000000},"attrs":{"temperature":12.5}}'
persister_1                   | [31/01/22 - 15:16:15] |persister| INFO: Received data: {'metadata': {'deviceid': '2a1503', 'tenant': 'admin', 'timestamp': 1643638212000}, 'attrs': {'temperature': 24}}
persister_1                   | [31/01/22 - 15:16:15] |persister| DEBUG: got data event b'{"metadata":{"deviceid":"2a1503","tenant":"admin","timestamp":1643638212000},"attrs":{"temperature":24}}'
```
