### ISSUE TITLE
[Flowbroker] No flows run

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#2577]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Flowbroker is not working. No flows run.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Example:
![image](https://user-images.githubusercontent.com/37310063/168899659-fad5ec62-5cab-419e-86d6-5756aa65d4cf.png)

```
mosquitto_pub -h localhost -p 1883 -t admin:3875bd/attrs -u admin:3875bd -m '{"velocidade": 75}' 2>/dev/null -d
Client mosqpub|21142-mcity75 sending CONNECT
Client mosqpub|21142-mcity75 received CONNACK
Client mosqpub|21142-mcity75 sending PUBLISH (d0, q0, r0, m1, 'admin:3875bd/attrs', ... (18 bytes))
Client mosqpub|21142-mcity75 sending DISCONNECT
```
```
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: Got a message in topic admin.device-data.
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: There are 1 callbacks registered.
flowbroker_1                  | <19:21:08 17/05/2022> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c 22 64 65 76 69 63 65 69 64 22 3a 22 33 38 37 35 62 64 22 2c ... >,
flowbroker_1                  |   size: 103,
flowbroker_1                  |   key: <Buffer 61 64 6d 69 6e 3a 33 38 37 35 62 64>,
flowbroker_1                  |   topic: 'admin.device-data',
flowbroker_1                  |   offset: 56,
flowbroker_1                  |   partition: 0,
flowbroker_1                  |   timestamp: 1652815268186 } 
flowbroker_1                  | <19:21:08 17/05/2022> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: { 'fa08bf5d-f76c-4451-a56c-35a15a0a075c': [Function] }
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: Mapping device 3875bd ===into===> event_queue7
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"tenant\":\"admin\",\"deviceid\":\"3875bd\",\"timestamp\":1652815268186},\"attrs\":{\"velocidade\":75}}"}
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <19:21:08 17/05/2022> -- |dev cache -- DEBUG: retriving data related to admin:3875bd from cache
flowbroker_1                  | <19:21:08 17/05/2022> -- DEBUG: [ingestor] got new device event: { metadata: { tenant: 'admin', timestamp: 1652815268186 },
flowbroker_1                  |   event: 'publish',
flowbroker_1                  |   data: { attrs: { velocidade: 75, protocol: 'mqtt' }, id: '3875bd' } }
```

`anemômetro` history:
```
curl -X GET "localhost:8000/history/device/3875bd/history?attr=velocidade&lastN=1" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq
[
  {
    "attr": "velocidade",
    "value": 75,
    "device_id": "3875bd",
    "ts": "2022-05-17T19:21:08.186000Z",
    "metadata": {}
  }
]
```
`controle` history:
```
curl -X GET "localhost:8000/history/device/3cc788/history?attr=mensagem" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq
{
  "title": "Attr not found",
  "description": "No data for the given attribute could be found"
}
```

* **What is the expected behavior?**
Flow run. 
In this example, the message `vento muito forte` should be set in the `mensagem` attribute of the device `controle`

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: **0.8.0-rc.2**
  - Environment: docker-compose
  - Operating system: Ubuntu 18.04

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by betefaber** [comment]
### Note

If the flowbroker service is restarted, an error occurs when the flow reruns.

`mosquitto_pub -h localhost -p 1883 -t admin:3875bd/attrs -u admin:3875bd -m '{"velocidade": 60}'`

```
flowbroker_1                  | <13:38:59 18/05/2022> -- DEBUG: Got a message in topic admin.device-data.
flowbroker_1                  | <13:38:59 18/05/2022> -- DEBUG: There are 1 callbacks registered.
flowbroker_1                  | <13:38:59 18/05/2022> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c 22 64 65 76 69 63 65 69 64 22 3a 22 33 38 37 35 62 64 22 2c ... >,
flowbroker_1                  |   size: 103,
flowbroker_1                  |   key: <Buffer 61 64 6d 69 6e 3a 33 38 37 35 62 64>,
flowbroker_1                  |   topic: 'admin.device-data',
flowbroker_1                  |   offset: 23,
flowbroker_1                  |   partition: 0,
flowbroker_1                  |   timestamp: 1652881139069 } 
flowbroker_1                  | <13:38:59 18/05/2022> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
flowbroker_1                  | <13:38:59 18/05/2022> -- DEBUG: { '3de1ce20-b7b0-41c4-ba88-05aa1ac06824': [Function] }
flowbroker_1                  | <13:38:59 18/05/2022> -- DEBUG: Mapping device 3875bd ===into===> event_queue7
flowbroker_1                  | <13:38:59 18/05/2022> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"tenant\":\"admin\",\"deviceid\":\"3875bd\",\"timestamp\":1652881139069},\"attrs\":{\"velocidade\":60}}"}
flowbroker_1                  | <13:38:59 18/05/2022> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <13:38:59 18/05/2022> -- |dev cache -- DEBUG: failingback to retrieve data related to admin:3875bd from device-manager
flowbroker_1                  | <13:38:59 18/05/2022> -- |dev cache -- DEBUG: [redis] Could not get from redis, will request to device manager
flowbroker_1                  | <13:38:59 18/05/2022> -- ERROR: [ingestor] device-manager event ingestion failed: Error: Request failed with status code 404
flowbroker_1                  |     at createError (/opt/flowbroker/orchestrator/node_modules/axios/lib/core/createError.js:16:15)
flowbroker_1                  |     at settle (/opt/flowbroker/orchestrator/node_modules/axios/lib/core/settle.js:18:12)
flowbroker_1                  |     at IncomingMessage.handleStreamEnd (/opt/flowbroker/orchestrator/node_modules/axios/lib/adapters/http.js:202:11)
flowbroker_1                  |     at emitNone (events.js:111:20)
flowbroker_1                  |     at IncomingMessage.emit (events.js:208:7)
flowbroker_1                  |     at endReadableNT (_stream_readable.js:1064:12)
flowbroker_1                  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
flowbroker_1                  |     at process._tickCallback (internal/process/next_tick.js:181:9)
flowbroker_1                  | <13:38:59 18/05/2022> -- ERROR: Problem on pre process event. Reason: Failed to process device event
```

**Comment by betefaber** [comment]
### Note

After restarting the service a few times the flows run.

**Comment by betefaber** [comment]
**Repeating the test:**

- restart dojot
```
docker-compose down -v
docker-compose up -d
```
- devices created
```
curl -X GET "localhost:8000/device?idsOnly=true" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq
[
  "2c3f04",
  "2e4c8d",
  "3bb02f",
  "3bee43",
  "53320b",
  "5807a4",
  "5e5a96",
  "72f651",
  "7da788",
  "87450d",
  "978f13",
  "9b51aa",
  "aa2bcc",
  "b60d7b",
  "d6e3a8",
  "e3b9b2",
  "eefd69",
  "ef965c",
  "f89738"
]
```

![image](https://user-images.githubusercontent.com/37310063/169871436-e7eba6fa-0b8d-4b87-b1c4-a9c49cf83277.png)


![image](https://user-images.githubusercontent.com/37310063/169871288-810198f4-cc5b-49ea-9f2a-b10d38105b24.png)

```
device-manager_1              | [23/05/22 - 14:46:40] |DeviceHandler| INFO:  Creating a new device with id 7da788.
device-manager_1              | [23/05/22 - 14:46:40] |BackendHandler| INFO:  Publishing create event to Kafka
device-manager_1              | [23/05/22 - 14:46:40] |DeviceHandler| INFO:  Creating a new device with id 3bee43.
device-manager_1              | [23/05/22 - 14:46:40] |BackendHandler| INFO:  Publishing create event to Kafka
```
``` 
flowbroker_1                  | <14:46:40 23/05/2022> -- |messenger -- DEBUG: Emitting new event message for subject dojot.device-manager.device@admin
flowbroker_1                  | <14:46:40 23/05/2022> -- DEBUG: { 'e2003ef0-4efd-4525-9351-b006b938f0a3': [Function] }
flowbroker_1                  | <14:46:40 23/05/2022> -- DEBUG: Mapping device 7da788 ===into===> event_queue8
flowbroker_1                  | <14:46:40 23/05/2022> -- DEBUG: Pre-processing event {"source":"device-manager","message":"{\"event\":\"create\",\"data\":{\"created\":\"2022-05-23T14:46
:40.658527+00:00\",\"id\":\"7da788\",\"label\":\"anemometro\",\"templates\":[\"4\",\"5\"],\"attrs\":{\"4\":[{\"created\":\"2022-05-23T14:46:39.036472+00:00\",\"id\":8,\"label\":\"velocidade\",\"value_type
\":\"float\",\"metadata\":[{\"static_value\":\"km/h\",\"created\":\"2022-05-23T14:46:39.037459+00:00\",\"id\":9,\"updated\":null,\"label\":\"unidade\",\"value_type\":\"string\",\"type\":\"meta\",\"is_stat
ic_overridden\":false}],\"type\":\"dynamic\",\"template_id\":\"4\"}],\"5\":[{\"static_value\":\"mqtt\",\"created\":\"2022-05-23T14:46:39.057689+00:00\",\"id\":10,\"label\":\"protocol\",\"value_type\":\"st
ring\",\"type\":\"static\",\"template_id\":\"5\",\"is_static_overridden\":false}]}},\"meta\":{\"service\":\"admin\"}}"}
flowbroker_1                  | <14:46:40 23/05/2022> -- |dev cache -- DEBUG: storing device info on cache . . .
flowbroker_1                  | <14:46:40 23/05/2022> -- |dev cache -- DEBUG: . . . device info stored successfully

flowbroker_1                  | <14:46:40 23/05/2022> -- |messenger -- DEBUG: Emitting new event message for subject dojot.device-manager.device@admin
flowbroker_1                  | <14:46:40 23/05/2022> -- DEBUG: { 'e2003ef0-4efd-4525-9351-b006b938f0a3': [Function] }
flowbroker_1                  | <14:46:40 23/05/2022> -- DEBUG: Mapping device 3bee43 ===into===> event_queue9
flowbroker_1                  | <14:46:40 23/05/2022> -- DEBUG: Pre-processing event {"source":"device-manager","message":"{\"event\":\"create\",\"data\":{\"created\":\"2022-05-23T14:46
:40.900654+00:00\",\"id\":\"3bee43\",\"label\":\"controle\",\"templates\":[\"7\"],\"attrs\":{\"7\":[{\"static_value\":\"\",\"created\":\"2022-05-23T14:46:39.114017+00:00\",\"id\":23,\"label\":\"display\",
\"value_type\":\"string\",\"type\":\"actuator\",\"template_id\":\"7\",\"is_static_overridden\":false},{\"static_value\":\"\",\"created\":\"2022-05-23T14:46:39.114369+00:00\",\"id\":24,\"label\":\"objeto\"
,\"value_type\":\"object\",\"type\":\"actuator\",\"template_id\":\"7\",\"is_static_overridden\":false},{\"created\":\"2022-05-23T14:46:39.113653+00:00\",\"id\":22,\"label\":\"medida\",\"value_type\":\"flo
at\",\"type\":\"dynamic\",\"template_id\":\"7\"},{\"created\":\"2022-05-23T14:46:39.113243+00:00\",\"id\":21,\"label\":\"mensagem\",\"value_type\":\"string\",\"type\":\"dynamic\",\"template_id\":\"7\"}]}}
,\"meta\":{\"service\":\"admin\"}}"}
flowbroker_1                  | <14:46:40 23/05/2022> -- |dev cache -- DEBUG: storing device info on cache . . .
flowbroker_1                  | <14:46:40 23/05/2022> -- |dev cache -- DEBUG: . . . device info stored successfully
```

- the data is published but the **flow is not executed**
```
mosquitto_pub -h localhost -p 1883 -t admin:7da788/attrs -u admin:7da788 -m '{"velocidade": 50}
```
```
flowbroker_1                  | <14:47:30 23/05/2022> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: { '97461a8b-acca-4ca3-b762-1272510e8dfa': [Function] }
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: Mapping device 7da788 ===into===> event_queue8
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"tenant\":\"admin\",\"deviceid\":\"7da788\",\"timestam
p\":1653317250201},\"attrs\":{\"velocidade\":50}}"}
flowbroker_1                  | <14:47:30 23/05/2022> -- |dev cache -- DEBUG: retriving data related to admin:7da788 from cache
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: [ingestor] got new device event: { metadata: { tenant: 'admin', timestamp: 1653317250201 },
flowbroker_1                  |   event: 'publish',
flowbroker_1                  |   data: { attrs: { velocidade: 50, protocol: 'mqtt' }, id: '7da788' } }
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: Queued event [object Object]
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: Pre-processing event {"source":"device","message":"{\"metadata\":{\"tenant\":\"admin\",\"deviceid\":\"7da788\",\"timestam
p\":1653317250203},\"attrs\":{\"velocidade\":50}}"}
flowbroker_1                  | <14:47:30 23/05/2022> -- |dev cache -- DEBUG: retriving data related to admin:7da788 from cache
flowbroker_1                  | <14:47:30 23/05/2022> -- DEBUG: [ingestor] got new device event: { metadata: { tenant: 'admin', timestamp: 1653317250203 },
flowbroker_1                  |   event: 'publish',
flowbroker_1                  |   data: { attrs: { velocidade: 50, protocol: 'mqtt' }, id: '7da788' } }
flowbroker_1                  | <14:47:35 23/05/2022> -- DEBUG: Got a message in topic admin.device-data.
```

```
curl -X GET "localhost:8000/history/device/7da788/history?attr=velocidade&lastN=1" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq[
  {
    "attr": "velocidade",
    "value": 50,
    "device_id": "7da788",
    "ts": "2022-05-23T14:47:30.203000Z",
    "metadata": {}
  }
]
```
```
curl -X GET "localhost:8000/history/device/3bee43/history?attr=mensagem,medida" -H "Authorization: Bearer ${JWT}"  -H 'Content-Type:application/json' 2>/dev/null | jq
{
  "mensagem": [],
  "medida": []
}
```


- after a while there is an **error getting the device**
```
device-manager_1              | [23/05/22 - 15:43:49] |TemplateHandler| INFO: Getting template with id: 4
device-manager_1              | [23/05/22 - 15:44:40] |DeviceHandler| INFO:  Getting latest added device(s).
device-manager_1              | [2022-05-23 15:46:08,375] ERROR in app: Exception on /device [GET]
device-manager_1              | Traceback (most recent call last):
device-manager_1              |   File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
device-manager_1              |     response = self.full_dispatch_request()
device-manager_1              |   File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
device-manager_1              |     rv = self.handle_user_exception(e)
device-manager_1              |   File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
device-manager_1              |     reraise(exc_type, exc_value, tb)
device-manager_1              |   File "/usr/src/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
device-manager_1              |     raise value
device-manager_1              |   File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
device-manager_1              |     rv = self.dispatch_request()
device-manager_1              |   File "/usr/src/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
device-manager_1              |     return self.view_functions[rule.endpoint](**req.view_args)
device-manager_1              |   File "/usr/src/app/DeviceManager/DeviceHandler.py", line 972, in flask_get_devices
device-manager_1              |     result = DeviceHandler.get_devices(token, params)
device-manager_1              |   File "/usr/src/app/DeviceManager/DeviceHandler.py", line 275, in get_devices
device-manager_1              |     attr_label.append(DeviceAttr.label == parsed.group(1))
device-manager_1              | AttributeError: 'NoneType' object has no attribute 'group'
device-manager_1              | [23/05/22 - 15:46:32] |DeviceHandler| INFO:  Getting the device with id 7da788.
device-manager_1              | [23/05/22 - 15:47:32] |DeviceHandler| INFO:  Getting latest added device(s).
device-manager_1              | [23/05/22 - 15:47:47] |DeviceHandler| INFO:  Getting the device with id 7da788.
device-manager_1              | [23/05/22 - 15:48:22] |DeviceHandler| INFO:  Getting the device with id 3bee43
.
.
.
device-manager_1              | [23/05/22 - 16:09:03] |DeviceHandler| INFO:  Getting the device with id 7da788.
device-manager_1              | [23/05/22 - 16:09:12] |DeviceHandler| INFO:  Getting the device with id 3bee43.
```

**Comment by betefaber** [comment]
script used to run the test: 
[script_2577.sh.txt](https://github.com/dojot/dojot/files/9133976/script_2577.sh.txt)

**Comment by betefaber** [comment]
The error remains in **v0.8.0-rc.6**. 

Task queue consumers are not created.

![Captura de tela de 2022-08-11 16-28-06](https://user-images.githubusercontent.com/37310063/184226160-022dcbf3-3410-492e-903e-ce5633076b84.png)

![Captura de tela de 2022-08-11 16-34-33](https://user-images.githubusercontent.com/37310063/184226053-4536df23-8b06-4ff4-9cdb-093ef62ec6a7.png)

[flowbroker.log](https://github.com/dojot/dojot/files/9311593/flowbroker.log)
