### ISSUE TITLE
iotagent-mqtt (iotagent-mosca) is not automatically respawning on failure

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#309]
```
[iota:kafka] Failed to acquire topic to subscribe from (device events)
 { Error: connect ECONNREFUSED 172.18.0.14:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.18.0.14',
  port: 80,
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        authorization: 'Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiaW50ZXJuYWwiLCJ1c2VybmFtZSI6ImlvdGFnZW50In0=.ZHVtbXkgc2lnbmF0dXJl',
        'User-Agent': 'axios/0.17.1' },
     method: 'get',
     url: 'http://data-broker:80/topic/dojot.tenancy?global=true',
     data: undefined },
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        hostname: 'data-broker',
        port: '80',
        path: '/topic/dojot.tenancy?global=true',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        nativeProtocols: [Object],
        pathname: '/topic/dojot.tenancy',
        search: '?global=true' },
     _redirectCount: 0,
     _requestBodyLength: 0,
     _requestBodyBuffers: [],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /topic/dojot.tenancy?global=true HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nauthorization: Bearer and0IHNjaGVtYQ==.eyJzZXJ2aWNlIjoiaW50ZXJuYWwiLCJ1c2VybmFtZSI6ImlvdGFnZW50In0=.ZHVtbXkgc2lnbmF0dXJl\r\nUser-Agent: axios/0.17.1\r\nHost: data-broker\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/topic/dojot.tenancy?global=true',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'http://data-broker:80/topic/dojot.tenancy?global=true' },
  response: undefined }
```

**Comment by mmagr** [comment]
This should be fixed on [0.2.0-nightly20180319](https://github.com/dojot-nightly/docker-compose/releases/tag/0.2.0-nightly20180319).

@betefaber can you please verify?
