### ISSUE TITLE
error when listing templates with new user

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#377]
**Log in with a newly registered user:**

![image](https://user-images.githubusercontent.com/37310063/38051555-0e69fc42-32a5-11e8-82e0-a4b16c0df042.png)

![image](https://user-images.githubusercontent.com/37310063/38051569-1a34d204-32a5-11e8-896d-262f41708c6c.png)

**Note: With an user already registered the error does not occur**

![image](https://user-images.githubusercontent.com/37310063/38051595-25c83304-32a5-11e8-9162-2e89e58e7d88.png)

**Comment by mmagr** [comment]
As an addendum - this is the log of the `image-manager` service, during those failures:

```
[2018-03-28 19:02:46,435] ERROR in app: Exception on /image/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/ImageManager/TenancyManager.py", line 35, in get_allowed_service
    data = json.loads(decode_base64(payload))
  File "/usr/src/app/ImageManager/TenancyManager.py", line 18, in decode_base64
    return base64.decodebytes(data).decode("utf-8")
  File "/usr/local/lib/python3.5/base64.py", line 553, in decodebytes
    _input_type_check(s)
  File "/usr/local/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/Flask-0.12-py3.5.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/Flask-0.12-py3.5.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/Flask-0.12-py3.5.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/Flask-0.12-py3.5.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/Flask-0.12-py3.5.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/Flask-0.12-py3.5.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/ImageManager/ImageManager.py", line 34, in get_all
    init_tenant_context(request, db, minioClient)
  File "/usr/src/app/ImageManager/TenancyManager.py", line 83, in init_tenant_context
    tenant = get_allowed_service(token)
  File "/usr/src/app/ImageManager/TenancyManager.py", line 38, in get_allowed_service
    raise ValueError("Invalid authentication token payload - not json object", ex)
ValueError: ('Invalid authentication token payload - not json object', TypeError('expected bytes-like object, not str',))
172.18.0.3 - - [28/Mar/2018:19:02:46 +0000] "GET /image/ HTTP/1.1" 500 25 "http://10.50.11.195:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
```

**Comment by ericbaum** [comment]
This issue probably happened because the new user was created with the "User" profile.

In the Auth service initialization the fw-image endpoint is not mapped to the "User" profile.

**Comment by ericbaum** [comment]
This issue probably happened because the new user was created with the "User" profile.

In the Auth service initialization the fw-image endpoint is not mapped to the "User" profile.

**Comment by betefaber** [comment]
curl "http://10.50.11.195:8000/fw-image/image?label=onibus" -H "authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIyYzY3YVZRRXBrWEJia1VEVlAyWUVZTGluVG9FazFoVyIsImlhdCI6MTUyMjcwMTY1NiwiZXhwIjoxNTIyNzAyMDc2LCJuYW1lIjoiQmV0ZSIsImVtYWlsIjoiZWZhYmVyQGNwcWQuY29tLmJyIiwicHJvZmlsZSI6ImFkbWluIiwiZ3JvdXBzIjpbMV0sInVzZXJpZCI6MiwianRpIjoiZmE5MTg1YmQ0Yzg4YWFkYTA2NDZhODIyOGQ1ZmIwYjAiLCJzZXJ2aWNlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImVmYWJlciJ9.nGEh672PQr72b09jtlSOl38T-Yn29FHkNu08YIUOS-U" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" -H "Accept: */*" -H "Referer: http://10.50.11.195:8000/" -H "Cookie: io=mtOV3Pp4WbRjQWVgAAA3" -H "Connection: keep-alive" --compressed

This is Call Failed
