### ISSUE TITLE
Device manager stopped listing devices and templates (kubernetes)

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#423]
On a kubernetes environment, for some reason, after a while device manager stopped replying the GUI with devices and templates configuration data.

All calls to the service result in a 500 error being returned. After a forced restart of the service everything seemed to be working again.

Service logs for such failed calls follow:

```
[2018-04-10 19:13:53,998] ERROR in app: Exception on /device [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "devices" does not exist
LINE 2: FROM devices 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 586, in flask_get_devices
    result = DeviceHandler.get_devices(request)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 190, in get_devices
    page = db.session.query(Device).paginate(**pagination)
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2726, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "devices" does not exist
LINE 2: FROM devices 
             ^
 [SQL: 'SELECT devices.id AS devices_id, devices.label AS devices_label, devices.created AS devices_created, devices.updated AS devices_updated, devices.persistence AS devices_persistence \nFROM devices \n LIMIT %(param_1)s OFFSET %(param_2)s'] [parameters: {'param_1': 1000, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
10.32.0.7 - - [10/Apr/2018:19:13:53 +0000] "GET /device?page_size=1000 HTTP/1.1" 500 25 "http://10.50.11.32/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
[2018-04-10 19:13:54,804] ERROR in app: Exception on /template [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "templates" does not exist
LINE 3: FROM templates 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/DeviceManager/TemplateHandler.py", line 224, in flask_get_templates
    result = TemplateHandler.get_templates(request)
  File "/usr/src/app/DeviceManager/TemplateHandler.py", line 64, in get_templates
    error_out=False)
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2726, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "templates" does not exist
LINE 3: FROM templates 
             ^
 [SQL: 'SELECT anon_1.templates_id AS anon_1_templates_id, anon_1.templates_label AS anon_1_templates_label, anon_1.templates_created AS anon_1_templates_created, anon_1.templates_updated AS anon_1_templates_updated, attrs_1.id AS attrs_1_id, attrs_1.label AS attrs_1_label, attrs_1.created AS attrs_1_created, attrs_1.updated AS attrs_1_updated, attrs_1.type AS attrs_1_type, attrs_1.value_type AS attrs_1_value_type, attrs_1.static_value AS attrs_1_static_value, attrs_1.template_id AS attrs_1_template_id, attrs_1.parent_id AS attrs_1_parent_id \nFROM (SELECT templates.id AS templates_id, templates.label AS templates_label, templates.created AS templates_created, templates.updated AS templates_updated \nFROM templates \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN attrs AS attrs_1 ON anon_1.templates_id = attrs_1.template_id'] [parameters: {'param_1': 20, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
10.32.0.7 - - [10/Apr/2018:19:13:54 +0000] "GET /template HTTP/1.1" 500 25 "http://10.50.11.32/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
[2018-04-10 19:13:54,817] ERROR in app: Exception on /device [GET]
```

**Comment by ericbaum** [comment]
This error originates from a prior failure on the PostgreSQL cluster where one of the nodes died and the access to the leader became corrupted until a new leader was assigned.

The log for the postgres error can be seen below:


```

2018-04-10 17:55:31,426 WARNING: Connection dropped: outstanding heartbeat ping not received
2018-04-10 17:55:31,427 WARNING: Transition to CONNECTING
2018-04-10 17:55:31,428 INFO: Zookeeper connection lost
2018-04-10 17:55:31,599 INFO: Connecting to zk-client:2181
2018-04-10 17:55:34.894 27 LOG {ticks: 90, maint: 0, retry: 0}
2018-04-10 17:55:40,823 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kazoo/retry.py", line 123, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/patroni/dcs/zookeeper.py", line 148, in _inner_load_cluster
    nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
  File "/usr/local/lib/python3.4/dist-packages/patroni/dcs/zookeeper.py", line 132, in get_children
    return self._client.get_children(key, watch)
  File "/usr/local/lib/python3.4/dist-packages/kazoo/client.py", line 1079, in get_children
    return self.get_children_async(path, watch, include_data).get()
  File "/usr/local/lib/python3.4/dist-packages/kazoo/handlers/utils.py", line 72, in get
    raise self._exception
kazoo.exceptions.SessionExpiredError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/patroni/dcs/zookeeper.py", line 196, in _load_cluster
    self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python3.4/dist-packages/kazoo/client.py", line 273, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/kazoo/retry.py", line 136, in __call__
    raise RetryFailedError("Exceeded retry deadline")
kazoo.retry.RetryFailedError: Exceeded retry deadline
2018-04-10 17:55:40,827 ERROR: Error communicating with DCS
waiting for server to shut down....2018-04-10 17:55:41.353 27 ERROR connection error: PQsendQuery
2018-04-10 17:55:41.353 27 ERROR libpq: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
2018-04-10 17:55:41.353 27 WARNING dojot_auth: default timeout
2018-04-10 17:55:41.354 27 ERROR connection error: PQsendQuery
2018-04-10 17:55:41.354 27 ERROR libpq: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
2018-04-10 17:55:41.354 27 WARNING kong: default timeout
2018-04-10 17:55:41.354 27 ERROR connection error: PQsendQuery
2018-04-10 17:55:41.354 27 ERROR libpq: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
2018-04-10 17:55:41.354 27 WARNING dojot_devm: default timeout
....2018-04-10 17:55:45.171 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:45.171 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:45.171 27 WARNING dojot_devm: default reconnect
....2018-04-10 17:55:49.584 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:49.584 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:49.584 27 WARNING kong: default reconnect
..2018-04-10 17:55:51,623 WARNING: Connection dropped: socket connection error: Name or service not known
.2018-04-10 17:55:52,346 INFO: Connecting to zk-client:2181
..2018-04-10 17:55:54.602 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:54.602 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:54.602 27 WARNING dojot_devm: default reconnect
2018-04-10 17:55:54.602 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:54.603 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:54.603 27 WARNING kong: default reconnect
2018-04-10 17:55:54.605 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:54.605 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:54.605 27 WARNING dojot_auth: default reconnect
2018-04-10 17:55:54.614 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:54.614 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:54.616 27 ERROR connection error: PQconnectPoll
2018-04-10 17:55:54.616 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:55:54.616 27 WARNING postgres: default timeout
.........2018-04-10 17:56:03.083 27 ERROR connection error: PQconnectPoll
2018-04-10 17:56:03.083 27 ERROR libpq: FATAL:  the database system is shutting down
2018-04-10 17:56:03.083 27 WARNING dojot_auth: default reconnect
..2018-04-10 17:56:04.896 27 LOG {ticks: 18, maint: 0, retry: 0}
..2018-04-10 17:56:07,368 WARNING: Connection dropped: socket connection error: Name or service not known
.2018-04-10 17:56:08,131 INFO: Connecting to zk-client:2181
2018-04-10 17:56:08,143 WARNING: Session has expired
2018-04-10 17:56:08,143 INFO: Zookeeper session lost, state: EXPIRED_SESSION
.2018-04-10 17:56:08,966 INFO: Connecting to zk-client:2181
2018-04-10 17:56:08,976 INFO: Zookeeper connection established, state: CONNECTED
...2018-04-10 17:56:11,979 CRIT reaped unknown pid 56)
 done
server stopped
2018-04-10 17:56:12,906 CRIT reaped unknown pid 57)
2018-04-10 17:56:12,927 INFO: closed patroni connection to the postgresql cluster
2018-04-10 17:56:13,002 INFO: postmaster pid=30048
2018-04-10 17:56:13 UTC [30048]: [1-1] 5accfabd.7560 0     LOG:  redirecting log output to logging collector process
2018-04-10 17:56:13 UTC [30048]: [2-1] 5accfabd.7560 0     HINT:  Future log output will appear in directory "../pg_log".
localhost:5432 - accepting connections
localhost:5432 - accepting connections
2018-04-10 17:56:14,141 INFO: demoted self because DCS is not accessible and i was a leader
2018-04-10 17:56:14,145 WARNING: Loop time exceeded, rescheduling immediately.
2018-04-10 17:56:14,158 INFO: establishing a new patroni connection to the postgres cluster
2018-04-10 17:56:14,175 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:14,175 INFO: does not have lock
2018-04-10 17:56:14,185 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:56:14,199 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:14,199 INFO: changing primary_conninfo and restarting in progress
2018-04-10 17:56:14,206 INFO: rewind flag is set
waiting for server to shut down....2018-04-10 17:56:14,238 CRIT reaped unknown pid 30048)
2018-04-10 17:56:14,239 CRIT reaped unknown pid 30050)
2018-04-10 17:56:15.173 27 ERROR connection error: PQconnectStart
2018-04-10 17:56:15.173 27 ERROR libpq: could not connect to server: No such file or directory
		Is the server running locally and accepting
		connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2018-04-10 17:56:15.173 27 WARNING dojot_devm: default reconnect
 done
server stopped
2018-04-10 17:56:15,528 INFO: running pg_rewind from user=postgres host=10.42.0.2 port=5432 dbname=postgres sslmode=prefer sslcompression=1
servers diverged at WAL position 0/640005A0 on timeline 1
rewinding from last common checkpoint at 0/640004F8 on timeline 1
2018-04-10 17:56:19.589 27 ERROR connection error: PQconnectStart
2018-04-10 17:56:19.590 27 ERROR libpq: could not connect to server: No such file or directory
		Is the server running locally and accepting
		connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2018-04-10 17:56:19.590 27 WARNING kong: default reconnect
2018-04-10 17:56:24,188 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:24,196 INFO: changing primary_conninfo and restarting in progress
Done!
2018-04-10 17:56:25,612 INFO: closed patroni connection to the postgresql cluster
2018-04-10 17:56:25,679 INFO: postmaster pid=30077
2018-04-10 17:56:25 UTC [30077]: [1-1] 5accfac9.757d 0     LOG:  redirecting log output to logging collector process
2018-04-10 17:56:25 UTC [30077]: [2-1] 5accfac9.757d 0     HINT:  Future log output will appear in directory "../pg_log".
localhost:5432 - accepting connections
localhost:5432 - accepting connections
2018-04-10 17:56:26,853 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:26,854 INFO: does not have lock
2018-04-10 17:56:26,854 INFO: establishing a new patroni connection to the postgres cluster
2018-04-10 17:56:26,880 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:56:33.106 27 ERROR dojot_auth: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:56:34.899 27 LOG {ticks: 0, maint: 0, retry: 0}
2018-04-10 17:56:36,841 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:36,842 INFO: does not have lock
2018-04-10 17:56:36,845 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:56:41.371 27 LOG dojot_auth: pgq version ok: 3.2.6
2018-04-10 17:56:41.376 27 LOG dojot_devm: pgq version ok: 3.2.6
2018-04-10 17:56:41.377 27 LOG kong: pgq version ok: 3.2.6
2018-04-10 17:56:45.183 27 ERROR dojot_devm: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:56:46,840 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:46,840 INFO: does not have lock
2018-04-10 17:56:46,846 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:56:49.601 27 ERROR kong: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:56:53.116 27 ERROR dojot_auth: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:56:56,841 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:56:56,842 INFO: does not have lock
2018-04-10 17:56:56,845 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:57:04.900 27 LOG {ticks: 72, maint: 3, retry: 0}
2018-04-10 17:57:05.197 27 ERROR dojot_devm: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:06,841 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:57:06,841 INFO: does not have lock
2018-04-10 17:57:06,844 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:57:09.612 27 ERROR kong: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:13.129 27 ERROR dojot_auth: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:16,840 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:57:16,841 INFO: does not have lock
2018-04-10 17:57:16,843 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:57:25.212 27 ERROR dojot_devm: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:26,842 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:57:26,842 INFO: does not have lock
2018-04-10 17:57:26,845 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:57:29.625 27 ERROR kong: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:33.140 27 ERROR dojot_auth: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:34.901 27 LOG {ticks: 90, maint: 0, retry: 0}
2018-04-10 17:57:36,840 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:57:36,841 INFO: does not have lock
2018-04-10 17:57:36,844 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:57:45.225 27 ERROR dojot_devm: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:46,841 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:57:46,841 INFO: does not have lock
2018-04-10 17:57:46,844 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:57:49.635 27 ERROR kong: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:53.152 27 ERROR dojot_auth: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:57:56,841 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:57:56,841 INFO: does not have lock
2018-04-10 17:57:56,844 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:58:04.902 27 LOG {ticks: 90, maint: 0, retry: 0}
2018-04-10 17:58:05.237 27 ERROR dojot_devm: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:58:06,840 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:58:06,840 INFO: does not have lock
2018-04-10 17:58:06,847 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:58:09.644 27 ERROR kong: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:58:13.166 27 ERROR dojot_auth: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:58:16,841 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:58:16,841 INFO: does not have lock
2018-04-10 17:58:16,848 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:58:25.248 27 ERROR dojot_devm: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
2018-04-10 17:58:26,840 INFO: Lock owner: postgres-1; I am postgres-0
2018-04-10 17:58:26,841 INFO: does not have lock
2018-04-10 17:58:26,843 INFO: no action.  i am a secondary and i am following a leader
2018-04-10 17:58:29.656 27 ERROR kong: ERROR:  cannot execute LOCK TABLE during recovery
	CONTEXT:  SQL statement "lock table pgq.retry_queue in share update exclusive mode"
	PL/pgSQL function pgq.maint_retry_events() line 20 at SQL statement
```

**Comment by ericbaum** [comment]
The issue  is related to this repeating message on ZooKeeper:

```
2018-04-09 13:20:11,905 [myid:2] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@188] - Too many connections from /10.46.0.5 - max is 60
```

Where the presented IP is associated with the data broker POD.
