### ISSUE TITLE
For an invalid template composition, a 500 internal error is returned

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#451]
Logs for the failure:
```
172.18.0.22 - - [20/Apr/2018:19:15:37 +0000] "GET /template HTTP/1.1" 200 14049 "http://10.50.11.195:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
[2018-04-20 19:15:56,859] ERROR in app: Exception on /device [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 340, in _get_value_for_key
    return obj[key]
TypeError: 'DeviceAttr' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.IntegrityError: Template (9) cannot be added to device (17dc93) as it has standing attribute conflicts


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 707, in flask_create_device
    result = DeviceHandler.create_device(request)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 308, in create_device
    full_device = serialize_full_device(orm_device, tenant)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 44, in serialize_full_device
    data['attrs'][template.id] = attr_list_schema.dump(template.attrs)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 428, in dump
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 124, in serialize
    for idx, d in enumerate(obj)]
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 124, in <listcomp>
    for idx, d in enumerate(obj)]
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/fields.py", line 239, in serialize
    value = self.get_value(obj, attr, accessor=accessor)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/fields.py", line 182, in get_value
    return accessor_func(obj, check_key, default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 371, in get_attribute
    return utils.get_value(obj, attr, default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 327, in get_value
    return _get_value_for_keys(obj, key.split('.'), default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 332, in _get_value_for_keys
    return _get_value_for_key(obj, keys[0], default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 343, in _get_value_for_key
    return getattr(obj, key)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 623, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 747, in _emit_lazyload
    result = q(session).params(**params).all()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 434, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 336, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2243, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2369, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2333, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 507, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/dependency.py", line 1082, in process_saves
    secondary_update, secondary_delete)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/dependency.py", line 1126, in _run_crud
    connection.execute(statement, secondary_insert)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) Template (9) cannot be added to device (17dc93) as it has standing attribute conflicts
 [SQL: 'INSERT INTO device_template (device_id, template_id) VALUES (%(device_id)s, %(template_id)s)'] [parameters: ({'device_id': '17dc93', 'template_id': 8}, {'device_id': '17dc93', 'template_id': 9}, {'device_id': '17dc93', 'template_id': 10}, {'device_id': '17dc93', 'template_id': 11})] (Background on this error at: http://sqlalche.me/e/gkpj)
172.18.0.22 - - [20/Apr/2018:19:15:56 +0000] "POST /device HTTP/1.1" 500 30 "http://10.50.11.195:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
[2018-04-20 19:16:48,346] ERROR in app: Exception on /device [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 340, in _get_value_for_key
    return obj[key]
TypeError: 'DeviceAttr' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.IntegrityError: Template (9) cannot be added to device (211541) as it has standing attribute conflicts


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 707, in flask_create_device
    result = DeviceHandler.create_device(request)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 308, in create_device
    full_device = serialize_full_device(orm_device, tenant)
  File "/usr/src/app/DeviceManager/DeviceHandler.py", line 44, in serialize_full_device
    data['attrs'][template.id] = attr_list_schema.dump(template.attrs)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 428, in dump
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 124, in serialize
    for idx, d in enumerate(obj)]
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 124, in <listcomp>
    for idx, d in enumerate(obj)]
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/fields.py", line 239, in serialize
    value = self.get_value(obj, attr, accessor=accessor)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/fields.py", line 182, in get_value
    return accessor_func(obj, check_key, default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 371, in get_attribute
    return utils.get_value(obj, attr, default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 327, in get_value
    return _get_value_for_keys(obj, key.split('.'), default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 332, in _get_value_for_keys
    return _get_value_for_key(obj, keys[0], default)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/utils.py", line 343, in _get_value_for_key
    return getattr(obj, key)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 623, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 747, in _emit_lazyload
    result = q(session).params(**params).all()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 434, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 336, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2243, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2369, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2333, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 507, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/dependency.py", line 1082, in process_saves
    secondary_update, secondary_delete)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/dependency.py", line 1126, in _run_crud
    connection.execute(statement, secondary_insert)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) Template (9) cannot be added to device (211541) as it has standing attribute conflicts
 [SQL: 'INSERT INTO device_template (device_id, template_id) VALUES (%(device_id)s, %(template_id)s)'] [parameters: ({'device_id': '211541', 'template_id': 8}, {'device_id': '211541', 'template_id': 9}, {'device_id': '211541', 'template_id': 10}, {'device_id': '211541', 'template_id': 11})] (Background on this error at: http://sqlalche.me/e/gkpj)
172.18.0.22 - - [20/Apr/2018:19:16:48 +0000] "POST /device HTTP/1.1" 500 30 "http://10.50.11.195:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
172.18.0.22 - - [20/Apr/2018:19:16:50 +0000] "GET /template HTTP/1.1" 200 14049 "http://10.50.11.195:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
172.18.0.22 - - [20/Apr/2018:19:16:53 +0000] "GET /template HTTP/1.1" 200 14049 "http://10.50.11.195:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
```

**Comment by giovannicuriel** [comment]
I was not able to reproduce this error with recent releases. Might be already solved :tada:
