### ISSUE TITLE
Status updates stop working for selected tenants

### ISSUE THREAD

**Issue by mmagr** [dojot/dojot#468]
Sometimes, a tenant's status information consumer will fail, leading to no further status updates being issued for the devices that belong to that tenant.

Device manager logs, occasionally display the following, prior to the failure to update.

```
will set testf:e39adc online for 600.0sException in thread Thread-118:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-148:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-44:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-74:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-280:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-346:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-109:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-370:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-313:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-332:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-299:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 160, in iterate
    self.collect(partition)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 184, in collect
    exp = float(self.redis.get(device).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: terminating connection due to administrator command
SSL connection has been closed unexpectedly


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gevent/threading.py", line 191, in run
    super(Thread, self).run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 90, in run
    self.set_online(tenant, deviceid, message.partition, metadata.get('exp', None))
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 134, in set_online
    exp = StatusMonitor.default_exp(tenant, device)
  File "/usr/src/app/DeviceManager/StatusMonitor.py", line 120, in default_exp
    db.session.execute("SET search_path TO %s" % tenant)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command
SSL connection has been closed unexpectedly
 [SQL: 'SET search_path TO testf'] (Background on this error at: http://sqlalche.me/e/e3q8)

[2018-05-09 13:27:46,754] ERROR in app: Exception on /template [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "templates" does not exist
LINE 3: FROM templates ORDER BY templates.label 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/DeviceManager/TemplateHandler.py", line 268, in flask_get_templates
    result = TemplateHandler.get_templates(request)
  File "/usr/src/app/DeviceManager/TemplateHandler.py", line 93, in get_templates
    page = db.session.query(DeviceTemplate).order_by(sortBy).paginate(**pagination)
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 491, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2726, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "templates" does not exist
LINE 3: FROM templates ORDER BY templates.label 
             ^
 [SQL: 'SELECT anon_1.templates_id AS anon_1_templates_id, anon_1.templates_label AS anon_1_templates_label, anon_1.templates_created AS anon_1_templates_created, anon_1.templates_updated AS anon_1_templates_updated, attrs_1.id AS attrs_1_id, attrs_1.label AS attrs_1_label, attrs_1.created AS attrs_1_created, attrs_1.updated AS attrs_1_updated, attrs_1.type AS attrs_1_type, attrs_1.value_type AS attrs_1_value_type, attrs_1.static_value AS attrs_1_static_value, attrs_1.template_id AS attrs_1_template_id, attrs_1.parent_id AS attrs_1_parent_id \nFROM (SELECT templates.id AS templates_id, templates.label AS templates_label, templates.created AS templates_created, templates.updated AS templates_updated \nFROM templates ORDER BY templates.label \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN attrs AS attrs_1 ON anon_1.templates_id = attrs_1.template_id ORDER BY anon_1.templates_label'] [parameters: {'param_1': 20, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)

will set testf:627203 online for 600.0s

```

**Comment by giovannicuriel** [comment]
We don't have status updates generated by device manager anymore :fireworks: :
