### ISSUE TITLE
EJBCA fails during boot

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/dojot#561]
Using baseline 0.3.0-nightly20180626, EJBCA doesn't not come up cleanly.
The last lines from the log are:

```
ejbca_1                 | /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is 
strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings                                                                                             
ejbca_1                 |   InsecureRequestWarning)                                                                                                                                          
ejbca_1                 | Traceback (most recent call last):                                                                                                                                 
ejbca_1                 |   File "/var/www/RESTmain.py", line 244, in <module>                                                                                                               
ejbca_1                 |     initicalConf()                                                                                                                                                 ejbca_1                 |   File "/var/www/ejbcaUtils.py", line 117, in initicalConf                                                                                                         
ejbca_1                 | Chances are the server is not ready yet.                                                                                                                           
ejbca_1                 | Will retry in 30sec                                                                                                                                                ejbca_1                 |     loadWSDLbase()                                                                                                                                                 
ejbca_1                 |   File "/var/www/ejbcaUtils.py", line 65, in loadWSDLbase                                                                                                          ejbca_1                 |     ejbcaWSDLbase.options(raw_response=True)                                                                                                                       
ejbca_1                 | AttributeError: 'Client' object has no attribute 'options'                                                                                                         
^CERROR: Aborting.   
```

Also, iotagent-mosca doesn't come up even if TLS is disable. EJBCA should not be mandatory for iotagent-mosca if TLS is not used.

**Comment by betefaber** [comment]
Test OK.

> ejbca_1                       | waiting for new messages
> ejbca_1                       | Chances are the server is not ready yet.
> ejbca_1                       | Will retry in 30sec
> ejbca_1                       |  * Serving Flask app "RESTmain" (lazy loading)
> ejbca_1                       |  * Environment: production
> ejbca_1                       |    WARNING: Do not use the development server in a production environment.
> ejbca_1                       |    Use a production WSGI server instead.
> ejbca_1                       |  * Debug mode: off
> ejbca_1                       |  * Running on http://0.0.0.0:5583/ (Press CTRL+C to quit)
