### ISSUE TITLE
[GUI] After create the user, does not display the user's card

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#618]
After saving the user, does not display the user's card. Need to refresh the page (F5).

**Steps to reproduce the problem:**

1. click "New User"
2. fill in the fields
3. click Create

**Actual result:** 
- internal error in user creation

![screenshot_1](https://user-images.githubusercontent.com/37310063/43961129-807e9780-9c8a-11e8-954f-f1fae8fe3119.png)

> 2018-08-10 14:03:37,869 - INFO - User b1 created by admin
> 2018-08-10 14:03:37,869 - INFO - <User (transient 140349163510864)>
> 2018-08-10 14:03:37,940 - INFO - user b1 added to group admin by admin
> [2018-08-10 14:03:38,899] ERROR in app: Exception on /user [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
>     result = crud.create_user(db.session, user, requester)
>   File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
>     pwdc.create_password_set_request(db_session, new_user)
>   File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
>     send_mail(user.email, 'Account Activation', html)
>   File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
>     s = smtplib.SMTP(conf.emailHost, conf.emailPort)
>   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
>     raise err # pylint:disable=raising-bad-type
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
>     sock.connect(sa)
>   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
>     raise error(result, strerror(result))
> OSError: [Errno 99] Cannot assign requested address
> 2018-08-10 14:03:38,899 - ERROR - Exception on /user [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
>     result = crud.create_user(db.session, user, requester)
>   File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
>     pwdc.create_password_set_request(db_session, new_user)
>   File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
>     send_mail(user.email, 'Account Activation', html)
>   File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
>     s = smtplib.SMTP(conf.emailHost, conf.emailPort)
>   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
>     raise err # pylint:disable=raising-bad-type
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
>     sock.connect(sa)
>   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
>     raise error(result, strerror(result))
> OSError: [Errno 99] Cannot assign requested address
> 172.18.0.18 - - [10/Aug/2018:14:03:38 +0000] "POST /user HTTP/1.1" 500 291 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36"
> 

- the created user's card is not displayed

**Expected behavior**: user must be created and his card must be displayed
**Affected Version**: v0.3.0-beta1 (0.3.0-nightly_20180807)

**Comment by betefaber** [comment]
This error happens if the **smtp** port is locked.
Otherwise, the user is created and the email to register the password is sent.
