### ISSUE TITLE
User creation failed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#661]
**Steps to reproduce the problem:**

- via GUI:

1. Click on "New user"
2. Fill the form
3. Click on "Create"

![add_user_gui](https://user-images.githubusercontent.com/37310063/45494977-afd06a80-b748-11e8-8683-c08fdfd59d1c.png)

- via API:

![add_user_api](https://user-images.githubusercontent.com/37310063/45495008-c24aa400-b748-11e8-88de-ab0882457151.png)

**Affected Version:** 0.3.0-nightly_20180912

**Comment by betefaber** [comment]
Auth log:

> 2018-09-13 14:54:00,050 - INFO - User bete created by admin
2018-09-13 14:54:00,050 - INFO - <User (transient 139782051738568)>
Consumer already exists
2018-09-13 14:54:00,115 - INFO - user bete added to group admin by admin
[2018-09-13 14:54:00,401] ERROR in app: Exception on /user [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
    result = crud.create_user(db.session, user, requester)
  File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
    pwdc.create_password_set_request(db_session, new_user)
  File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
    send_mail(user.email, 'Account Activation', html)
  File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
    s = smtplib.SMTP(conf.emailHost, conf.emailPort)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
    raise err # pylint:disable=raising-bad-type
  File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
    raise error(result, strerror(result))
OSError: [Errno 99] Cannot assign requested address
2018-09-13 14:54:00,401 - ERROR - Exception on /user [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
    result = crud.create_user(db.session, user, requester)
  File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
    pwdc.create_password_set_request(db_session, new_user)
  File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
    send_mail(user.email, 'Account Activation', html)
  File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
    s = smtplib.SMTP(conf.emailHost, conf.emailPort)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
    raise err # pylint:disable=raising-bad-type
  File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
    raise error(result, strerror(result))
OSError: [Errno 99] Cannot assign requested address
172.25.0.17 - - [13/Sep/2018:14:54:00 +0000] "POST /user HTTP/1.1" 500 291 "-" "PostmanRuntime/7.1.1"
