### ISSUE TITLE
Flowbroker was broken

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#664]
A flow with a geo node was created. If a data is published to the device without the geo attribute, the flowbroker breaks.

**log flowbroker:**

> [ingestor] got new device event: { metadata: { deviceid: '7db27e', tenant: 'admin', timestamp: 1537187935573 },
>   attrs: { int: 60 } }
> [executor] will handle node geofence
> debug: Executing geo node...
> debug: ... geo node was not successfully executed.
> error: Message has no geographic position attached.
> [executor] Node execution failed. Error: Message has no geographic position attached. Aborting flow 7619b591-b718-4d92-9c8c-362ae2f02c00.
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> TypeError: Cannot read property 'hasOwnProperty' of null
>     at /opt/flowbroker/orchestrator/node_modules/geolib/dist/geolib.js:119:34
>     at Array.every (<anonymous>)
>     at getKey (/opt/flowbroker/orchestrator/node_modules/geolib/dist/geolib.js:114:32)
>     at Geolib.getKeys (/opt/flowbroker/orchestrator/node_modules/geolib/dist/geolib.js:126:29)
>     at Geolib.getLon (/opt/flowbroker/orchestrator/node_modules/geolib/dist/geolib.js:159:101)
>     at Geolib.longitude (/opt/flowbroker/orchestrator/node_modules/geolib/dist/geolib.js:164:32)
>     at Geolib.isPointInside (/opt/flowbroker/orchestrator/node_modules/geolib/dist/geolib.js:632:60)
>     at DataHandler.handleMessage (/opt/flowbroker/orchestrator/src/nodes/geo/index.js:86:28)
>     at Executor.hop (/opt/flowbroker/orchestrator/src/executor.js:49:21)
>     at channel.consume (/opt/flowbroker/orchestrator/src/amqp.js:106:9)
>     at Channel.BaseChannel.dispatchMessage (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:466:12)
>     at Channel.BaseChannel.handleDelivery (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:475:15)
>     at emitOne (events.js:116:13)
>     at Channel.emit (events.js:211:7)
>     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:263:10
>     at Channel.content [as handleMessage] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:316:9)
> 

**Affected Version**: 0.3.0-nightly_20180912

**Comment by betefaber** [comment]
Test OK.

> [ingestor] got new device event: { metadata: { deviceid: '97d9bb', tenant: 'admin', timestamp: 1538073642995 },
>   attrs: { int: 8 } }
> [executor] will handle node geofence
> [executor] will handle node geofence
> [executor] will handle node switch
> [executor] hop (switch) result: [null,{"payload":{"int":8}}]
> debug: Executing geo node...
> debug: ... geo node was not successfully executed.
> error: Message has no geographic position attached.
> [executor] Node execution failed. Error: Message has no geographic position attached. Aborting flow 6a9b969d-1f66-422e-a39c-ca709b5315be.
> debug: Executing geo node...
> debug: ... geo node was not successfully executed.
> error: Message has no geographic position attached.
> [executor] Node execution failed. Error: Message has no geographic position attached. Aborting flow 6a9b969d-1f66-422e-a39c-ca709b5315be.
> debug: Executing switch node...
>
