### ISSUE TITLE
[GUI] Error in user creation after alert message

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#667]
The user is not created, even if the data has been filled out correctly.

**Steps to reproduce the problem:**

1. Click "New User"
2. Click "CREATE". The "Invalid email" alert message is displayed.
3. Fill in the fields:
 - Username: bete
 - Name: bete
 - Email: efaber@cpqd.com.br
 - Confirm Email: efaber@cpqd.com.br
 - Profile: Administrator
4. Click "CREATE"

![missingservice](https://user-images.githubusercontent.com/37310063/45646494-e7694a80-ba99-11e8-89bf-4a0599c4c532.png)

**Actual result:** The user is not created. The "Missing service" message appears, but the Service field does not exist on the form.

**Expected behavior**: The user should be created.

**Affected Version**: 0.3.0-nightly_20180912

**Comment by betefaber** [comment]
Test NOK.

![image](https://user-images.githubusercontent.com/37310063/45824192-d3a22c00-bcc5-11e8-981a-d3e442efcc52.png)

**log auth:**

> 2018-09-20 14:00:39,290 - INFO - User bete created by admin
> 2018-09-20 14:00:39,290 - INFO - <User (transient 139713503278528)>
> Consumer already exists
> 2018-09-20 14:00:39,371 - INFO - user bete added to group admin by admin
> [2018-09-20 14:00:39,387] ERROR in app: Exception on /user [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
>     result = crud.create_user(db.session, user, requester)
>   File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
>     pwdc.create_password_set_request(db_session, new_user)
>   File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
>     send_mail(user.email, 'Account Activation', html)
>   File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
>     s = smtplib.SMTP(conf.emailHost, conf.emailPort)
>   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
>     raise err # pylint:disable=raising-bad-type
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
>     sock.connect(sa)
>   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
>     raise error(result, strerror(result))
> OSError: [Errno 99] Cannot assign requested address
> 2018-09-20 14:00:39,387 - ERROR - Exception on /user [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/src/app/auth/webRoutes.py", line 44, in create_user
>     result = crud.create_user(db.session, user, requester)
>   File "/usr/src/app/auth/controller/CRUDController.py", line 134, in create_user
>     pwdc.create_password_set_request(db_session, new_user)
>   File "/usr/src/app/auth/controller/PasswordController.py", line 259, in create_password_set_request
>     send_mail(user.email, 'Account Activation', html)
>   File "/usr/src/app/auth/utils/emailUtils.py", line 17, in send_mail
>     s = smtplib.SMTP(conf.emailHost, conf.emailPort)
>   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 99, in create_connection
>     raise err # pylint:disable=raising-bad-type
>   File "/usr/local/lib/python3.6/site-packages/gevent/socket.py", line 86, in create_connection
>     sock.connect(sa)
>   File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 307, in connect
>     raise error(result, strerror(result))
> OSError: [Errno 99] Cannot assign requested address
> 192.168.48.21 - - [20/Sep/2018:14:00:39 +0000] "POST /user HTTP/1.1" 500 291 "http://10.4.1.41:8000/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36"
