### ISSUE TITLE
Persister initialization failed

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#824]
> $ sudo docker-compose logs -f persister
> Attaching to dojot_persister_1
> persister_1                   | [03/01/19 - 11:21:53] |persister| INFO: db initialized
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Could not create producer
> persister_1                   | [03/01/19 - 11:21:53] |consumer| INFO: Creating consumer on ['kafka:9092'] on group dojotmodulepython0c2dbbd3-165a-47af-abed-f6748ff2512f and topic []
> persister_1                   | [03/01/19 - 11:21:53] |consumer| INFO: Consumer created []
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Creating channel for subject: dojot.tenancy
> persister_1                   | [03/01/19 - 11:21:53] |messenger| DEBUG: tenants in create channel: []
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Bootstraping tenant internal for subject dojot.tenancy
> persister_1                   | [03/01/19 - 11:21:53] |messenger| DEBUG: Global: True, mode: rw
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Requesting topic for dojot.tenancy@internal
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Got topics: "da85bb49-a0d4-464c-b8cc-8eb9af6c4c52"
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Got topic for subject dojot.tenancy and tenant internal: da85bb49-a0d4-464c-b8cc-8eb9af6c4c52
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Telling consumer to subscribe to new topic
> persister_1                   | [03/01/19 - 11:21:53] |consumer| INFO: Got a new topic to subscribe: da85bb49-a0d4-464c-b8cc-8eb9af6c4c52
> persister_1                   | [03/01/19 - 11:21:53] |consumer| INFO: Current topic list: []
> persister_1                   | [03/01/19 - 11:21:53] |consumer| DEBUG: Current subscriptions: {'da85bb49-a0d4-464c-b8cc-8eb9af6c4c52'}
> persister_1                   | [03/01/19 - 11:21:53] |consumer| INFO: Subscribed to topic da85bb49-a0d4-464c-b8cc-8eb9af6c4c52
> persister_1                   | [03/01/19 - 11:21:53] |consumer| DEBUG: Current topic list: ['da85bb49-a0d4-464c-b8cc-8eb9af6c4c52']
> persister_1                   | [03/01/19 - 11:21:53] |messenger| DEBUG: Starting consumer thread
> persister_1                   | [03/01/19 - 11:21:53] |consumer| DEBUG: Now running consumer for topics: ['da85bb49-a0d4-464c-b8cc-8eb9af6c4c52']
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Adding a producer topic.
> persister_1                   | [03/01/19 - 11:21:53] |messenger| INFO: Registering new callback for subject dojot.tenancy and event message
> persister_1                   | [03/01/19 - 11:21:53] |auth    | DEBUG: Retrieving list of tenants from auth...
> persister_1                   | [03/01/19 - 11:21:53] |auth    | WARNING: Connection error retrieving list of tenants: HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb9242b160>: Failed to establish a new connection: [Errno 111] Connection refused',))
> persister_1                   | [03/01/19 - 11:21:53] |auth    | WARNING: Sleeping for 5 before trying again.
> persister_1                   | [03/01/19 - 11:21:58] |auth    | WARNING: Retrying...
> persister_1                   | [03/01/19 - 11:21:58] |auth    | DEBUG: Retrieving list of tenants from auth...
> persister_1                   | [03/01/19 - 11:21:58] |auth    | WARNING: Connection error retrieving list of tenants: HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb9242be48>: Failed to establish a new connection: [Errno 111] Connection refused',))
> persister_1                   | [03/01/19 - 11:21:58] |auth    | WARNING: Sleeping for 5 before trying again.
> persister_1                   | [03/01/19 - 11:22:03] |auth    | WARNING: Retrying...
> persister_1                   | [03/01/19 - 11:22:03] |auth    | DEBUG: Retrieving list of tenants from auth...
> persister_1                   | [03/01/19 - 11:22:07] |auth    | WARNING: Connection error retrieving list of tenants: HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb91497f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
> persister_1                   | [03/01/19 - 11:22:07] |auth    | WARNING: Sleeping for 5 before trying again.
> persister_1                   | [03/01/19 - 11:22:12] |auth    | WARNING: Retrying...
> persister_1                   | [03/01/19 - 11:22:12] |auth    | WARNING: Tenant list request payload is still None.
> persister_1                   | [03/01/19 - 11:22:12] |messenger| ERROR: Cannot initialize messenger, as the list of tenants could not be retrieved.
> persister_1                   | [03/01/19 - 11:22:12] |messenger| ERROR: Bailing out.

**Affected Version:** 0.3.0-nightly20181227

**Comment by betefaber** [comment]
Test OK at baseline **training-20190122**.

The issue will be validated at the next baseline.

**Comment by betefaber** [comment]
Test OK.

> matheusr@vali:/opt/teste/current/docker-compose$ sudo docker-compose logs -f persister
> Attaching to dojot_persister_1
> persister_1                   | [19/02/19 - 12:12:38] |persister| DEBUG: Initializing persister...
> persister_1                   | [19/02/19 - 12:12:38] |persister| INFO: db initialized
> persister_1                   | [19/02/19 - 12:12:38] |persister| DEBUG: ... persister was successfully initialized.
> persister_1                   | [19/02/19 - 12:12:38] |persister| DEBUG: Initializing dojot messenger...
> persister_1                   | [19/02/19 - 12:12:38] |consumer| INFO: Creating a new Kafka consumer dojot-module-07441d5f-e1fb-4f6a-9e16-a41357d28cd8...
> persister_1                   | [19/02/19 - 12:12:38] |consumer| INFO: Configuration is:
> persister_1                   | [19/02/19 - 12:12:38] |consumer| INFO: {'group_id': 'persister-group', 'bootstrap_servers': ['kafka:9092']}
> persister_1                   | [19/02/19 - 12:12:38] |consumer| INFO: ... consumer created.
> persister_1                   | [19/02/19 - 12:12:38] |messenger| DEBUG: Creating consumer for tenancy messages...
> persister_1                   | [19/02/19 - 12:12:38] |messenger| INFO: Creating channel for subject: dojot.tenancy
> persister_1                   | [19/02/19 - 12:12:38] |messenger| DEBUG: tenants in create channel: []
> persister_1                   | [19/02/19 - 12:12:38] |messenger| INFO: Bootstraping tenant dojot-management for subject dojot.tenancy
> persister_1                   | [19/02/19 - 12:12:38] |messenger| DEBUG: Global: True, mode: r
> persister_1                   | [19/02/19 - 12:12:38] |messenger| INFO: Requesting topic for dojot.tenancy@dojot-management
> persister_1                   | [19/02/19 - 12:12:38] |topic_manager| DEBUG: Getting a topic for dojot.tenancy@dojot-management...
> persister_1                   | [19/02/19 - 12:12:38] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:12:38] |http_requester| DEBUG: Remaining attempts: 3
> persister_1                   | [19/02/19 - 12:12:47] |http_requester| DEBUG: Got an answer from HTTP endpoint.
> persister_1                   | [19/02/19 - 12:12:47] |http_requester| DEBUG: ... data retrieved from endpoint.
> persister_1                   | [19/02/19 - 12:12:47] |messenger| INFO: Got topics: "fc1c8c9d-2b14-40e1-846a-87b3665e61d8"
> persister_1                   | [19/02/19 - 12:12:47] |messenger| INFO: Got topic for subject dojot.tenancy and tenant dojot-management: fc1c8c9d-2b14-40e1-846a-87b3665e61d8
> persister_1                   | [19/02/19 - 12:12:47] |messenger| INFO: Telling consumer to subscribe to new topic
> persister_1                   | [19/02/19 - 12:12:47] |consumer| INFO: Got a new topic to subscribe: fc1c8c9d-2b14-40e1-846a-87b3665e61d8
> persister_1                   | [19/02/19 - 12:12:47] |messenger| INFO: Starting consumer thread...
> persister_1                   | [19/02/19 - 12:12:47] |consumer| DEBUG: Now running consumer for topics: ['fc1c8c9d-2b14-40e1-846a-87b3665e61d8']
> persister_1                   | [19/02/19 - 12:12:47] |messenger| INFO: ... consumer thread was successfully started.
> persister_1                   | [19/02/19 - 12:12:47] |consumer| DEBUG: Subscribing to a new list of topics...
> persister_1                   | [19/02/19 - 12:12:47] |messenger| DEBUG: ... consumer for tenancy messages was successfully created.
> persister_1                   | [19/02/19 - 12:12:47] |consumer| DEBUG: Holding off a bit before performing the subscription...
> persister_1                   | [19/02/19 - 12:12:47] |consumer| INFO: Creating a new Kafka consumer Persister...
> persister_1                   | [19/02/19 - 12:12:47] |consumer| INFO: Configuration is:
> persister_1                   | [19/02/19 - 12:12:47] |consumer| INFO: {'group_id': 'persister-group', 'bootstrap_servers': ['kafka:9092']}
> persister_1                   | [19/02/19 - 12:12:47] |consumer| INFO: ... consumer created.
> persister_1                   | [19/02/19 - 12:12:47] |messenger| INFO: Registering new callback for subject dojot.tenancy and event message
> persister_1                   | [19/02/19 - 12:12:47] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:12:47] |http_requester| DEBUG: Remaining attempts: 3
> persister_1                   | [19/02/19 - 12:12:49] |consumer| DEBUG: Ok, woke up just now.
> persister_1                   | [19/02/19 - 12:12:49] |consumer| DEBUG: ... no further changes in topic list.
> persister_1                   | [19/02/19 - 12:12:49] |consumer| DEBUG: Creating subscriptions...
> persister_1                   | [19/02/19 - 12:12:49] |consumer| INFO: Current topic list: ['fc1c8c9d-2b14-40e1-846a-87b3665e61d8']
> persister_1                   | [19/02/19 - 12:12:49] |consumer| DEBUG: Current subscriptions: {'fc1c8c9d-2b14-40e1-846a-87b3665e61d8'}
> persister_1                   | [19/02/19 - 12:12:49] |consumer| DEBUG: ... subscriptions created
> persister_1                   | [19/02/19 - 12:12:49] |consumer| DEBUG: ... successfully subscribed to new list of topics.
> persister_1                   | [19/02/19 - 12:12:50] |http_requester| WARNING: Connection error while retrieving data: HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efed8724400>: Failed to establish a new connection: [Errno 113] Host is unreachable',))
> persister_1                   | [19/02/19 - 12:12:50] |http_requester| WARNING: Sleeping for 5 before trying again.
> persister_1                   | [19/02/19 - 12:12:55] |http_requester| WARNING: Retrying...
> persister_1                   | [19/02/19 - 12:12:55] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:12:55] |http_requester| DEBUG: Remaining attempts: 2
> persister_1                   | [19/02/19 - 12:12:55] |http_requester| WARNING: Connection error while retrieving data: HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efed871bda0>: Failed to establish a new connection: [Errno 111] Connection refused',))
> persister_1                   | [19/02/19 - 12:12:55] |http_requester| WARNING: Sleeping for 5 before trying again.
> persister_1                   | [19/02/19 - 12:13:00] |http_requester| WARNING: Retrying...
> persister_1                   | [19/02/19 - 12:13:00] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:13:00] |http_requester| DEBUG: Remaining attempts: 1
> persister_1                   | [19/02/19 - 12:13:00] |http_requester| WARNING: Connection error while retrieving data: HTTPConnectionPool(host='auth', port=5000): Max retries exceeded with url: /admin/tenants (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efed8733908>: Failed to establish a new connection: [Errno 111] Connection refused',))
> persister_1                   | [19/02/19 - 12:13:00] |http_requester| WARNING: Sleeping for 5 before trying again.
> persister_1                   | [19/02/19 - 12:13:05] |http_requester| WARNING: Retrying...
> persister_1                   | [19/02/19 - 12:13:05] |http_requester| WARNING: Data request payload is still None.
> persister_1                   | [19/02/19 - 12:13:05] |messenger| ERROR: Cannot initialize messenger, as the list of tenants could not be retrieved.
> persister_1                   | [19/02/19 - 12:13:05] |messenger| ERROR: Bailing out.
> persister_1                   | Traceback (most recent call last):
> persister_1                   |   File "history/subscriber/persister.py", line 190, in <module>
> persister_1                   |     main()
> persister_1                   |   File "history/subscriber/persister.py", line 183, in main
> persister_1                   |     messenger.init()
> persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a4-py3.6.egg/dojot/module/messenger.py", line 114, in init
> persister_1                   |     raise UserWarning("Cannot initialize messenger")
> persister_1                   | UserWarning: Cannot initialize messenger
> persister_1                   | [19/02/19 - 12:13:09] |persister| DEBUG: Initializing persister...
> persister_1                   | [19/02/19 - 12:13:09] |persister| INFO: db initialized
> persister_1                   | [19/02/19 - 12:13:09] |persister| DEBUG: ... persister was successfully initialized.
> persister_1                   | [19/02/19 - 12:13:10] |persister| DEBUG: Initializing dojot messenger...
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: Creating a new Kafka consumer dojot-module-942dabaf-80db-48f4-932e-2cd3d8f1de10...
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: Configuration is:
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: {'group_id': 'persister-group', 'bootstrap_servers': ['kafka:9092']}
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: ... consumer created.
> persister_1                   | [19/02/19 - 12:13:10] |messenger| DEBUG: Creating consumer for tenancy messages...
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Creating channel for subject: dojot.tenancy
> persister_1                   | [19/02/19 - 12:13:10] |messenger| DEBUG: tenants in create channel: []
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Bootstraping tenant dojot-management for subject dojot.tenancy
> persister_1                   | [19/02/19 - 12:13:10] |messenger| DEBUG: Global: True, mode: r
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Requesting topic for dojot.tenancy@dojot-management
> persister_1                   | [19/02/19 - 12:13:10] |topic_manager| DEBUG: Getting a topic for dojot.tenancy@dojot-management...
> persister_1                   | [19/02/19 - 12:13:10] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:13:10] |http_requester| DEBUG: Remaining attempts: 3
> persister_1                   | [19/02/19 - 12:13:10] |http_requester| DEBUG: Got an answer from HTTP endpoint.
> persister_1                   | [19/02/19 - 12:13:10] |http_requester| DEBUG: ... data retrieved from endpoint.
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Got topics: "fc1c8c9d-2b14-40e1-846a-87b3665e61d8"
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Got topic for subject dojot.tenancy and tenant dojot-management: fc1c8c9d-2b14-40e1-846a-87b3665e61d8
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Telling consumer to subscribe to new topic
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: Got a new topic to subscribe: fc1c8c9d-2b14-40e1-846a-87b3665e61d8
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Starting consumer thread...
> persister_1                   | [19/02/19 - 12:13:10] |consumer| DEBUG: Now running consumer for topics: ['fc1c8c9d-2b14-40e1-846a-87b3665e61d8']
> persister_1                   | [19/02/19 - 12:13:10] |consumer| DEBUG: Subscribing to a new list of topics...
> persister_1                   | [19/02/19 - 12:13:10] |consumer| DEBUG: Holding off a bit before performing the subscription...
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: ... consumer thread was successfully started.
> persister_1                   | [19/02/19 - 12:13:10] |messenger| DEBUG: ... consumer for tenancy messages was successfully created.
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: Creating a new Kafka consumer Persister...
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: Configuration is:
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: {'group_id': 'persister-group', 'bootstrap_servers': ['kafka:9092']}
> persister_1                   | [19/02/19 - 12:13:10] |consumer| INFO: ... consumer created.
> persister_1                   | [19/02/19 - 12:13:10] |messenger| INFO: Registering new callback for subject dojot.tenancy and event message
> persister_1                   | [19/02/19 - 12:13:10] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:13:10] |http_requester| DEBUG: Remaining attempts: 3
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: Got an answer from HTTP endpoint.
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: ... data retrieved from endpoint.
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Retrieved list of tenants
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Bootstraping tenant: admin
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Received message in tenanct subject.
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: Tenant is: dojot-management
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: Message is: {"tenant": "admin"}
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Emitting new event new-tenant for subject dojot.tenancy@dojot-management
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: No one is listening to subject dojot.tenancy new-tenant events
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: admin bootstrapped.
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: tenants: ['admin']
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Finished tenant boostrapping
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Creating channel for subject: dojot.device-manager.device
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: tenants in create channel: ['admin']
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Bootstraping tenant admin for subject dojot.device-manager.device
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: Global: False, mode: r
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Requesting topic for dojot.device-manager.device@admin
> persister_1                   | [19/02/19 - 12:13:11] |topic_manager| DEBUG: Getting a topic for dojot.device-manager.device@admin...
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: Remaining attempts: 3
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: Got an answer from HTTP endpoint.
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: ... data retrieved from endpoint.
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Got topics: "325e1896-55a1-4d23-aaeb-a7e4ca2ae9b9"
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Got topic for subject dojot.device-manager.device and tenant admin: 325e1896-55a1-4d23-aaeb-a7e4ca2ae9b9
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Telling consumer to subscribe to new topic
> persister_1                   | [19/02/19 - 12:13:11] |consumer| INFO: Got a new topic to subscribe: 325e1896-55a1-4d23-aaeb-a7e4ca2ae9b9
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Starting consumer thread...
> persister_1                   | [19/02/19 - 12:13:11] |consumer| DEBUG: Now running consumer for topics: ['325e1896-55a1-4d23-aaeb-a7e4ca2ae9b9']
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: ... consumer thread was successfully started.
> persister_1                   | [19/02/19 - 12:13:11] |consumer| DEBUG: Subscribing to a new list of topics...
> persister_1                   | [19/02/19 - 12:13:11] |consumer| DEBUG: Holding off a bit before performing the subscription...
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Creating channel for subject: device-data
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: tenants in create channel: ['admin']
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Bootstraping tenant admin for subject device-data
> persister_1                   | [19/02/19 - 12:13:11] |messenger| DEBUG: Global: False, mode: r
> persister_1                   | [19/02/19 - 12:13:11] |messenger| INFO: Requesting topic for device-data@admin
> persister_1                   | [19/02/19 - 12:13:11] |topic_manager| DEBUG: Getting a topic for device-data@admin...
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: Retrieving data from HTTP endpoint...
> persister_1                   | [19/02/19 - 12:13:11] |http_requester| DEBUG: Remaining attempts: 3
> persister_1                   | [19/02/19 - 12:13:12] |http_requester| DEBUG: Got an answer from HTTP endpoint.
> persister_1                   | [19/02/19 - 12:13:12] |http_requester| DEBUG: ... data retrieved from endpoint.
> persister_1                   | [19/02/19 - 12:13:12] |messenger| INFO: Got topics: "8fab3ddd-64e7-4eb2-98c7-a789241f54c1"
> persister_1                   | [19/02/19 - 12:13:12] |messenger| INFO: Got topic for subject device-data and tenant admin: 8fab3ddd-64e7-4eb2-98c7-a789241f54c1
> persister_1                   | [19/02/19 - 12:13:12] |messenger| INFO: Telling consumer to subscribe to new topic
> persister_1                   | [19/02/19 - 12:13:12] |consumer| INFO: Got a new topic to subscribe: 8fab3ddd-64e7-4eb2-98c7-a789241f54c1
> persister_1                   | [19/02/19 - 12:13:12] |messenger| DEBUG: Consumer thread is already started
> persister_1                   | [19/02/19 - 12:13:12] |messenger| INFO: Registering new callback for subject dojot.device-manager.device and event message
> persister_1                   | [19/02/19 - 12:13:12] |messenger| INFO: Registering new callback for subject device-data and event message
> persister_1                   | [19/02/19 - 12:13:12] |persister| DEBUG: ... dojot messenger was successfully initialized.
> persister_1                   | [19/02/19 - 12:13:12] |consumer| DEBUG: Ok, woke up just now.
> persister_1                   | [19/02/19 - 12:13:12] |consumer| DEBUG: ... no further changes in topic list.
> persister_1                   | [19/02/19 - 12:13:12] |consumer| DEBUG: Creating subscriptions...
> persister_1                   | [19/02/19 - 12:13:12] |consumer| INFO: Current topic list: ['fc1c8c9d-2b14-40e1-846a-87b3665e61d8']
> persister_1                   | [19/02/19 - 12:13:12] |consumer| DEBUG: Current subscriptions: {'fc1c8c9d-2b14-40e1-846a-87b3665e61d8'}
> persister_1                   | [19/02/19 - 12:13:12] |consumer| DEBUG: ... subscriptions created
> persister_1                   | [19/02/19 - 12:13:12] |consumer| DEBUG: ... successfully subscribed to new list of topics.
> persister_1                   | [19/02/19 - 12:13:13] |consumer| DEBUG: Ok, woke up just now.
> persister_1                   | [19/02/19 - 12:13:13] |consumer| DEBUG: ... changes detected.
> persister_1                   | [19/02/19 - 12:13:13] |consumer| DEBUG: Will wait for more changes.
> persister_1                   | [19/02/19 - 12:13:13] |consumer| DEBUG: Holding off a bit before performing the subscription...
> persister_1                   | [19/02/19 - 12:13:15] |consumer| DEBUG: Ok, woke up just now.
> persister_1                   | [19/02/19 - 12:13:15] |consumer| DEBUG: ... no further changes in topic list.
> persister_1                   | [19/02/19 - 12:13:15] |consumer| DEBUG: Creating subscriptions...
> persister_1                   | [19/02/19 - 12:13:15] |consumer| INFO: Current topic list: ['325e1896-55a1-4d23-aaeb-a7e4ca2ae9b9', '8fab3ddd-64e7-4eb2-98c7-a789241f54c1']
> persister_1                   | [19/02/19 - 12:13:15] |consumer| DEBUG: Current subscriptions: {'325e1896-55a1-4d23-aaeb-a7e4ca2ae9b9', '8fab3ddd-64e7-4eb2-98c7-a789241f54c1'}
> persister_1                   | [19/02/19 - 12:13:15] |consumer| DEBUG: ... subscriptions created
> persister_1                   | [19/02/19 - 12:13:15] |consumer| DEBUG: ... successfully subscribed to new list of topics.
