### ISSUE TITLE
The persister restarts when a template is updated

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#828]
**Steps to reproduce the problem:**

1. Edit a template
2. Change template name
3. Click Save

> persister_1                   | [03/01/19 - 17:58:01] |messenger| INFO: Emitting new event message for subject dojot.device-manager.device@admin
> persister_1                   | [03/01/19 - 17:58:01] |persister| INFO: got device event {'event': 'template.update', 'data': {'affected': [], 'template': {'id': 9, 'config_attrs': [{'id': 39, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.055489+00:00', 'type': 'actuator', 'label': 'alerta', 'value_type': 'string'}, {'id': 38, 'static_value': '6000', 'template_id': '9', 'created': '2019-01-03T17:27:46.071595+00:00', 'type': 'meta', 'label': 'device_timeout', 'value_type': 'string'}, {'id': 35, 'static_value': 'mqtt', 'template_id': '9', 'created': '2019-01-03T16:32:40.055914+00:00', 'type': 'meta', 'label': 'protocol', 'value_type': 'string'}], 'data_attrs': [{'id': 28, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.051913+00:00', 'type': 'dynamic', 'label': 'bool', 'value_type': 'bool'}, {'id': 30, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.053658+00:00', 'type': 'dynamic', 'label': 'float', 'value_type': 'float'}, {'id': 29, 'static_value': '', 'template_id': '9', 'metadata': [{'id': 36, 'static_value': 'decimal', 'created': '2019-01-03T16:32:40.056603+00:00', 'type': 'meta', 'label': 'unidade', 'updated': None, 'value_type': 'string'}], 'created': '2019-01-03T16:32:40.053181+00:00', 'type': 'dynamic', 'label': 'gps', 'value_type': 'geo'}, {'id': 31, 'static_value': '', 'template_id': '9', 'metadata': [{'id': 37, 'static_value': 'ms', 'created': '2019-01-03T16:32:40.057102+00:00', 'type': 'meta', 'label': 'unidade', 'updated': None, 'value_type': 'string'}], 'created': '2019-01-03T16:32:40.054118+00:00', 'type': 'dynamic', 'label': 'int', 'value_type': 'integer'}, {'id': 32, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.054572+00:00', 'type': 'dynamic', 'label': 'str', 'value_type': 'string'}, {'id': 33, 'static_value': '0000', 'template_id': '9', 'created': '2019-01-03T16:32:40.055028+00:00', 'type': 'static', 'label': 'serialNumber', 'value_type': 'string'}], 'created': '2019-01-03T16:32:40.050611+00:00', 'label': 'template', 'updated': '2019-01-03T17:58:01.348690+00:00', 'attrs': [{'id': 39, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.055489+00:00', 'type': 'actuator', 'label': 'alerta', 'value_type': 'string'}, {'id': 28, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.051913+00:00', 'type': 'dynamic', 'label': 'bool', 'value_type': 'bool'}, {'id': 30, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.053658+00:00', 'type': 'dynamic', 'label': 'float', 'value_type': 'float'}, {'id': 29, 'static_value': '', 'template_id': '9', 'metadata': [{'id': 36, 'static_value': 'decimal', 'created': '2019-01-03T16:32:40.056603+00:00', 'type': 'meta', 'label': 'unidade', 'updated': None, 'value_type': 'string'}], 'created': '2019-01-03T16:32:40.053181+00:00', 'type': 'dynamic', 'label': 'gps', 'value_type': 'geo'}, {'id': 31, 'static_value': '', 'template_id': '9', 'metadata': [{'id': 37, 'static_value': 'ms', 'created': '2019-01-03T16:32:40.057102+00:00', 'type': 'meta', 'label': 'unidade', 'updated': None, 'value_type': 'string'}], 'created': '2019-01-03T16:32:40.054118+00:00', 'type': 'dynamic', 'label': 'int', 'value_type': 'integer'}, {'id': 32, 'static_value': '', 'template_id': '9', 'created': '2019-01-03T16:32:40.054572+00:00', 'type': 'dynamic', 'label': 'str', 'value_type': 'string'}, {'id': 38, 'static_value': '6000', 'template_id': '9', 'created': '2019-01-03T17:27:46.071595+00:00', 'type': 'meta', 'label': 'device_timeout', 'value_type': 'string'}, {'id': 35, 'static_value': 'mqtt', 'template_id': '9', 'created': '2019-01-03T16:32:40.055914+00:00', 'type': 'meta', 'label': 'protocol', 'value_type': 'string'}, {'id': 33, 'static_value': '0000', 'template_id': '9', 'created': '2019-01-03T16:32:40.055028+00:00', 'type': 'static', 'label': 'serialNumber', 'value_type': 'string'}]}}, 'meta': {'service': 'admin'}}
> persister_1                   | Exception in thread Thread-2:
> persister_1                   | Traceback (most recent call last):
> persister_1                   |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> persister_1                   |     self.run()
> persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a1-py3.6.egg/dojot/module/kafka/consumer.py", line 75, in run
> persister_1                   |     self.callback(msg.topic, msg.value)
> persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a1-py3.6.egg/dojot/module/messenger.py", line 319, in __process_kafka_messages
> persister_1                   |     self.emit(self.topics[topic]['subject'], self.topics[topic]['tenant'], "message", messages)
> persister_1                   |   File "/usr/src/venv/lib/python3.6/site-packages/dojot.module-0.0.1a1-py3.6.egg/dojot/module/messenger.py", line 180, in emit
> persister_1                   |     callback(tenant, data)
> persister_1                   |   File "history/subscriber/persister.py", line 162, in handle_event_devices
> persister_1                   |     collection_name = "{}_{}".format(data['meta']['service'], data['data']['id'])
> persister_1                   | KeyError: 'id'
> persister_1                   |

4. Edit any template
5. Click Save. The persister restarts.

> persister_1                   |
> dojot_persister_1 exited with code 0
> 

**Affected Version**: 0.3.0-nightly20181227

**Comment by betefaber** [comment]
Test **OK** at baseline **training-20190122**.

The issue will be validated at the next baseline.

**Comment by betefaber** [comment]
Test OK.
