### ISSUE TITLE
Failed to create a template

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#887]
**Steps to reproduce the problem:**

1. Create a template
2. Add attribute with space in name

![createtemplate](https://user-images.githubusercontent.com/37310063/51694185-67bf2f80-1fe7-11e9-8de8-d59871bd5606.png)

> device-manager_1              | [2019-01-24 16:12:37,957] ERROR in app: Exception on /template [POST]
> device-manager_1              | Traceback (most recent call last):
> device-manager_1              |   File "/usr/src/app/DeviceManager/SerializationModels.py", line 99, in load_attrs
> device-manager_1              |     entity = attr_schema.load(attr)
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 498, in load
> device-manager_1              |     return self._do_load(data, many, partial=partial, postprocess=True)
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 621, in _do_load
> device-manager_1              |     raise exc
> device-manager_1              | marshmallow.exceptions.ValidationError: {'label': ['Labels must contain letters, numbers or dashes(-_)']}
> device-manager_1              |
> device-manager_1              | During handling of the above exception, another exception occurred:
> device-manager_1              |
> device-manager_1              | Traceback (most recent call last):
> device-manager_1              |   File "/usr/src/app/DeviceManager/TemplateHandler.py", line 309, in flask_create_template
> device-manager_1              |     result = TemplateHandler.create_template(request)
> device-manager_1              |   File "/usr/src/app/DeviceManager/TemplateHandler.py", line 131, in create_template
> device-manager_1              |     load_attrs(json_payload['attrs'], loaded_template, DeviceAttr, db)
> device-manager_1              |   File "/usr/src/app/DeviceManager/SerializationModels.py", line 113, in load_attrs
> device-manager_1              |     raise HTTPRequestError(400, results)
> device-manager_1              | DeviceManager.utils.HTTPRequestError
> device-manager_1              |
> device-manager_1              | During handling of the above exception, another exception occurred:
> device-manager_1              |
> device-manager_1              | Traceback (most recent call last):
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
> device-manager_1              |     response = self.full_dispatch_request()
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
> device-manager_1              |     rv = self.handle_user_exception(e)
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
> device-manager_1              |     reraise(exc_type, exc_value, tb)
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
> device-manager_1              |     raise value
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
> device-manager_1              |     rv = self.dispatch_request()
> device-manager_1              |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
> device-manager_1              |     return self.view_functions[rule.endpoint](**req.view_args)
> device-manager_1              |   File "/usr/src/app/DeviceManager/TemplateHandler.py", line 320, in flask_create_template
> device-manager_1              |     LOGGER.error(f" {e}")
> device-manager_1              | UnboundLocalError: local variable 'e' referenced before assignment

**Comment by betefaber** [comment]
It is not allowed to create an attribute with white space in the name.

![Screenshot_199](https://user-images.githubusercontent.com/37310063/56372365-349acf80-61d5-11e9-95ff-5e0ce608e954.png)

But the displayed error message should be improved, indicating that the name must contain letters, numbers or dashes (-_).

![Screenshot_198](https://user-images.githubusercontent.com/37310063/56372386-40869180-61d5-11e9-80ae-03a748b1ac1d.png)

**log is empty:**

`device-manager_1              | [18/04/19 - 14:54:41] |TemplateHandler| ERROR:`

Tested on version: 58.2-20190321

**Comment by betefaber** [comment]
Test OK.

_Label for attrs and metas: only letters (a-z), numbers (0-9) , hyphens (-), two points (:) and underscores (_).
Label for device, template and flow-name: only letters (a-z), numbers (0-9) , spaces ( ), hyphens (-), two points (:) and underscores (_)._

- GUI

![image](https://user-images.githubusercontent.com/37310063/56767784-06902f00-6783-11e9-8486-a1ef7da7361a.png)

- API

![image](https://user-images.githubusercontent.com/37310063/56768064-b8c7f680-6783-11e9-8f62-7d877567eaa8.png)
