### ISSUE TITLE
[Flowbroker] No flow runs after running a flow with email

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#916]
**Steps to reproduce the problem:**

1. create a basic flow
2. create an email flow
3. run the basic flow
- the basic flow is executed:

> flowbroker_1                  | <19:33:04 12/02/2019> -- DEBUG: Got a message in topic 41fa6ea0-95bd-4844-b562-86cc76a4b836.
> flowbroker_1                  | <19:33:04 12/02/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <19:33:04 12/02/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 62 65 30 38 64 63 22 2c 22 74
> 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 95,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '41fa6ea0-95bd-4844-b562-86cc76a4b836',
> flowbroker_1                  |   offset: 12,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1549999983358 }
> flowbroker_1                  | <19:33:04 12/02/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:33:04 12/02/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"be08dc","tenant":"admin","timestamp":1549999983358},"attrs":{"int":1}}
> flowbroker_1                  | <19:33:04 12/02/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"be08dc","tenant":"admin","timestamp":1549999983358},"attrs":{"int":1}}
> flowbroker_1                  | <19:33:04 12/02/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'be08dc', tenant: 'admin', timestamp: 1549999983358 },
> flowbroker_1                  |   attrs: { int: 1 } }
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"int":1,"serial":"indefinido"}}]
> flowbroker_1                  | debug: Executing change node...
> flowbroker_1                  | debug: ... change node was successfully executed.
> flowbroker_1                  | [executor] will handle node change
> flowbroker_1                  | [executor] hop (change) result: [{"payload":{"int":1,"serial":"indefinido"},"saida":{"str":"teste bÃ¡sico"}}]
> flowbroker_1                  | [executor] will handle node device out
> flowbroker_1                  | debug: Executing device-out node...
> flowbroker_1                  | debug: Updating device...
> flowbroker_1                  | debug: Message is: { attrs: { str: 'teste bÃ¡sico' },
> flowbroker_1                  |   metadata: { deviceid: 'be08dc', timestamp: 1549999984593, tenant: 'admin' } }
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to device-data:admin
> flowbroker_1                  | <19:33:04 12/02/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'dojot.device-manager.device': { admin: '67ec6cb4-f678-454c-aaf2-85d2fb9b9bb8' },
> 39m
> flowbroker_1                  |   'device-data': { admin: '41fa6ea0-95bd-4844-b562-86cc76a4b836' } }
> flowbroker_1                  | debug: ... device was updated.
> flowbroker_1                  | debug: ... device-out node was successfully executed.
> flowbroker_1                  | [executor] hop (device out) result: undefined
> flowbroker_1                  | <19:33:06 12/02/2019> -- DEBUG: Got a message in topic 41fa6ea0-95bd-4844-b562-86cc76a4b836.
> flowbroker_1                  | <19:33:06 12/02/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <19:33:06 12/02/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 61 74 74 72 73 22 3a 7b 22 73 74 72 22 3a 22 74 65 73 74 65 20 62 c3 a1 73 69 63 6f 22 7d 2c 22 6d
> 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 ... >,
> flowbroker_1                  |   size: 109,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '41fa6ea0-95bd-4844-b562-86cc76a4b836',
> flowbroker_1                  |   offset: 13,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1549999984594 }
> flowbroker_1                  | <19:33:06 12/02/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:33:06 12/02/2019> -- DEBUG: Queued event {"attrs":{"str":"teste bÃ¡sico"},"metadata":{"deviceid":"be08dc","timestamp":1549999984593,"tenant":"admin"}}
> flowbroker_1                  | <19:33:06 12/02/2019> -- DEBUG: Pre-processing event {"attrs":{"str":"teste bÃ¡sico"},"metadata":{"deviceid":"be08dc","timestamp":1549999984593,"tenant":"admin"}}
> flowbroker_1                  | <19:33:06 12/02/2019> -- DEBUG: [ingestor] got new device event: { attrs: { str: 'teste bÃ¡sico' },
> flowbroker_1                  |   metadata: { deviceid: 'be08dc', timestamp: 1549999984593, tenant: 'admin' } }
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [null]

4. run the email flow

> flowbroker_1                  | <19:37:18 12/02/2019> -- DEBUG: Got a message in topic 41fa6ea0-95bd-4844-b562-86cc76a4b836.
> flowbroker_1                  | <19:37:18 12/02/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <19:37:18 12/02/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 62 65 30 38 64 63 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 101,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '41fa6ea0-95bd-4844-b562-86cc76a4b836',
> flowbroker_1                  |   offset: 14,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1550000237023 }
> flowbroker_1                  | <19:37:18 12/02/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:37:18 12/02/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"be08dc","tenant":"admin","timestamp":1550000237023},"attrs":{"str":"teste"}}
> flowbroker_1                  | <19:37:18 12/02/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"be08dc","tenant":"admin","timestamp":1550000237023},"attrs":{"str":"teste"}}
> flowbroker_1                  | <19:37:18 12/02/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'be08dc', tenant: 'admin', timestamp: 1550000237023 },
> flowbroker_1                  |   attrs: { str: 'teste' } }
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [null]
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"str":"teste","serial":"indefinido"}}]
> flowbroker_1                  | [executor] will handle node template
> flowbroker_1                  | debug: Executing template node...
> flowbroker_1                  | debug: ... template node was successfully executed.
> flowbroker_1                  | [executor] hop (template) result: [{"payload":{"str":"teste","serial":"indefinido"},"emailBody":"teste do nÃ³ email"}]
> flowbroker_1                  | [executor] will handle node email
> flowbroker_1                  | debug: Executing e-mail node...
> flowbroker_1                  | debug: Preparing e-mail options...
> flowbroker_1                  | debug: ... e-mail options were successfully build
> flowbroker_1                  | debug: E-mail will be sent as:
> flowbroker_1                  | debug: { subject: 'aviso',
> flowbroker_1                  |   to: 'bete@cpqd.com.br',
> flowbroker_1                  |   from: 'dojotcpqd@gmail.com',
> flowbroker_1                  |   text: 'teste do nÃ³ email' }
> flowbroker_1                  | debug: Preparing SMTP transport handler...
> flowbroker_1                  | debug: Using e-mail config: { host: 'gmail-smtp-in.l.google.com', port: '25', secure: false }
> flowbroker_1                  | debug: ... e-mail transport was successfully created.
> flowbroker_1                  | debug: Sending e-mail...
> flowbroker_1                  | <19:37:18 12/02/2019> -- |undefined -- ERROR: uncaughtException: Cannot read property 'then' of undefined
> flowbroker_1                  | TypeError: Cannot read property 'then' of undefined
> flowbroker_1                  |     at Executor.hop (/opt/flowbroker/orchestrator/src/executor.js:50:17)
> flowbroker_1                  |     at channel.consume (/opt/flowbroker/orchestrator/src/amqp.js:107:9)
> flowbroker_1                  |     at Channel.BaseChannel.dispatchMessage (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:466:12)
> flowbroker_1                  |     at Channel.BaseChannel.handleDelivery (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:475:15)
> flowbroker_1                  |     at emitOne (events.js:116:13)
> flowbroker_1                  |     at Channel.emit (events.js:211:7)
> flowbroker_1                  |     at /opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:263:10
> flowbroker_1                  |     at Channel.content [as handleMessage] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:316:9)
> flowbroker_1                  |     at Channel.C.acceptMessageFrame (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:231:31)
> flowbroker_1                  |     at Channel.C.accept (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/channel.js:384:17)
> flowbroker_1                  |     at Connection.mainAccept [as accept] (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:64:33)
> flowbroker_1                  |     at Socket.go (/opt/flowbroker/orchestrator/node_modules/amqplib/lib/connection.js:477:48)
> flowbroker_1                  |     at emitNone (events.js:106:13)
> flowbroker_1                  |     at Socket.emit (events.js:208:7)
> flowbroker_1                  |     at emitReadable_ (_stream_readable.js:513:10)
> flowbroker_1                  |     at emitReadable (_stream_readable.js:507:7)
> flowbroker_1                  | debug: ... e-mail node was not successfully executed.
> flowbroker_1                  | error: Error while executing e-mail node: Error: connect ECONNREFUSED 172.217.192.26:25
> flowbroker_1                  | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 172.217.192.26:25
> flowbroker_1                  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
> flowbroker_1                  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
> flowbroker_1                  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![image](https://user-images.githubusercontent.com/37310063/52665084-d6f6b800-2ef1-11e9-9127-991665972b9c.png)

5. run the basic flow again
- the basic flow is not executed:

> flowbroker_1                  | <19:39:18 12/02/2019> -- DEBUG: Got a message in topic 41fa6ea0-95bd-4844-b562-86cc76a4b836.
> flowbroker_1                  | <19:39:18 12/02/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <19:39:18 12/02/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 62 65 30 38 64 63 22 2c 22 74
> 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 95,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '41fa6ea0-95bd-4844-b562-86cc76a4b836',
> flowbroker_1                  |   offset: 15,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1550000357887 }
> flowbroker_1                  | <19:39:18 12/02/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <19:39:18 12/02/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"be08dc","tenant":"admin","timestamp":1550000357886},"attrs":{"int":1}}
> flowbroker_1                  | <19:39:18 12/02/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"be08dc","tenant":"admin","timestamp":1550000357886},"attrs":{"int":1}}
> flowbroker_1                  | <19:39:18 12/02/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'be08dc', tenant: 'admin', timestamp: 1550000357886 },
> flowbroker_1                  |   attrs: { int: 1 } }
> flowbroker_1                  | debug: Checking memory.

**Affected Version:** 0.3.0-nightly20190207

**Comment by betefaber** [comment]
Test OK.

- running the basic flow:

> flowbroker_1                  | <20:11:43 20/03/2019> -- DEBUG: Got a message in topic 7e350993-47b6-47ff-aa0a-a59fe559bc6d.
> flowbroker_1                  | <20:11:43 20/03/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <20:11:43 20/03/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 62 38 35 64 64 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c 22 ... >,
> flowbroker_1                  |   size: 102,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |   offset: 5,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1553112702451 }
> flowbroker_1                  | <20:11:43 20/03/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <20:11:43 20/03/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"b85dd","tenant":"admin","timestamp":1553112702451},"attrs":{"velocidade":60}}
> flowbroker_1                  | <20:11:43 20/03/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"b85dd","tenant":"admin","timestamp":1553112702451},"attrs":{"velocidade":60}}
> flowbroker_1                  | <20:11:43 20/03/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'b85dd', tenant: 'admin', timestamp: 1553112702451 },
> flowbroker_1                  |   attrs: { velocidade: 60 } }
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"velocidade":60}}]
> flowbroker_1                  | [executor] will handle node change
> flowbroker_1                  | debug: Executing change node...
> flowbroker_1                  | debug: ... change node was successfully executed.
> flowbroker_1                  | [executor] hop (change) result: [{"payload":{"velocidade":60},"saida":{"mensagem":"vento muito forte!!!"}}]
> flowbroker_1                  | [executor] will handle node device out
> flowbroker_1                  | debug: Executing device-out node...
> flowbroker_1                  | debug: Updating device...
> flowbroker_1                  | debug: Message is: { attrs: { mensagem: 'vento muito forte!!!' },
> flowbroker_1                  |   metadata: { timestamp: 1553112703490, tenant: 'admin' } }
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to device-data:admin
> flowbroker_1                  | <20:11:43 20/03/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data':
> flowbroker_1                  |    { admin: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |      teste: 'febd67b3-cebf-49fd-817d-16152aa07b2e' },
> flowbroker_1                  |   'dojot.device-manager.device':
> flowbroker_1                  |    { admin: '457baa44-45ca-40d3-889c-8dcfb736ccb3',
> flowbroker_1                  |      teste: '8bcac85a-95a6-4072-9979-d33f377232aa' } }
> flowbroker_1                  | debug: ... device was updated.
> flowbroker_1                  | debug: ... device-out node was successfully executed.
> flowbroker_1                  | [executor] hop (device out) result: undefined
> flowbroker_1                  | <20:11:44 20/03/2019> -- DEBUG: Got a message in topic 7e350993-47b6-47ff-aa0a-a59fe559bc6d.
> flowbroker_1                  | <20:11:44 20/03/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <20:11:44 20/03/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 61 74 74 72 73 22 3a 7b 22 6d 65 6e 73 61 67 65 6d 22 3a 22 76 65 6e 74 6f 20 6d 75 69 74 6f 20 66 6f 72 74 65 21 21 21 22 7d 2c 22 6d 65 74 61 ... >,
> flowbroker_1                  |   size: 121,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |   offset: 6,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1553112703491 }
> flowbroker_1                  | <20:11:44 20/03/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <20:11:44 20/03/2019> -- DEBUG: Queued event {"attrs":{"mensagem":"vento muito forte!!!"},"metadata":{"timestamp":1553112703490,"tenant":"admin","deviceid":"72db40"}}
> flowbroker_1                  | <20:11:44 20/03/2019> -- DEBUG: Pre-processing event {"attrs":{"mensagem":"vento muito forte!!!"},"metadata":{"timestamp":1553112703490,"tenant":"admin","deviceid":"72db40"}}
> flowbroker_1                  | <20:11:44 20/03/2019> -- DEBUG: [ingestor] got new device event: { attrs: { mensagem: 'vento muito forte!!!' },
> flowbroker_1                  |   metadata: { timestamp: 1553112703490, tenant: 'admin', deviceid: '72db40' } }
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully


- running the email flow:

> flowbroker_1                  | <20:16:53 20/03/2019> -- DEBUG: Got a message in topic 7e350993-47b6-47ff-aa0a-a59fe559bc6d.
> flowbroker_1                  | <20:16:53 20/03/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <20:16:53 20/03/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 32 30 33 37 39 33 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c ... >,
> flowbroker_1                  |   size: 104,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |   offset: 8,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1553113012492 }
> flowbroker_1                  | <20:16:53 20/03/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <20:16:53 20/03/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"203793","tenant":"admin","timestamp":1553113012491},"attrs":{"temperatura":32}}
> flowbroker_1                  | <20:16:53 20/03/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"203793","tenant":"admin","timestamp":1553113012491},"attrs":{"temperatura":32}}
> flowbroker_1                  | <20:16:53 20/03/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: '203793', tenant: 'admin', timestamp: 1553113012491 },
> flowbroker_1                  |   attrs: { temperatura: 32 } }
> flowbroker_1                  | [redis] storing device info on cache . . .
> flowbroker_1                  | [redis] . . . device info stored successfully
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"temperatura":32}}]
> flowbroker_1                  | [executor] will handle node template
> flowbroker_1                  | debug: Executing template node...
> flowbroker_1                  | [executor] hop (template) result: [{"payload":{"temperatura":32},"emailBody":"Temperatura muito alta: 32 Â°C !"}]
> flowbroker_1                  | [executor] will handle node email
> flowbroker_1                  | debug: ... template node was successfully executed.
> flowbroker_1                  | debug: Executing e-mail node...
> flowbroker_1                  | debug: Preparing e-mail options...
> flowbroker_1                  | debug: ... e-mail options were successfully build
> flowbroker_1                  | debug: E-mail will be sent as:
> flowbroker_1                  | debug: { subject: 'aviso',
> flowbroker_1                  |   to: 'bete@cpqd.com.br',
> flowbroker_1                  |   from: 'dojotcpqd@gmail.com',
> flowbroker_1                  |   text: 'Temperatura muito alta: 32 Â°C !' }
> flowbroker_1                  | debug: Preparing SMTP transport handler...
> flowbroker_1                  | debug: Using e-mail config: { host: 'gmail-smtp-in.l.google.com',
> flowbroker_1                  |   port: '25',
> flowbroker_1                  |   secure: 'false' }
> flowbroker_1                  | debug: ... e-mail transport was successfully created.
> flowbroker_1                  | debug: Sending e-mail...
> flowbroker_1                  | debug: ... e-mail node was not successfully executed.
> flowbroker_1                  | error: Error while executing e-mail node: Error: connect ECONNREFUSED 172.217.192.26:25
> flowbroker_1                  | [executor] Node execution failed. Error: connect ECONNREFUSED 172.217.192.26:25. Aborting flow 179e1e67-9f24-40b2-aae5-3d3637521dca.


- running the basic flow again:

> flowbroker_1                  | <20:17:44 20/03/2019> -- DEBUG: Got a message in topic 7e350993-47b6-47ff-aa0a-a59fe559bc6d.
> flowbroker_1                  | <20:17:44 20/03/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <20:17:44 20/03/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 6d 65 74 61 64 61 74 61 22 3a 7b 22 64 65 76 69 63 65 69 64 22 3a 22 62 38 35 64 64 22 2c 22 74 65 6e 61 6e 74 22 3a 22 61 64 6d 69 6e 22 2c 22 ... >,
> flowbroker_1                  |   size: 102,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |   offset: 9,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1553113063820 }
> flowbroker_1                  | <20:17:44 20/03/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <20:17:44 20/03/2019> -- DEBUG: Queued event {"metadata":{"deviceid":"b85dd","tenant":"admin","timestamp":1553113063820},"attrs":{"velocidade":70}}
> flowbroker_1                  | <20:17:44 20/03/2019> -- DEBUG: Pre-processing event {"metadata":{"deviceid":"b85dd","tenant":"admin","timestamp":1553113063820},"attrs":{"velocidade":70}}
> flowbroker_1                  | <20:17:44 20/03/2019> -- DEBUG: [ingestor] got new device event: { metadata: { deviceid: 'b85dd', tenant: 'admin', timestamp: 1553113063820 },
> flowbroker_1                  |   attrs: { velocidade: 70 } }
> flowbroker_1                  | [executor] will handle node switch
> flowbroker_1                  | [executor] hop (switch) result: [{"payload":{"velocidade":70}}]
> flowbroker_1                  | debug: Executing switch node...
> flowbroker_1                  | debug: ... switch node was successfully executed.
> flowbroker_1                  | [executor] will handle node change
> flowbroker_1                  | debug: Executing change node...
> flowbroker_1                  | debug: ... change node was successfully executed.
> flowbroker_1                  | [executor] hop (change) result: [{"payload":{"velocidade":70},"saida":{"mensagem":"vento muito forte!!!"}}]
> flowbroker_1                  | [executor] will handle node device out
> flowbroker_1                  | debug: Executing device-out node...
> flowbroker_1                  | debug: Updating device...
> flowbroker_1                  | debug: Message is: { attrs: { mensagem: 'vento muito forte!!!' },
> flowbroker_1                  |   metadata: { timestamp: 1553113064830, tenant: 'admin' } }
> flowbroker_1                  | object
> flowbroker_1                  | will produce [object Object] to device-data:admin
> flowbroker_1                  | <20:17:44 20/03/2019> -- |messenger -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data':
> flowbroker_1                  |    { admin: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |      teste: 'febd67b3-cebf-49fd-817d-16152aa07b2e' },
> flowbroker_1                  |   'dojot.device-manager.device':
> flowbroker_1                  |    { admin: '457baa44-45ca-40d3-889c-8dcfb736ccb3',
> flowbroker_1                  |      teste: '8bcac85a-95a6-4072-9979-d33f377232aa' } }
> flowbroker_1                  | debug: ... device was updated.
> flowbroker_1                  | [executor] hop (device out) result: undefined
> flowbroker_1                  | debug: ... device-out node was successfully executed.
> flowbroker_1                  | <20:17:45 20/03/2019> -- DEBUG: Got a message in topic 7e350993-47b6-47ff-aa0a-a59fe559bc6d.
> flowbroker_1                  | <20:17:45 20/03/2019> -- DEBUG: There are 1 callbacks registered.
> flowbroker_1                  | <20:17:45 20/03/2019> -- |messenger -- DEBUG: Received message: { value: <Buffer 7b 22 61 74 74 72 73 22 3a 7b 22 6d 65 6e 73 61 67 65 6d 22 3a 22 76 65 6e 74 6f 20 6d 75 69 74 6f 20 66 6f 72 74 65 21 21 21 22 7d 2c 22 6d 65 74 61 ... >,
> flowbroker_1                  |   size: 121,
> flowbroker_1                  |   key: null,
> flowbroker_1                  |   topic: '7e350993-47b6-47ff-aa0a-a59fe559bc6d',
> flowbroker_1                  |   offset: 10,
> flowbroker_1                  |   partition: 0,
> flowbroker_1                  |   timestamp: 1553113064830 }
> flowbroker_1                  | <20:17:45 20/03/2019> -- |messenger -- DEBUG: Emitting new event message for subject device-data@admin
> flowbroker_1                  | <20:17:45 20/03/2019> -- DEBUG: Queued event {"attrs":{"mensagem":"vento muito forte!!!"},"metadata":{"timestamp":1553113064830,"tenant":"admin","deviceid":"72db40"}}
> flowbroker_1                  | <20:17:45 20/03/2019> -- DEBUG: Pre-processing event {"attrs":{"mensagem":"vento muito forte!!!"},"metadata":{"timestamp":1553113064830,"tenant":"admin","deviceid":"72db40"}}
> flowbroker_1                  | <20:17:45 20/03/2019> -- DEBUG: [ingestor] got new device event: { attrs: { mensagem: 'vento muito forte!!!' },
> flowbroker_1                  |   metadata: { timestamp: 1553113064830, tenant: 'admin', deviceid: '72db40' } }
